### ISSUE TITLE
Log rotation not working

### ISSUE THREAD

**Issue by aw197** [StamusNetworks/SELKS#100]
Running SELKS 4 on 4 different boxes, having issues with a lag occurring in evebox in all environments which grows over time.   However, this issue being reported is related to the log file rotation. We noticed that the drive space is filling up and log rotation process mentioned [here](https://github.com/StamusNetworks/SELKS/wiki/Logrotate) doesn't seem to be working. 

Set to keep 7 days of logs
![image](https://user-images.githubusercontent.com/8451159/34881190-e1a77ebe-f780-11e7-9267-155db057a0e1.png)

Log files in /var/log/suricata/StatsbyDate/ are more than 7 days
![image](https://user-images.githubusercontent.com/8451159/34881104-999c7eda-f780-11e7-88d7-4884b44e3840.png)

Attempted forcing log rotation, but files remain.
![image](https://user-images.githubusercontent.com/8451159/34881293-2e70f180-f781-11e7-97a2-3a0b3a7aee4c.png)

Additional observations:

logstash.pid does not seem to exist in /var/run/
![image](https://user-images.githubusercontent.com/8451159/34881422-8727f152-f781-11e7-9d94-fe21c4c4f586.png)

Noticed that there is suricata log rotation script in /opt/selks/Scripts/Configs/SELKS4/Logrotate/etc/logrotate.d  - is this just part of the OS setup and copied to /etc/logrotate.d/ ?
![image](https://user-images.githubusercontent.com/8451159/34881659-29a1465e-f782-11e7-8b93-fccd9970370f.png)

**Comment by pevma** [comment]
It seems the logrotate is working from the posted screenshots as you have a daily logs being rotated in `StatsByDay` folder. 

There is also two parts of the `forcing` of the logrotation in that particular case.
- if you already have  a log with that date in `StatsByDay` folder  -it will not be overwritten (you can try adding `-v` to the command for more verbosity)
- the logstash HUP signal fails as there is no `/var/run/logstash.pid` (bug). The fix would be to replace
 
``/bin/kill -HUP $(cat /var/run/logstash.pid)``  
with   
``/bin/systemctl kill -s HUP --kill-who=main logstash.service``  
in the ``/etc/logrotate.d/suricata``.

**Comment by aw197** [comment]
Thanks for your response.  Yes, your right based on the daily log files, rotation is working - should have been obvious.  What I really should have said is that the older files are not getting deleted.  

I updated the script with your fix and ran "logrotate --force /etc/logrotate.d/suricata".  I see that it created a gz file (eve.json-20180118.gz).  Is there a reason the older files still remain and were not removed?  Or will the cleanup happen going forward from this date, now that the script has been updated?  TIA


![image](https://user-images.githubusercontent.com/8451159/35113729-7b5b3216-fc50-11e7-83d1-1650504ca0e0.png)

**Comment by pevma** [comment]
yes correct - it should be from this date forward since you made the changes.

**Comment by aw197** [comment]
Thanks pevma, log rotation is now working correctly.

**Comment by pevma** [comment]
Thank you for the update and feedback!
