### ISSUE TITLE
Elasticsearch cluster

### ISSUE THREAD

**Issue by hawatius** [StamusNetworks/SELKS#102]
Hi!
After the Elasticsearch node was added, the data graphs were no longer displayed.
![ids](https://user-images.githubusercontent.com/19649806/36094803-a9b9a80e-1000-11e8-9cb7-88a593e501bd.jpg)
![ids2](https://user-images.githubusercontent.com/19649806/36094807-afdad6cc-1000-11e8-9e60-9c315f81e11d.jpg)
`Linux ids 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
`
`This is Suricata version 4.1.0-dev (rev cba41207)`
Help me!

**Comment by pevma** [comment]
Hi,
It should not need anything specific...
Could you please provide how you added the node ?

**Comment by hawatius** [comment]
Installed the server Elasticsearch.
Made changes to the file /etc/elasticsearch/elasticsearch.yml
SELKS
```
cluster.name: elasticsearch
node.name: ids
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["ids", "ids-data1"]
discovery.zen.minimum_master_nodes: 1
node.master: true
node.data: true
```
elasticsearch
```
cluster.name: elasticsearch
node.name: ids-data1
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["ids", "ids-data1"]
discovery.zen.minimum_master_nodes: 1
node.master: false
node.data: true
```

**Comment by hawatius** [comment]
If you turn off the IPv6, the graphs disappear.
Thanks for the help, the problem is solved.

**Comment by pevma** [comment]
@hawatius  - thanks for posting the solution ! Out of curiosity how did you turned it off?

**Comment by hawatius** [comment]
Added to file /etc/sysctl.conf
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
