### ISSUE TITLE
Change type Dashboard - SN Alert (heatmap instead of points)

### ISSUE THREAD

**Issue by berekese** [StamusNetworks/SELKS#111]
Hi, 

I wanted to change the point map of SN-Alert to one of Heatmap. I create a new one going to Visualize and in SN-Alert GeoMap changing by heatmap and pressing "save". That created me a new SN-Alert GeoMap graphic. Now I have 2, the points and the heatmap
How could Scirius change that when you click on "SN-Alert" go to the new heatmap?

Thank you!

**Comment by pevma** [comment]
Are you making a new dashboard or would you like to change one visualization with another in the current dashboard?

**Comment by berekese** [comment]
In current dashboard, SN-Alert I would like to change "points" for "heatmap". 
In Kibana -> Visualize -> I edited SN Alert Geomap with heatmap and I pushed "save" but it creates a new with my value, I want that in Scirius when I push "SN-Alert" I can see it with heatmap. 

Basically change one for another. 
http://i68.tinypic.com/mcrrq1.png

Thanks.

**Comment by pevma** [comment]
If you would like to just replace one visualization with another in a already existing dashboard -  you should open the dashboard, edit it (right upper corner) - remove the visualization and place the new one on its spot. Then save the dashboard. After that when you point to the dashboard from Scirius it will open the new saved one.

**Comment by berekese** [comment]
Hi, 
When I create a new dashboard in Kibana -> (push icon +), it creates a new called "SN-Alert Geomap" for example, now I have two same (SN-Alert GeoMap with points and SN-Alert GeoMap with heatmap). But in Scirius -> SN-Alert go to that dashboard (with points). 
Should I delete the old SN-GeoMap and have another call the same will be replaced? My fear is that it is erased and I can not see any.
http://i63.tinypic.com/av615u.png

Thanks!

**Comment by pevma** [comment]
Are you referring to Visualization or a Dashboard?   
If you have created a new Visualization you can simply use it and  replace the already existing Geomap visualization inside the SN-Alerts dashboard.     
If you would like to create  a new Dashboard - it would be enough to just create and save it. Then reload the Scirius page. Note - Scirius would only show a certain number of Dashboards - up to the first 15 i think or similar.   

Also FYI -  if you do Dashboard reset - any dashboard that does not start with `SN-` would be deleted. so if you need to dont forget to export and save your dashboards.

**Comment by berekese** [comment]
I refer to the SN-Alert in Scirius's dashboard. I want that when I click there it takes me to SN-Alert GeoMap with heatmap and not with points.
So create a new SN-Alert GeoMap in Visualizations, which is called the same, but now I do not know how to tell you that the SN-Alert Dashboard of Scirius takes that new SN-Alert GeoMap with heatmap and not with points.

Thanks.

**Comment by pevma** [comment]
You need to `edit `the Dashboard, delete the old Visualization and put the new Visualization, then save the Dashboard.

**Comment by berekese** [comment]
Hi, 
I edited Dashboard, I added Visualization (SN-Alert GeoMap1) but editing Dashboard I don't see in Visualization the new (alert geomap1). Am I forgetting something?

http://i66.tinypic.com/25s0kjq.png

http://i63.tinypic.com/2mee8gi.png

I am causing you many problems hehe, I'm sorry

**Comment by pevma** [comment]
The new visualization is there - you just need to try to ``filter`` it to get it displayed on the same search page or go through the pages and find it to add it in.

**Comment by berekese** [comment]
Done! all ok :) now yes.

Thanks.

**Comment by pevma** [comment]
Glad you made it work
