### ISSUE TITLE
Documentation clarification needed for file overwrite preference during upgrade

### ISSUE THREAD

**Issue by jgallucci32** [StamusNetworks/SELKS#115]
The documentation upgrades states this
> It is recommended to use SELKS provided version of configuration files as they will guarantee you that the system will work correctly. So answer yes when you are asked for file overwrite might be a good idea in most cases.
>
The verbiage used by the debian installer is slightly different and creates some confusion:
>Configuration file '/etc/logstash/logstash.yml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** logstash.yml (Y/I/N/O/D/Z) [default=N] ?
>
Suggest changing the documentation to state the following
> It is recommended to use the package maintainer's version of configuration files as they will guarantee you that the system will work properly. So answer "Y" when you are asked what you would like to do about configuration file differences during the upgrade. This will be ideal in most cases.

**Comment by pevma** [comment]
Updated - Thank you!
