### ISSUE TITLE
No data for period in Scirius

### ISSUE THREAD

**Issue by JoooostB** [StamusNetworks/SELKS#116]
Just finished a clean install of SELKS for the second time on my ESXi Host. But both times I get the same result: _No data for period_ in Scirius. I ran all the scripts in the Suricata folder to assign and set-up the network interface, but no luck so far.
![image](https://user-images.githubusercontent.com/8641236/39395731-9210b6ee-4ae2-11e8-8de7-6fc40973af93.png)
But when I open Kibana, eve.json or just a tcpdump, there ís data flowing from my network.
![image](https://user-images.githubusercontent.com/8641236/39395784-3bb9e292-4ae3-11e8-8de3-e2f46501f74e.png)
For the record, I did not change my hostname (I've seen a lot of issues related to that)

Hope you can help me out, thanks in advance.

**Comment by pevma** [comment]
Hi,

Thanks for trying out SELKS!
It seems you only have stats - no actual events.

I would suggest checking if all the services are running properly and if Suricata is listening on the correct interface. Also if there is traffic coming up that interface. (Basically double check most of the stuff from “Initial setup” from our wiki )


Let us know how it goes !

> -- 
> Regards,
> Peter Manev

**Comment by JoooostB** [comment]
Hi @pevma,
Thank you for your real quick response, even on a Saturday. Running `systemctl status suricata elasticsearch logstash kibana evebox && supervisorctl status scirius ` all results in _active (running)_

When I run a tcpdump, I see that all my network traffic is indeed flowing on the interface I set-up using the following scripts (ens192):
`reconfigure-listening-interface_stamus.sh
setup-selks-ids-interface.sh`

Still no results though, even if I trigger an alert with `wget http://testmyids.com`

Thanks for helping me out!

**Comment by pevma** [comment]
What is the output of the last 20 lines from /var/log/suricata/suricata.log ? Any errs there?

> -- 
> Regards,
> Peter Manev

**Comment by JoooostB** [comment]
The last lines all contain `[ERRCODE: SC_ERR_AFP_CREATE(190)]` 
Not sure what that means to be honest

**Comment by pevma** [comment]
It most likely means it is either not listening to the correct interface or  the interface is down.

> -- 
> Regards,
> Peter Manev

**Comment by pevma** [comment]
You can try finding the exact line/error for ens192 in suricata.log - i would suggest lets start from there.

**Comment by lukelee1987** [comment]
Hi, I am facing the same problem too. Seems no solutions.

**Comment by pevma** [comment]
@lukelee1987  - no you re not facing the same problem - please do not post randomly on any issues and be creating noise. This issue is with regards to sniffing interface.

**Comment by pevma** [comment]
Closing since no feedback since April.
