### ISSUE TITLE
evebox and kibana no events after selk4 update script

### ISSUE THREAD

**Issue by tmarvi** [StamusNetworks/SELKS#117]
Hi,
i am new to the SELK and using community edition. I have the below 2 interfaces in my debian9 selk installation.
i ran all the scripts and see ethtool output as required
Also i see eve.json logs when i tail it. But cant see anything on kibana and evebox. Need help

auto eno2
allow-hotplug eno2
iface eno2 inet manual
	#up link set $IFACE promisc on	
	pre-up ifconfig $IFACE up
	post-down ifconfig $IFACE down
	post-up /etc/network/if-up.d/idps-interface-tuneup_stamus
auto eno3
allow-hotplug eno3
iface eno3 inet manual
	#up link set $IFACE promisc on	
	pre-up ifconfig $IFACE up
	post-down ifconfig $IFACE down
	post-up /etc/network/if-up.d/idps-interface-tuneup_stamus

**Comment by pevma** [comment]
Hi,

Thanks for trying out SELKS!
Quick question - if you had a chance to set up the sniffing interface correctly - 
https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---Suricata-IDPS
?

Thank you

> -- 
> Regards,
> Peter Manev

**Comment by tmarvi** [comment]
i was able to fix the issue using the below resolution

https://github.com/StamusNetworks/SELKS/issues/112#issuecomment-382719164
