### ISSUE TITLE
No data in Kibana dashboard

### ISSUE THREAD

**Issue by opaji** [StamusNetworks/SELKS#134]
Hi,
I am unable to view past events in Kibana and and Evebox, I am only able to see events less than two weeks old. When I checked the StatsByDate files, all past events are still present. Can you please help on how to get these events back into Kibana?
I also noticed that ES indices stats only go back to two weeks earlier

Name | Count | Deleted
-- | -- | --
logstash-2018.10.17 | 17613 | 0
logstash-2018.10.29 | 696 | 0
logstash-dns-2018.10.31 | 963 | 0
logstash-2018.10.30 | 17628 | 0
logstash-2018.10.31 | 3418 | 0
logstash-flow-2018.10.31 | 992 | 0
logstash-fileinfo-2018.10.31 | 34 | 0
.kibana | 248 | 0
logstash-2018.10.18 | 324 | 0
logstash-tls-2018.10.31 | 123 | 0
logstash-http-2018.10.31 | 18

Please note that this is a temporary installation which I used to capture traffic for one week and removed from the network, now when I'm ready to analyse the events, I couldn't see events in Kibana anymore. I have connected back to the network but all I can see is current events and stats less than two weeks old.

Thank you.

**Comment by dgrgicevic** [comment]
check  your  current time/date

**Comment by opaji** [comment]
Yes I checked data/ time and it's intact

**Comment by pevma** [comment]
There is a log rotation/cron job that cleans up all logs older than 2 weeks  in `/etc/crontab`. If you want to keep data longer than that you need to adjust the duration in the script that is used by the cronjob.

**Comment by opaji** [comment]
Thanks Pevma, I forgot the log rotation thing.
I have used the files in StatsByData directory as logstash input file and I'm now able to get the events I need in Kibana.

**Comment by pevma** [comment]
Ok - glad it is solved.
Closing this then.
