### ISSUE TITLE
SELKS 5.0 ippair_alerts

### ISSUE THREAD

**Issue by freenetwork** [StamusNetworks/SELKS#147]
/viz/dashboard
https://pasteboard.co/HQ6PmEc.png

ippair_alerts not working. 
rules/es?query=ippair_alerts&from_date=1543805836673&hosts=selks&filter=* return 404 error/

**Comment by pevma** [comment]
Can you please confirm that with the latest Scirius version (3.0.1) - if you are not running it already I mean ?
``/opt/selks/Scripts/Setup/selks-upgrade_stamus.sh`` - should be enough for upgrade

**Comment by freenetwork** [comment]
I do /opt/selks/Scripts/Setup/selks-upgrade_stamus.sh

P.S.
There has bugs, rm /var/log*

**Comment by pevma** [comment]
Ok - What is the output of   - ``dpkg -l |grep scirius`` ?
