### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by Gatall** [StamusNetworks/SELKS#149]
After running /opt/selks/Scripts/Setup/selks-upgrade_stamus.sh
all scrips from /opt/selks/Scripts/ are deleted.

**Comment by pevma** [comment]
This should be affecting the SELKS5 only repo.
They are still available but should be system wide now - under /use/bin - can you please confirm ?


Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by Gatall** [comment]
Yes, confirm!  All in  usr/bin. Thanks!
