### ISSUE TITLE
Excluding events from the ALERTS dashboard was : Changing event type from alert to something else 

### ISSUE THREAD

**Issue by michelpy** [StamusNetworks/SELKS#15]
You made me realize that I did not know what I wanted to do ;-)
In fact, what I want to do is to modify the ALERTS dashboard so it excludes some of the events. Any tutorials you could recommend ?

Thanks,

**Comment by pevma** [comment]
A tutorial is a great idea ! We would need to look into that. 

In the meanwhile here is what you can do - in the ALERT dashboard (Kibana) - scroll down to the section - "Alert Details" - where you will have all alerts listed. 

Click on the alert (any) that you do not want to display. A detail window will open. Look for "alert.signature_id" or "alert.signature". In the "Action" column you have three choices  - click on the middle one "Add filter to NOT match this value". All widgets will be updated automatically to exclude that alert signature (any and all that match that signature id).

You can do that type of filtering with any JSON field in Kibana - and there are over 200 of them - so very flexible indeed.

**Comment by regit** [comment]
And don't forget to click on the save icon in the topbar so the dashboard is saved.

**Comment by michelpy** [comment]
> regit wrote :
> And don't forget to click on the save icon in the topbar so the dashboard is saved.

It got me the first time : have to click twice :P

> pevma wrote :+1: Click on the alert (any) that you do not want to display. A detail window will open. Look for "alert.signature_id" or "alert.signature". In the "Action" column you have three choices - click on the middle one "Add filter to NOT match this value". All widgets will be updated automatically to exclude that alert signature (any and all that match that signature id).

Thanks! solves 99% of my question. I see the results when I expand "filtering"
field mustNot field : alert.signature_id query :xxxxxxx

Now, how do I narrow the exclusion to a single host ?
exclude alert.signature_id xxxxxxx only if dest_ip = y.y.y.y or src_ip = y.y.y.y

Thanks much!

**Comment by pevma** [comment]
Example - select all signatures but exclude alert.signature_id 2013504 only if dest_ip = y.y.y.y or src_ip = y.y.y.y 
-> translates to (in the QUERY search space - top of the page - type in and hit enter):

alert.signature_id:* AND NOT (alert.signature_id:"2013504" AND (dest_ip:"x.x.x.x" OR src_ip:"y.y.y.y"))

On the opposite if you would like to select only signatures 2013504 that have either destination IP of x.x.x.x or source IP of y.y.y.y:

alert.signature_id:"2013504" AND (dest_ip:"x.x.x.x" OR src_ip:"y.y.y.y")

**Comment by michelpy** [comment]
Thanks! that helped a lot.

Still experimenting, but I found out the way that works the best for me so far is as follows:
- With the alert dashboard displayed, expand "filtering".
- There is a plus sign "Add a query filter" click on it.
- I my case, it's querystring mustNot, and the query is:
(alert.signature:"Text of the alert signature" AND ( src_ip:"192.168.y.y" OR dest_ip:"192.168.y.y" ) )
- Don't forget to SAVE.

I use alert.signature text instead of alert.signature_id number because it makes it a lot easier to manage when there are several ones. It is powerful.
Maybe the outer set of parenthesis could be omitted, me thinks.

I'm compiling a list of things to know for dummies :P

**Comment by pevma** [comment]
Thanks!
Looking forward to your compilation list.
