### ISSUE TITLE
Latests path updates broke libpolkit

### ISSUE THREAD

**Issue by Jeroen0494** [StamusNetworks/SELKS#150]
Hi Peter,

I see you moved all the setup script to /usr/bin/ and updated the desktop files, but you forgot to update the libpolkit paths. Please set the correct paths under /usr/share/polkit-1/actions/*. Change the line with the annotate key:

`<annotate key="org.freedesktop.policykit.exec.path">/opt/selks/Scripts/Setup/selks-first-time-setup_stamus.sh</annotate>`

Jeroen

**Comment by pevma** [comment]
Thanks !
Fixed by - https://github.com/StamusNetworks/SELKS/commit/023403a294fe02682ccd881110b4f97341fce32d
