### ISSUE TITLE
No logstash data on Kibana

### ISSUE THREAD

**Issue by lukelee1987** [StamusNetworks/SELKS#153]
Hi all, I have this issue with querying the data on Kibana. Besides that I was running a check and found the following: 

systemctl status of : 
 - suricata (active)
 - elasticsearch (Inactive) 
 - logstash (active)
 - kibana (Inactive) 

I just wonder all these must run as systemctl services? or can I just run under services? All my portal (Elasticsearch, Kibana, and Scirius) are displaying....

**Comment by pevma** [comment]
> On 2 Jan 2019, at 04:01, Sky Luke <notifications@github.com> wrote:
> 
> Hi all, I have this issue with querying the data on Kibana. Besides that I was running a check and found the following:
> 
> systemctl status of :
> 
> suricata (active)
> elasticsearch (Inactive)
> logstash (active)
> kibana (Inactive)
> I just wonder all these must run as systemctl services? or can I just run under services? All my portal (Elasticsearch, Kibana, and Scirius) are displaying....
> 


Is this a SELKS installation ?

**Comment by lukelee1987** [comment]
In a way it is. But I am installing the different component differently. Start with Scirius, Suricata, Kibana and Elasticsearch respectively. Then logstash and also metricbeat on the server. Now I have difficulties linking them.

**Comment by pevma** [comment]
We are currently handling only SELKS installations , not custom installs as the configuration can substantially differ depending on the customization which makes it difficult to troubleshoot remotely. (Especially when you install unsupported logstash and elasticsearch versions as it was in your case )

Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by lukelee1987** [comment]
May I know where can I get support for custom SELKS setting up?

**Comment by pevma** [comment]
Custom SELKS is not the issue.
In your case you are running  CentOS. (SELKS is Debian bases including the packaging we do for Scirius, Suricata etc) 

I have previously shared some ideas of how to achieve that in CentOS as well. 

> -- 
> Regards,
> Peter Manev

**Comment by lukelee1987** [comment]
Hi Pevma, do you mind to share it here again for the benefits of all? Thanks

**Comment by pevma** [comment]
It has already been shared on github.
SELKS is open source so all build steps and source is on github - 
https://github.com/StamusNetworks/SELKS/tree/SELKS5
 
The general process you should follow is -
https://github.com/StamusNetworks/SELKS/blob/SELKS5/build-debian-live.sh
Then 
https://github.com/StamusNetworks/SELKS/blob/SELKS5/staging/config/hooks/live/chroot-inside-Debian-Live.hook.chroot
This  above is Debian specific - you should adjust it for CentOS - aka all pkg names and config files location may differ and be CentOS specific.

**Comment by lukelee1987** [comment]
Do you have guides for installing on CentOS?

**Comment by pevma** [comment]
We currently dont. We are happy to accept contributions thought ! :)

**Comment by pevma** [comment]
Seems the error is about your start command - the syntax is wrong - based on the message.

Closing this issue as it is not SELKS related. 
Please do not open issues for SELKS about CentOS installations as they (the SELKS one and your custom CentOS install) are most probably very different in terms of configuration.
