### ISSUE TITLE
classification.config edit

### ISSUE THREAD

**Issue by bbatmandakh** [StamusNetworks/SELKS#154]
Hi, 

I try to edit "/etc/suricata/rules/classification.config" file. But after following command "classification.config" file is reset back.

https://selks/suricata/ -> Ruleset Actions -> Actions(Update/Build/Push) -> Apply 

How to edit/add classtype in SELKS?

**Comment by pevma** [comment]
You can point to a different classification config inside selks5 yaml and that way set up your own.
