### ISSUE TITLE
SELKS 5RC1 - Kibana not working after update using script.

### ISSUE THREAD

**Issue by thecube13** [StamusNetworks/SELKS#156]
After update via  selks-upgrade_stamus.sh Kibana not working. 

Error in browser: 
Kibana did not load properly. Check the server output for more information.

In browser console:
Failed to load resource: vendors.style.dll.css:1 the server responded with a status of 404 (Not Found).
Failed to load resource: vendors.bundle.dll.js:1 the server responded with a status of 404 (Not Found).
Failed to load resource: vendors.style.dll.css:1 the server responded with a status of 404 (Not Found).

**Comment by pevma** [comment]
You should try this - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#elk-stack-660-nginx-config-change-needed 
Let us know how it goes!

**Comment by thecube13** [comment]
> You should try this - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#elk-stack-660-nginx-config-change-needed
> Let us know how it goes!

Thank you, everything works fine after a change in the nginx config.

**Comment by pevma** [comment]
Thank you for confirming !

**Comment by FredJ21** [comment]
Hi, 
I have a same issue with a fresh install of SELKS 5RC1 and  after upgrading package.
I also confirm that everything works correctly with new nginx configuration 
Thank !
