### ISSUE TITLE
Kibana doesn't launch properly from dashboard link

### ISSUE THREAD

**Issue by Cptspal** [StamusNetworks/SELKS#157]
Kibana is available by launching directly http://selksserver:5601 but not from the dashboard link in scirius.

I needed to edit  /usr/share/python/scirius/lib/python2.7/site-packages/scirius/urls.py
and add the line :
`url(r'^(?P<path>dlls.*)$', KibanaProxyView.as_view()),`
to fix the problem

cdt

**Comment by pevma** [comment]
Just FYI - we have a fix here  as well - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#elk-stack-6-6-0-nginx-config-change-needed
The Scirius manual fix will most likely be overwritten by the next package install.

**Comment by Cptspal** [comment]
Oh ok, sorry, I miss that. Good to know, thx !
