### ISSUE TITLE
Disk filling quickly

### ISSUE THREAD

**Issue by showipintbri** [StamusNetworks/SELKS#158]
I have SELKS 5 RC1 up and running. 

I'm not sure how to scale it properly.

I have a VM with 16 GB memory, 2 vCPU and 120 GB disk space.

In about an hour I fill up the hard drive.
![capture1](https://user-images.githubusercontent.com/40892800/52881196-f7ad5080-3131-11e9-8c9c-49ff0d70d7c4.PNG)
![capture2](https://user-images.githubusercontent.com/40892800/52881200-fc720480-3131-11e9-9c41-d097bd477bac.PNG)

When the hard drive fills, the system is unusable.

Are there any configurations or settings I can change to stop the hard disk from filling so rapidly? Are there any rotation policies?

**Comment by pevma** [comment]
Is it probably the /data/nsm or /data/moloch/raw ? 

If that is the case it is the packet capture - so if it fills up in 1hr you may need to budget bigger disk space.(or disable it by tuning selks-first-time-setup script executable  system wide )

Also if that is the case it may be better to mount those folders to a diff drive.

> -- 
> Regards,
> Peter Manev

**Comment by showipintbri** [comment]
I checked, it looks like, it's /data/moloch/raw/

![capture3](https://user-images.githubusercontent.com/40892800/52884340-aefa9500-313b-11e9-9d80-106b98a9eea9.PNG)

When I ran the first-time setup script, I used "FPC_RETAIN" (option 2) and it asks about maximum file size (I used 1GB) and maximum rotation (I used "0").

I'm struggling to understand the difference between "FPC" and "FPC_RETAIN".

**Comment by pevma** [comment]
Not sure if you have seen it before but the diff is explained here - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#full-packet-capture-fpc

Maybe instead of the 0 you need to specify 30 (30 min) or so retention - or disable it via the setup script as the disk allows only for 1 hr or so capacity.

Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by showipintbri** [comment]
Awesome, exactly the documentation I needed. Thanks. I'm going to try a few things tonight.

**Comment by showipintbri** [comment]
Old Issue.

Resolved Now.
