### ISSUE TITLE
live-build not functional

### ISSUE THREAD

**Issue by mrdraper** [StamusNetworks/SELKS#160]
Hi,

We use a custom SELKS setup that we would like to make into a custom installable ISO. We want to use the live-build scripts here to achieve this. Two questions:

1. Will it be updated to SELKS5.0 w/ Moloch? Last update is 2 years ago.
2. When using the live-build script we can build an ISO, but it seems the `staging/config/hooks/chroot-inside-Debian-Live.chroot` post-installation script is not run when installing from the ISO. When installing from the ISO we get a Debian system without any of the tools installed. I could not see any errors in the output from the build-debian-live.sh script. Is there anything i'm missing?

Thanks in advance!

**Comment by mrdraper** [comment]
Sorry, just found https://github.com/StamusNetworks/SELKS/tree/SELKS5. Thanks for this!

**Comment by pevma** [comment]
Yes that one works :) 
No problem - thank you for trying !
