### ISSUE TITLE
Suricata.log - Error SC_WARN_FLOWBIT

### ISSUE THREAD

**Issue by Mauro2k** [StamusNetworks/SELKS#171]
I would like to know what is this error that appears in suricata.log since I can not find other cases:

> [16323] 27/3/2019 -- 10:16:04 - (detect-flowbits.c:477) <Warning> (DetectFlowbit
> sAnalyze) -- [ERRCODE: SC_WARN_FLOWBIT(306)] - flowbit 'ET.Netwire.HB.1' is chec
> ked but not set. Checked in 2018282 and 0 other sigs

**Comment by pevma** [comment]
It just means that the flowbit is set but not checked. You could find out more here -
https://suricata.readthedocs.io/en/latest/rules/flow-keywords.html

Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by Mauro2k** [comment]
Hi, thanks, 
Today when I went to work on the error, I find that it is gone.
I'm going to close this ticket and open a new one for other errors that I do not understand.
