### ISSUE TITLE
5.0RC1 | Web Interface: Administration: Updating sources problem.

### ISSUE THREAD

**Issue by xxaxxelxx** [StamusNetworks/SELKS#173]
No effect after successfully updated sources. Needs
 # /bin/su -s /bin/bash -c 'cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py updatesuricata && deactivate' www-data
to show reaction.

**Comment by pevma** [comment]
I am sorry - i do not understand what the issue is.

**Comment by xxaxxelxx** [comment]
Good morning! 
Using the web interface:
Created my own source. Added the source via Administration. 
The new rules show no effect in alerts. I've to run the updatesuricata from the console script to take effect.

**Comment by pevma** [comment]
You need to run ruleset update from the Suricata tab from the web GUI.

**Comment by xxaxxelxx** [comment]
Did. No reaction.

**Comment by xxaxxelxx** [comment]
More Details:
It works via 'Administration' -> 'Suricata' -> 'Ruleset actions' -> all options selected.
It works NOT via 'Adminsitration' -> 'Rulesets' -> 'Update ruleset'. (Seems this does not do 'build' and 'push'.)

**Comment by pevma** [comment]
Yep - as expected as in `Update ruleset` it only updates the ruleset but does not reload it for the sensor.
