### ISSUE TITLE
Kibana reset error

### ISSUE THREAD

**Issue by MartinsZB** [StamusNetworks/SELKS#175]
Kibana reset give an error because it is looking for /opt/kibana6-dashboards, but the real path for dashboards now is /opt/selks/kibana6-dashboards

**Comment by pevma** [comment]
Hi,

I think you need to adjust the variable in the ``/etc/scirius/local_settings.py``
```
KIBANA6_DASHBOARDS_PATH = "/opt/selks/kibana6-dashboards/"
```
Like explained here - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#kibana-dashboards. 
Then reset  the dashboards.

Thanks

**Comment by MartinsZB** [comment]
Thanks. Yes, somehow missed that wiki part. Sorry, my bad.

**Comment by pevma** [comment]
No problem - glad it works.
