### ISSUE TITLE
Initial NIC setup page

### ISSUE THREAD

**Issue by youngd24** [StamusNetworks/SELKS#179]
One of the bits in the initial NIC setup page is incorrect.

post-up /etc/network/if-up.d/idps-interface-tuneup_stamus

should be

post-up /etc/network/if-up.d/selks-idps-interface-tuneup_stamus

**Comment by youngd24** [comment]
Should be correct now.

**Comment by pevma** [comment]
Thank you for the report and fixing it !

**Comment by youngd24** [comment]
Quite welcome. Rockin' IDS dist, I'm really digging it. Keep up the good work.
