### ISSUE TITLE
Kibana server is not ready yet after upgrade

### ISSUE THREAD

**Issue by michal25** [StamusNetworks/SELKS#182]
I have the same problem as 
https://github.com/StamusNetworks/SELKS/issues/181

output of selks-health-check_stamus is
root@SELKS2:~# selks-health-check_stamus 
● suricata.service - LSB: Next Generation IDS/IPS
   Loaded: loaded (/etc/init.d/suricata; generated; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 20:13:06 CEST; 59s ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/suricata.service
           └─20060 /usr/bin/suricata -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid --af-packet -D -v --user=logstash

May 08 20:13:06 SELKS2 systemd[1]: Starting LSB: Next Generation IDS/IPS...
May 08 20:13:06 SELKS2 suricata[20046]: Starting suricata in IDS (af-packet) mode... done.
May 08 20:13:06 SELKS2 systemd[1]: Started LSB: Next Generation IDS/IPS.
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 20:09:38 CEST; 4min 28s ago
     Docs: http://www.elastic.co
 Main PID: 19295 (java)
   CGroup: /system.slice/elasticsearch.service
           ├─19295 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddres…et
           └─19419 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

May 08 20:09:38 SELKS2 systemd[1]: Started Elasticsearch.
May 08 20:09:38 SELKS2 elasticsearch[19295]: warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 16:22:06 CEST; 1 day 3h ago
 Main PID: 1633 (java)
   CGroup: /system.slice/logstash.service
           └─1633 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless…sh

May 08 20:09:39 SELKS2 logstash[1633]: [2019-05-08T20:09:39,695][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …8}
May 08 20:09:39 SELKS2 logstash[1633]: [2019-05-08T20:09:39,681][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …8}
May 08 20:09:39 SELKS2 logstash[1633]: [2019-05-08T20:09:39,680][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …8}
May 08 20:09:44 SELKS2 logstash[1633]: [2019-05-08T20:09:44,317][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but…"}
May 08 20:09:47 SELKS2 logstash[1633]: [2019-05-08T20:09:47,706][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …6}
May 08 20:09:47 SELKS2 logstash[1633]: [2019-05-08T20:09:47,707][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …6}
May 08 20:09:47 SELKS2 logstash[1633]: [2019-05-08T20:09:47,731][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …6}
May 08 20:09:47 SELKS2 logstash[1633]: [2019-05-08T20:09:47,707][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no …6}
May 08 20:09:49 SELKS2 logstash[1633]: [2019-05-08T20:09:49,368][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but…"}
May 08 20:09:54 SELKS2 logstash[1633]: [2019-05-08T20:09:54,380][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http:….0.1:9200/"}
Hint: Some lines were ellipsized, use -l to show in full.
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 20:09:38 CEST; 4min 28s ago
 Main PID: 19303 (node)
   CGroup: /system.slice/kibana.service
           └─19303 /usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

May 08 20:13:39 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:39Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:42 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:42Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:45 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:45Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:48 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:48Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:51 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:51Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:54 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:54Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:13:57 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:13:57Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:14:00 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:14:00Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:14:03 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:14:03Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
May 08 20:14:06 SELKS2 kibana[19303]: {"type":"log","@timestamp":"2019-05-08T18:14:06Z","tags":["error","task_manager"],"pid":19303,"message":"Failed to poll for …"}
Hint: Some lines were ellipsized, use -l to show in full.
● evebox.service - EveBox Server
   Loaded: loaded (/lib/systemd/system/evebox.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 16:17:29 CEST; 1 day 3h ago
 Main PID: 604 (evebox)
   CGroup: /system.slice/evebox.service
           └─604 /usr/bin/evebox server

May 07 16:17:35 SELKS2 evebox[604]: 2019-05-07 16:17:35 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:39 SELKS2 evebox[604]: 2019-05-07 16:17:39 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:42 SELKS2 evebox[604]: 2019-05-07 16:17:42 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:45 SELKS2 evebox[604]: 2019-05-07 16:17:45 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:353) <Info> -- Connected to Elastic Search (version: 6.7.2)
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (elasticsearch.go:199) <Info> -- Found templates [logstash]
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (elasticsearch.go:238) <Info> -- Found Elastic Search keyword suffix to be: keyword
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:131) <Info> -- Session reaper started
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:165) <Info> -- Authentication disabled.
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
Hint: Some lines were ellipsized, use -l to show in full.
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 20:10:15 CEST; 3min 50s ago
 Main PID: 19610 (sh)
   CGroup: /system.slice/molochviewer-selks.service
           ├─19610 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1
           └─19611 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini

May 08 20:10:15 SELKS2 systemd[1]: Started Moloch Viewer.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 20:10:15 CEST; 3min 50s ago
 Main PID: 19612 (sh)
   CGroup: /system.slice/molochpcapread-selks.service
           ├─19612 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1
           └─19613 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/

May 08 20:10:15 SELKS2 systemd[1]: Started Moloch Pcap Read.
scirius                          RUNNING   pid 19371, uptime 0:04:28
ii  elasticsearch                   6.7.2                          all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  elasticsearch-curator           5.7.6                          amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                          1:0.10.2                       amd64        no description given
ii  kibana                          6.7.2                          amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus        2019030501                     amd64        Kibana 6 dashboard templates.
ii  logstash                        1:6.7.2-1                      all          An extensible logging pipeline
ii  moloch                          1.8.0-1                        amd64        Moloch Full Packet System
ii  scirius                         3.2.0-1                        amd64        Django application to manage Suricata ruleset
ii  suricata                        2019040702-0stamus0            amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  7.8G     0  7.8G   0% /dev
tmpfs          tmpfs     1.6G   69M  1.5G   5% /run
/dev/md0       ext3      887G   27G  816G   4% /
tmpfs          tmpfs     7.8G     0  7.8G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     7.8G     0  7.8G   0% /sys/fs/cgroup
tmpfs          tmpfs     1.6G     0  1.6G   0% /run/user/1001

and
root@SELKS2:~# cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset && deactivate
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 38, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 584, in kibana_reset
    raise Exception('Please make sure Kibana dashboards are installed at %s' % self._get_dashboard_dir())
Exception: Please make sure Kibana dashboards are installed at /opt/kibana6-dashboards/

**Comment by markeur** [comment]
Hello @michal25, Before my issue I have yours it's a little bit different : 
1 . Be sure that you have : 
*KIBANA6_DASHBOARDS_PATH = "/opt/selks/kibana6-dashboards/"* in 
by default you have only : 
*KIBANA_DASHBOARDS_PATH = "/opt/selks/kibana6-dashboards/"* without the 6 at end of KIBANA :  *KIBANA**6**_DASHBOARDS_PATH*

2. Update you nginx config file

3. Use *su* command to become root and use cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset && deactivate

**Comment by michal25** [comment]
Apologize, the new title is correct.

My last updated binary via the
selks-upgrade_stamus

has been the
elasticsearch-curator

and here started my errors

root@SELKS2:~# selks-health-check_stamus 
● suricata.service - LSB: Next Generation IDS/IPS
   Loaded: loaded (/etc/init.d/suricata; generated; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 11:51:24 CEST; 54min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17611 ExecStop=/etc/init.d/suricata stop (code=exited, status=0/SUCCESS)
  Process: 17625 ExecStart=/etc/init.d/suricata start (code=exited, status=0/SUCCESS)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/suricata.service
           └─17633 /usr/bin/suricata -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid --af-packet -D -v --user=logstash

May 09 11:51:24 SELKS2 systemd[1]: Stopped LSB: Next Generation IDS/IPS.
May 09 11:51:24 SELKS2 systemd[1]: Starting LSB: Next Generation IDS/IPS...
May 09 11:51:24 SELKS2 suricata[17625]: Starting suricata in IDS (af-packet) mode... done.
May 09 11:51:24 SELKS2 systemd[1]: Started LSB: Next Generation IDS/IPS.
● elasticsearch.service - Elasticsearch                                                                                                                              
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 11:51:20 CEST; 54min ago
     Docs: http://www.elastic.co
 Main PID: 17459 (java)
    Tasks: 77 (limit: 4915)
   CGroup: /system.slice/elasticsearch.service
           ├─17459 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddres…et
           └─17583 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

May 09 11:51:20 SELKS2 systemd[1]: Started Elasticsearch.
May 09 11:51:20 SELKS2 elasticsearch[17459]: warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 12:46:09 CEST; 8s ago
 Main PID: 19419 (java)
    Tasks: 17 (limit: 4915)
   CGroup: /system.slice/logstash.service
           └─19419 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headles…sh

May 09 12:46:09 SELKS2 systemd[1]: Started logstash.
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 11:51:20 CEST; 54min ago
 Main PID: 17466 (node)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/kibana.service
           └─17466 /usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

May 09 12:45:51 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:45:51Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:45:54 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:45:54Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:45:57 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:45:57Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:00 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:00Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:03 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:03Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:06 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:06Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:09 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:09Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:12 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:12Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:15 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:15Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
May 09 12:46:18 SELKS2 kibana[17466]: {"type":"log","@timestamp":"2019-05-09T10:46:18Z","tags":["error","task_manager"],"pid":17466,"message":"Failed to poll for …"}
Hint: Some lines were ellipsized, use -l to show in full.
● evebox.service - EveBox Server
   Loaded: loaded (/lib/systemd/system/evebox.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 16:17:29 CEST; 1 day 20h ago
 Main PID: 604 (evebox)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/evebox.service
           └─604 /usr/bin/evebox server

May 07 16:17:35 SELKS2 evebox[604]: 2019-05-07 16:17:35 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:39 SELKS2 evebox[604]: 2019-05-07 16:17:39 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:42 SELKS2 evebox[604]: 2019-05-07 16:17:42 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:45 SELKS2 evebox[604]: 2019-05-07 16:17:45 (server.go:350) <Error> -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:353) <Info> -- Connected to Elastic Search (version: 6.7.2)
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (elasticsearch.go:199) <Info> -- Found templates [logstash]
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (elasticsearch.go:238) <Info> -- Found Elastic Search keyword suffix to be: keyword
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:131) <Info> -- Session reaper started
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:165) <Info> -- Authentication disabled.
May 07 16:17:48 SELKS2 evebox[604]: 2019-05-07 16:17:48 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
Hint: Some lines were ellipsized, use -l to show in full.
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 11:52:53 CEST; 53min ago
 Main PID: 17793 (sh)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/molochviewer-selks.service
           ├─17793 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1
           └─17794 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini

May 09 11:52:53 SELKS2 systemd[1]: Started Moloch Viewer.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-09 11:52:53 CEST; 53min ago
 Main PID: 17787 (sh)
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/molochpcapread-selks.service
           ├─17787 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1
           └─17788 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/

May 09 11:52:53 SELKS2 systemd[1]: Started Moloch Pcap Read.
scirius                          RUNNING   pid 17535, uptime 0:54:58
ii  elasticsearch                   6.7.2                          all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  elasticsearch-curator           5.7.6                          amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                          1:0.10.2                       amd64        no description given
ii  kibana                          6.7.2                          amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus        2019030501                     amd64        Kibana 6 dashboard templates.
ii  logstash                        1:6.7.2-1                      all          An extensible logging pipeline
ii  moloch                          1.8.0-1                        amd64        Moloch Full Packet System
ii  scirius                         3.2.0-1                        amd64        Django application to manage Suricata ruleset
ii  suricata                        2019040702-0stamus0            amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  7.8G     0  7.8G   0% /dev
tmpfs          tmpfs     1.6G   97M  1.5G   7% /run
/dev/md0       ext3      887G   32G  810G   4% /
tmpfs          tmpfs     7.8G     0  7.8G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     7.8G     0  7.8G   0% /sys/fs/cgroup
tmpfs          tmpfs     1.6G     0  1.6G   0% /run/user/1001

Maybe this line is relevant?
May 09 11:51:20 SELKS2 systemd[1]: Started Elasticsearch.
May 09 11:51:20 SELKS2 elasticsearch[17459]: warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME

**Comment by pevma** [comment]
@michal25  - what is the issue  - Can not open the Kibana page , right?

**Comment by michal25** [comment]
Issue is
Kibana server is not ready yet  - after upgrade

My last updated binary via the
selks-upgrade_stamus

has been the
elasticsearch-curator

![Screenshot_20190509_151759](https://user-images.githubusercontent.com/5064337/57456466-df9b2800-726d-11e9-801e-b520c2830087.png)

**Comment by michal25** [comment]
My latest version of elasticsearch-curator is amd64 5.7.6

root@SELKS2:~# dpkg -s elasticsearch-curator
Package: elasticsearch-curator
Status: install ok installed
Priority: extra
Section: tools
Installed-Size: 63713
Maintainer: 'Elastic Developers <info@elastic.co>'
Architecture: amd64
Version: 5.7.6
Provides: elasticsearch-curator
Conflicts: python-elasticsearch-curator, python3-elasticsearch-curator
Description: Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
License: Apache-2.0
Vendor: Elastic
Homepage: http://example.com/no-uri-given

**Comment by michal25** [comment]
My previous version of elasticsearch-curator has been Version: 5.7.5

Version 5.7.5 work OK on another device.

**Comment by pevma** [comment]
I just did an upgrade and rechecked , i got the following -
```
ii  elasticsearch                        6.7.2                             all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  elasticsearch-curator                5.7.6                             amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                               1:0.10.2                          amd64        no description given
ii  kibana                               6.7.2                             amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus             2019030501                        amd64        Kibana 6 dashboard templates.
ii  logstash                             1:6.7.2-1                         all          An extensible logging pipeline
ii  moloch                               1.8.0-1                           amd64        Moloch Full Packet System
ii  scirius                              3.2.0-1                           amd64        Django application to manage Suricata ruleset
ii  suricata                             2019040702-0stamus0               amd64        Suricata open source multi-thread IDS/IPS/NSM system.

```
I could not reproduce the Kibana error.

Some points/questions.
Do you have the exact nginx config as in here - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#elk-stack-6-6-0-nginx-config-change-needed  ?

Maybe you need to reboot the whole system?

I also see some Elasticsearch errors from your report - 
```
 2019-05-07 16:17:42 (server.go:350) -- Failed to ping Elastic Search, delaying startup: : Get http://localho…tion refused
```

Is there anything in `/var/log/elasticsearch/elasticsearch.log` ?

What is the output of `curl -X GET "localhost:9200/_cluster/health" |jq .` ?

**Comment by michal25** [comment]
root@SELKS2:~# curl -X GET "localhost:9200/_cluster/health" |jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   406  100   406    0     0   259k      0 --:--:-- --:--:-- --:--:--  396k
{
  "cluster_name": "elasticsearch",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 181,
  "active_shards": 181,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 5,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 97.31182795698925
}

elasticsearch logs attached
[Elasticsearch.tar.gz](https://github.com/StamusNetworks/SELKS/files/3163841/Elasticsearch.tar.gz)

I have exact nginx conf as
 https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1#elk-stack-6-6-0-nginx-config-change-needed

I tried to reboot the device - no effect. 
But, before the upgrade - the filesystem has been full (moloch logs) and FPC configuration is 2
2) FPC_Retain - Full Packet Capture with having Moloch's pcap retention/rotation. Keeps the pcaps as long as there is space available.

with 
max file size 1GB
and time rotation 600 min

and FPC 2 works strange - the device claims disk full after some 7 days, HD is SDD 1TB.

[elasticsearch_deprecation.log](https://github.com/StamusNetworks/SELKS/files/3163864/elasticsearch_deprecation.log)
[elasticsearch.log](https://github.com/StamusNetworks/SELKS/files/3163865/elasticsearch.log)

**Comment by markeur** [comment]
@michal25 I don't know if your probleme is exactly the same as mine but I just succeed to redeploy kibana
you can see what I did on #181 my two last post the second all command are executed as root.

Hope that can help you.

**Comment by michal25** [comment]
Great !
Thank you very much for this.
I discovered mismatch in the scirius config file on my failing selks device, the KIBANA6-  parameter has been missing. I don't know exactly why and from which time. But the selks_first_time  script fails with copy kibana dashboard files.
It look to same mismatch with some part of selks-upgrade script.
I will try your workaround this weekend.

Best regards
Michal

10. května 2019 8:37:59 SELČ, markeur <notifications@github.com> napsal:
>@michal25 I don't know if your probleme is exactly the same as mine but
>I just succeed to redeploy kibana
>you can see what I did on #181 my two last post the second all command
>are executed as root.
>
>Hope that can help you.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/StamusNetworks/SELKS/issues/182#issuecomment-491174680

-- 
Odesláno z mého telefonu s Androidem pomocí pošty K-9 Mail. Omluvte prosím moji stručnost.

**Comment by michal25** [comment]
Solved, workaround works. Thanks to https://github.com/markeur and https://github.com/pevma

all commands as root

After did that
curl -XDELETE http://localhost:9200/.kibana_1
curl -XDELETE http://localhost:9200/.kibana_2
curl -XDELETE http://localhost:9200/.kibana
curl -XDELETE http://localhost:9200/.kibana*

Kibana is back but without configuration

ok i just reload/reset dashboards with : 
cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset && deactivate

now

systemctl restart kibana

go to kibana and recreate indexes (or make default index only).

**Comment by pevma** [comment]
Thank you for the detailed steps  explaining the solution of the problem.
