### ISSUE TITLE
Kibana anonymous login

### ISSUE THREAD

**Issue by Famku** [StamusNetworks/SELKS#185]
Hi,

how  to enable anonymous login to Kibana?

Wanted to set the dashboards on my signage display.

thanks

**Comment by pevma** [comment]
I would update the package so it has the latest additions from git then you could enable it form yaml.

**Comment by Famku** [comment]
Thanks for your answer.

Can you explain how to do this via yalm?

**Comment by pevma** [comment]
Sorry -  i misread the question!
Currently authentication in SELKS is handled in Scirius.

**Comment by Famku** [comment]
so, it is not possible to open a Kibana Dashboard without login?

**Comment by Famku** [comment]
I use the Splunk app now, looks good
