### ISSUE TITLE
IPS AF_Packet mode and decoder invalid

### ISSUE THREAD

**Issue by VioletQbik** [StamusNetworks/SELKS#187]
When using SELKS with Suricata in IPS AF_Packet mode with "threads: 1" in interfaces configs the latency is quite big (+ from 30 to 100+ in ICMP). If I use "threads: >1" (both interfaces) as described https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---Suricata-IPS, I got "decoder invalid" parameter is growing very fast. Suricata build 2019040702-0stamus0, kernel: Linux SELKS 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux.

**Comment by pevma** [comment]
Can you please  share your:   

`/var/log/suricata/suricata.log`
`/var/log/suricata/stats.log`

Thank you

**Comment by VioletQbik** [comment]
Seems that using "defrag:no" parameter in config file solves thuis problem. Thank you.
