### ISSUE TITLE
Rules Reload doesn't work properly

### ISSUE THREAD

**Issue by VioletQbik** [StamusNetworks/SELKS#188]
I need to drop icmp traffic from 8.8.8.8 (for example). I have created my own rule file (this rules file name is added to the main config file) with 1 rule: drop icmp 8.8.8.8 any -> $HOME_NET any (msg:"Our Blocking Rule"; priority:1; sid:777;). When I use "kill -USR2 $(pidof suricata)", in suricata.log everything is ok. But ICMP with 8.8.8.8 seems not to be dropped. Why? Suricata build 2019040702-0stamus0, kernel: Linux SELKS 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux.

**Comment by pevma** [comment]
Could you try a diff rule - just for test - try `drop ip 8.8.8.8 any....` to see if a diff result ? Also look in the logs Kibana SN Alerts or Hunt in Scirius or Evebox - for that `sid`number `sid:777` to see if it will come up?

**Comment by VioletQbik** [comment]
When using "drop ip 8.8.8.8 any...." the situation is the same. This sid doesn't appear in logs (using Scirius and Evebox).

**Comment by pevma** [comment]
Anything different you are doing about your interfaces set up - bridges etc...?

> -- 
> Regards,
> Peter Manev

**Comment by VioletQbik** [comment]
Interfaces config:

%YAML 1.1
---
# AUTOGENERATED by Stamus SELKS set up script
# Linux high speed capture support
af-packet:
  # Put default values here. These will be used for an interface that is not
  # in the list above.
  - interface: default
    #threads: auto
    #use-mmap: no
    #rollover: yes
    #tpacket-v3: yes
  - interface: eno2
    threads: 8
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    #mmap-locked: yes
    tpacket-v3: no
    ring-size: 2048
    block-size: 32768
    #block-timeout: 10
    #use-emergency-flush: yes
    #checksum-checks: kernel
    #bpf-filter: port 80 or udp
    copy-mode: ips
    copy-iface: enp179s0f0
  - interface: enp179s0f0
    threads: 8
    cluster-id: 100
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    #mmap-locked: yes
    tpacket-v3: no
    ring-size: 2048
    block-size: 32768
    #block-timeout: 10
    #use-emergency-flush: yes
    #checksum-checks: kernel
    #bpf-filter: port 80 or udp
    copy-mode: ips
    copy-iface: eno2

**Comment by pevma** [comment]
Can you please remove the “block-size” settings and set defrag:no and try to see if any difference ?

> -- 
> Regards,
> Peter Manev

**Comment by VioletQbik** [comment]
I have removed “block-size” parameter and set defrag:no, and I don't see any difference.

**Comment by pevma** [comment]
Could you please post the resulting yaml ?

**Comment by pevma** [comment]
Can please you also check the raw logs for the `sid` itself - aka 
```
grep sid_number_here /var/log/suricata/eve.json
```

**Comment by VioletQbik** [comment]
[suricata.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3240603/suricata.yaml.txt)
[selks5-addin.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3240604/selks5-addin.yaml.txt)
[selks5-interfaces-config.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3240605/selks5-interfaces-config.yaml.txt)

I have noticed, that the new rule works, but after 10 or more minutes after the reloading. In eve.json (and Evebox  etc)  the sid appears the same time.

**Comment by pevma** [comment]
Ok - so it works - but there is a delay in when it appears in Scirius or Evebox, correct?
Does it appear right away in `eve.json`

**Comment by VioletQbik** [comment]
Yes, it seems tahr the delay is same in eve.json, Scirius and real rule working.

**Comment by pevma** [comment]
Ok - so the set up is working  it just appears in `eve.json` with a delay - > hence everywhere else.
what is the delay?

**Comment by VioletQbik** [comment]
No, the new drop rule starts to work with a delay (10 or more minutes). It comes to logs with se same delay.

**Comment by pevma** [comment]
Ok - sorry - just so i understand better  - it appears in `eve.json` with a 10 min delay ?

**Comment by VioletQbik** [comment]
Yes, 10 minutes minimum, sometimes is takes about an hour.

**Comment by pevma** [comment]
That is strange - can you please describe a bit more your set up? Traffic speed - is it constant is it in bursts ?

**Comment by VioletQbik** [comment]
When I decreased flow-timeout values in suricata.yaml:

flow-timeouts:

  default:
    new: 6
    established: 60
    closed: 0
    bypassed: 20
    emergency-new: 2
    emergency-established: 20
    emergency-closed: 0
    emergency-bypassed: 10
  tcp:
    new: 6
    established: 60
    closed: 6
    bypassed: 10
    emergency-new: 2
    emergency-established: 10
    emergency-closed: 2
    emergency-bypassed: 5
  udp:
    new: 3
    established: 30
    bypassed: 10
    emergency-new: 2
    emergency-established: 10
    emergency-bypassed: 5
  icmp:
    new: 3
    established: 30
    bypassed: 10
    emergency-new: 2
    emergency-established: 10
    emergency-bypassed: 5

Time lag was reduced to about 1-2 minutes. I think the problem was in high established flow-timeout value or something like this.

**Comment by pevma** [comment]
Thank you for sharing your feedback -yest that could be a reason - depending on the type of traffic indeed !
