### ISSUE TITLE
Can't ssh to the Selks host

### ISSUE THREAD

**Issue by michelpy** [StamusNetworks/SELKS#19]
Hi all,

I have trouble ssh to the Selks host.

- Linux command-line ssh from another linux box : nothing happens (ctrl-c goes back to the prompt).

- Putty from a Windows PC : the following error message "Couldn't agree a client-to-server cipher (available: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cgm@openssh.com,  aes256-cgm@openssh.com, chacha20-poly1305@openssh.com)

- IOS command-line from a Cisco router :
c1841-michel#ssh 192.168.222.3
[Connection to 192.168.222.3 aborted: error status 0]
Jun 17 13:49:32.583 PDT: %SSH-3-NO_MATCH: No matching cipher found: client aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc ser
ver aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com

Followed instructions from here :
http://steronius.blogspot.com/2014/10/ssh-no-matching-cipher-found.html
Solved most of the issue, but:

- Still can't ssh as root (minor)
- Does not work with putty (does work from Cisco and with Bitwise windows ssh client).

**Comment by pevma** [comment]
This is strange. Do you still have a problem using a Linux ssh client? (or that was fixed by following the instructions on  the before mentioned blog post)

**Comment by michelpy** [comment]
I believe that a fresh install from the SELKS 2.0 distro does not allow ssh at all from any platform without the fix mentioned in the blog post.

Now, this info is a week old; I don't know if I were to install a fresh SELKS today and aptitude ran, it would do the same. Next SELKS host I install, I will try to ssh to it without the fix and let you know.

**Comment by pevma** [comment]
I just tried on SELKS 2.0 - ssh selks-user@ip.ip.ip.ip - works fine - no issues.

**Comment by michelpy** [comment]
I must have missed something in my initial troubleshooting, my apologies. From a Debian command line, it now works. I still do have the issue sshing from a Cisco router and from Putty, as described above. I reloaded a test PC, it did bring somehow interesting things about CPU speed that I will detail in the other thread.
