### ISSUE TITLE
Motherboard GIGABYTE GA-IMB310TN in SELKS5 - Problem with the Second Network Card

### ISSUE THREAD

**Issue by lhouser** [StamusNetworks/SELKS#191]
### Description of Problem

During installation of SELKS5 is visible primary network card only (with chipset I-211). Second card is not visible, if we are using command: 
`$ sudo ip a`
 But device is visible in output of command: 
`$ sudo lspci `
(as  00:1f.6 Ethernet controller: Intel Corporation Device 15bc (rev 10))

### Description of Enabling Second Network Card for the Motherboard GIGABYTE GA-IMB310TN in SELKS5

1) First necessary action is update BIOS to latest version. It was version F12 in my case. Installed version of BIOS was F1. Download it from site https://www.gigabyte.com/Motherboard/GA-IMB310TN-rev-10#support-dl-bios and upgrade BIOS.
2) Next it's necessary download correct drivers from https://downloadcenter.intel.com/download/15817/Intel-Network-Adapter-Driver-for-PCI-E-Gigabit-Network-Connections-under-Linux-?product=71307 (Tested with version 3.4.2.4)
2.1. Unpack zip to folder of your choice
2.2. Change to the driver src directory, e.g. 
`$ cd e1000e-3.4.2.4/src/`
2.3. Make sure that any older e1000e drivers are removed from the memmory - command: 
`$ sudo rmmod e1000e`
2.4. Compile the driver module - command: 
`$ sudo make install`
2.5. Load the module using the modprobe command: 
`$ sudo modprobe e1000e` 
The binary driver will be installed as /lib/modules/\`uname -r\`/updates/drivers/net/ethernet/intel/e1000e/e1000e.ko
2.6. Verify that the interface works. It's visible in output of command in this case: 
`$ sudo ip a `
Next enter free IP_address from connected subnet - command: 
`$ sudo ifconfig NET_Device_Name IP_Address netmask NET_Mask up`
 or - command: 
`$ ip address add IP_Address/NET_Mask dev NET_Device_name `
Test it from other computer - command: 
`$ ping IP_Address`
2.7. If all operate OK, make the driver persistent - use command: 
`$ sudo dpkg-reconfigure linux-image-$(uname -r)`

That's all folks! Regards Leos

**Comment by pevma** [comment]
Thank you for the install instructions for the NIC !
