### ISSUE TITLE
DROP rule with "noalert"

### ISSUE THREAD

**Issue by VioletQbik** [StamusNetworks/SELKS#193]
Is there any chance of making drop rule with "noalert" to drop packets? When the rule look like drop ip 8.8.8.8 any <> $HOME_NET any (msg:"TEST"; priority:1; sid:999; noalert;) no drops appears.

**Comment by pevma** [comment]
You need it to just drop without generating alerts/events ?

**Comment by pevma** [comment]
you could try using thresholds to limit the number of logs/events for example - https://suricata.readthedocs.io/en/suricata-4.1.4/rules/thresholding.html#thresholding-keywords

**Comment by VioletQbik** [comment]
In fact, I need just to drop without generating alerts in drop.log.
Here is the idea: when some drop rule generates 10 alerts a day (for example), EXT_NET IP should be permanently banned via rule like "drop ip any any <> $HOME_NET any (msg:"Our Blocking Rule (Reputation)"; priority:1; sid:888; iprep:src,888,>,1;)". This rule has maximum priority. Some script analyses drop.log, then bad IP will be added to my IP reputaion list and after rules reload, all packets with this IP will be dropped.
So, my rule should not generate alert (nothing should be writted to drop.log). Any chance of doing something like that?

**Comment by pevma** [comment]
maybe you could use that -  https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L217 line in the selks5 addin yaml ?

**Comment by VioletQbik** [comment]
If drop log is not generated,  I can't get IP's to ban.

**Comment by pevma** [comment]
oh , right - sorry. I am thinking ``dorp...noalaert` should work ...maybe it is a bug then.
any chance you can share a pcap and post an issue on the suricata redmine tracker?

**Comment by VioletQbik** [comment]
https://redmine.openinfosecfoundation.org/issues/3083 - this issue in suricata redmine tracker.
