### ISSUE TITLE
Syntax error when executing ./filebeat modules enable suricata

### ISSUE THREAD

**Issue by Ropena** [StamusNetworks/SELKS#197]
I am trying to set up SELKS in a virtual box. In trying to setup Suricata to ingest files I tried to run ./filebeat modules enable suricata but I get a syntax error:
./filebeat: 1: ./filebeat: (some characters): not found
./filebeat: 2: ./filebeat: Syntax error: "(" unexpected

If filebeat is a compiled app, why this syntax error? And how do I fix it?

**Comment by pevma** [comment]
Can you explain a bit more of the set up please? How is Suricata ingesting files?

**Comment by Ropena** [comment]
Hi Peter,

Actually, Suricata is not ingesting anything yet. The problem arises when I execute, as per the README file in github, the following command in Ubuntu 18.0:

>./filebeat modules enable Suricata 

If you substitute any other file name for Suricata you get the same error: 

Syntax error unexpected “)”

**Comment by pevma** [comment]
That does not seem SELKS related as SELKS is Debian.

**Comment by Ropena** [comment]
Peter, 

My apologies,then. You are correct. The image now (after reloading) does say it is running over Debian. I had set it up wrongly in the Settings.

Regards,
Rodolfo

**Comment by pevma** [comment]
Thanks for the update!
Please let us know if anything else comes up!
