### ISSUE TITLE
performance tune

### ISSUE THREAD

**Issue by sanpichen** [StamusNetworks/SELKS#198]
Would U give some advises to improve my  suricata ?
Date: 9/24/2019 -- 09:37:35 (uptime: 0d, 19h 29m 50s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 633034297
capture.kernel_drops                          | Total                     | 400835325
decoder.pkts                                  | Total                     | 232191293
decoder.bytes                                 | Total                     | 91337398370
decoder.invalid                               | Total                     | 2
decoder.ipv4                                  | Total                     | 231737674
decoder.ipv6                                  | Total                     | 31596
decoder.ethernet                              | Total                     | 232191293
decoder.tcp                                   | Total                     | 204693149
decoder.udp                                   | Total                     | 24025415
decoder.icmpv4                                | Total                     | 2713309
decoder.icmpv6                                | Total                     | 2701
decoder.avg_pkt_size                          | Total                     | 393
decoder.max_pkt_size                          | Total                     | 1514
flow.tcp                                      | Total                     | 13814518
flow.udp                                      | Total                     | 8159145
flow.icmpv4                                   | Total                     | 161847
flow.icmpv6                                   | Total                     | 834
decoder.ipv4.trunc_pkt                        | Total                     | 2
decoder.icmpv4.unknown_code                   | Total                     | 22
tcp.sessions                                  | Total                     | 6954699
tcp.pseudo                                    | Total                     | 426
tcp.syn                                       | Total                     | 7154879
tcp.synack                                    | Total                     | 6839730
tcp.rst                                       | Total                     | 929181
tcp.stream_depth_reached                      | Total                     | 636
tcp.reassembly_gap                            | Total                     | 306416
tcp.overlap                                   | Total                     | 18360367
detect.alert                                  | Total                     | 729734
app_layer.flow.http                           | Total                     | 3066831
app_layer.tx.http                             | Total                     | 3383035
app_layer.flow.ftp                            | Total                     | 8276
app_layer.flow.smtp                           | Total                     | 7
app_layer.tx.smtp                             | Total                     | 7
app_layer.flow.tls                            | Total                     | 1015514
app_layer.flow.ssh                            | Total                     | 152
app_layer.flow.smb                            | Total                     | 1
app_layer.tx.smb                              | Total                     | 1
app_layer.flow.dns_tcp                        | Total                     | 1
app_layer.tx.dns_tcp                          | Total                     | 2
app_layer.flow.enip_tcp                       | Total                     | 4
app_layer.tx.enip_tcp                         | Total                     | 105
app_layer.flow.ntp                            | Total                     | 44383
app_layer.flow.ftp-data                       | Total                     | 1128
app_layer.flow.ikev2                          | Total                     | 1
app_layer.flow.dhcp                           | Total                     | 952
app_layer.flow.failed_tcp                     | Total                     | 136942
app_layer.flow.dcerpc_udp                     | Total                     | 23079
app_layer.flow.dns_udp                        | Total                     | 7656904
app_layer.tx.dns_udp                          | Total                     | 18091032
app_layer.flow.enip_udp                       | Total                     | 2
app_layer.tx.enip_udp                         | Total                     | 2
app_layer.tx.ntp                              | Total                     | 61520
app_layer.tx.ikev2                            | Total                     | 1
app_layer.tx.dhcp                             | Total                     | 4177
app_layer.flow.failed_udp                     | Total                     | 433824
flow_mgr.closed_pruned                        | Total                     | 3709914
flow_mgr.new_pruned                           | Total                     | 15098076
flow_mgr.est_pruned                           | Total                     | 3293252
flow.spare                                    | Total                     | 10114
flow.tcp_reuse                                | Total                     | 8712
flow_mgr.flows_checked                        | Total                     | 2809
flow_mgr.flows_notimeout                      | Total                     | 2446
flow_mgr.flows_timeout                        | Total                     | 363
flow_mgr.flows_timeout_inuse                  | Total                     | 26
flow_mgr.flows_removed                        | Total                     | 337
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 63443
flow_mgr.rows_empty                           | Total                     | 200
flow_mgr.rows_maxlen                          | Total                     | 6
tcp.memuse                                    | Total                     | 4151000
tcp.reassembly_memuse                         | Total                     | 66847336
http.memuse                                   | Total                     | 63404929
ftp.memuse                                    | Total                     | 98795
flow.memuse                                   | Total                     | 17764256

the selks lastest running
I have separated Es  from selks
already deprecated  moloch,kibana
system resource as follow
root@SELKS:/var/log/suricata# vmstat 1 10
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 311368 128524 130056 3649412    0    0    66   389    6    6 47  2 44  7  0
 1  0 311368 127904 130056 3650264    0    0     0     0 9846 1739 53  2 46  0  0
 1  0 311368 126912 130064 3651028    0    0     0    16 9603 2387 53  3 45  0  0
 1  0 311368 126292 130064 3651572    0    0     0     4 10066 3162 56  2 42  0  0
 4  0 311368 125672 130064 3652084    0    0     0     0 10127 2546 33  1 66  0  0
 1  0 311368 125176 130072 3652624    0    0     0    28 10556 1861 57  3 40  0  0
 2  0 311368 124432 130072 3653356    0    0     0     0 10277 3221 36  1 63  0  0
 1  0 311368 123192 130080 3654480    0    0     0    52 10243 2015 59  3 37  0  0
 3  0 311368 122448 130080 3655328    0    0     0     0 9746 1121 55  2 43  0  0
 5  0 311368 121456 130080 3656184    0    0     0     0 9840 1486 54  3 43  0  0

I have tried  that : 
increase the default stream: memcap: and stream: reassembly: memcap: values
decrease the default flow-timeouts: (at least for TCP)
set checksum-validation: no
increase max-pending-packets value
change to high profile in -> detect-engine: profile: high
increase the request-body-limit: and response-body-limit: values
.......

am I already max utilize  or can do any more ?

**Comment by pevma** [comment]
How much traffic are you monitoring? How busy are your CPUs?

**Comment by sanpichen** [comment]
traffic :AVG 60MB/s,MAX 126MB/S，avg 15000rxpck/s

cpu occupies snapshot :

top - 09:22:17 up 18 days, 19:50,  2 users,  load average: 1.69, 1.58, 1.64
Tasks: 130 total,   1 running, 129 sleeping,   0 stopped,   0 zombie
%Cpu0  : 26.8 us,  0.3 sy,  0.0 ni, 72.2 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu1  : 36.5 us,  0.3 sy,  0.0 ni, 61.5 id,  0.0 wa,  0.0 hi,  1.7 si,  0.0 st
%Cpu2  : 34.9 us,  1.3 sy,  0.0 ni, 61.5 id,  0.0 wa,  0.0 hi,  2.3 si,  0.0 st
%Cpu3  : 28.5 us,  0.7 sy,  0.0 ni, 70.1 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
KiB Mem :  6112760 total,   206240 free,  1235644 used,  4670876 buff/cache
KiB Swap:  6287356 total,  5964332 free,   323024 used.  4518912 avail Mem

**Comment by pevma** [comment]
In which yaml did you make the changes? 
Can you please share/attach the file?

Thank you

**Comment by sanpichen** [comment]
some parameters have  declined now

the currently  yamls as follow:
[selks5-interfaces-config.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3650823/selks5-interfaces-config.yaml.txt)
[suricata.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3650824/suricata.yaml.txt)
[selks5-addin.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3650825/selks5-addin.yaml.txt)

[suricata.log](https://github.com/StamusNetworks/SELKS/files/3650809/suricata.log)
[stats.log](https://github.com/StamusNetworks/SELKS/files/3650810/stats.log)

**Comment by pevma** [comment]
try setting max-pending-packets to 10 000  also set up in selks5-interfaces-config.yaml `ring-size: 50000`and see if any diff?

**Comment by sanpichen** [comment]
already  modified  to  max-pending-packets to 10 000 and  ring-size: 50000 ,seems not  significantly
Date: 9/26/2019 -- 16:34:30 (uptime: 0d, 02h 19m 16s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 105921252
capture.kernel_drops                          | Total                     | 64309063
decoder.pkts                                  | Total                     | 41367937
decoder.bytes                                 | Total                     | 18596591098
decoder.invalid                               | Total                     | 4
decoder.ipv4                                  | Total                     | 41315929
decoder.ipv6                                  | Total                     | 3694
decoder.ethernet                              | Total                     | 41367937
decoder.tcp                                   | Total                     | 34047942
decoder.udp                                   | Total                     | 6989263
decoder.icmpv4                                | Total                     | 244621
decoder.icmpv6                                | Total                     | 292
decoder.avg_pkt_size                          | Total                     | 449
decoder.max_pkt_size                          | Total                     | 1514
flow.tcp                                      | Total                     | 4969129
flow.udp                                      | Total                     | 3545773
flow.icmpv4                                   | Total                     | 76244
flow.icmpv6                                   | Total                     | 129
decoder.ipv4.trunc_pkt                        | Total                     | 4
decoder.icmpv4.unknown_code                   | Total                     | 3
tcp.sessions                                  | Total                     | 1076745
tcp.pseudo                                    | Total                     | 2
tcp.syn                                       | Total                     | 1092657
tcp.synack                                    | Total                     | 1044310
tcp.rst                                       | Total                     | 246104
tcp.stream_depth_reached                      | Total                     | 153
tcp.reassembly_gap                            | Total                     | 42840
tcp.overlap                                   | Total                     | 2462128
detect.alert                                  | Total                     | 152193
app_layer.flow.http                           | Total                     | 372236
app_layer.tx.http                             | Total                     | 444021
app_layer.flow.ftp                            | Total                     | 716
app_layer.flow.smtp                           | Total                     | 1
app_layer.tx.smtp                             | Total                     | 1
app_layer.flow.tls                            | Total                     | 87327
app_layer.flow.ssh                            | Total                     | 28
app_layer.flow.ntp                            | Total                     | 5630
app_layer.flow.ftp-data                       | Total                     | 109
app_layer.flow.dhcp                           | Total                     | 229
app_layer.flow.failed_tcp                     | Total                     | 12474
app_layer.flow.dcerpc_udp                     | Total                     | 25587
app_layer.flow.dns_udp                        | Total                     | 3061237
app_layer.tx.dns_udp                          | Total                     | 3785026
app_layer.tx.ntp                              | Total                     | 6827
app_layer.tx.dhcp                             | Total                     | 461
app_layer.flow.failed_udp                     | Total                     | 453090
flow_mgr.closed_pruned                        | Total                     | 422733
flow_mgr.new_pruned                           | Total                     | 7828756
flow_mgr.est_pruned                           | Total                     | 331573
flow.spare                                    | Total                     | 10079
flow.tcp_reuse                                | Total                     | 816
flow_mgr.flows_checked                        | Total                     | 1856
flow_mgr.flows_notimeout                      | Total                     | 775
flow_mgr.flows_timeout                        | Total                     | 1081
flow_mgr.flows_timeout_inuse                  | Total                     | 31
flow_mgr.flows_removed                        | Total                     | 1050
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 63285
flow_mgr.rows_empty                           | Total                     | 692
flow_mgr.rows_maxlen                          | Total                     | 4
tcp.memuse                                    | Total                     | 2714680
tcp.reassembly_memuse                         | Total                     | 41238008
http.memuse                                   | Total                     | 55645955
ftp.memuse                                    | Total                     | 9411
app_layer.expectations                        | Total                     | 4
flow.memuse                                   | Total                     | 11296352
------------------------------------------------------------------------------------
Date: 9/26/2019 -- 16:34:48 (uptime: 0d, 02h 19m 34s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 105921252
capture.kernel_drops                          | Total                     | 64309063
decoder.pkts                                  | Total                     | 41367937
decoder.bytes                                 | Total                     | 18596591098
decoder.invalid                               | Total                     | 4
decoder.ipv4                                  | Total                     | 41315929
decoder.ipv6                                  | Total                     | 3694
decoder.ethernet                              | Total                     | 41367937
decoder.tcp                                   | Total                     | 34047942
decoder.udp                                   | Total                     | 6989263
decoder.icmpv4                                | Total                     | 244621
decoder.icmpv6                                | Total                     | 292
decoder.avg_pkt_size                          | Total                     | 449
decoder.max_pkt_size                          | Total                     | 1514
flow.tcp                                      | Total                     | 4969129
flow.udp                                      | Total                     | 3545773
flow.icmpv4                                   | Total                     | 76244
flow.icmpv6                                   | Total                     | 129
decoder.ipv4.trunc_pkt                        | Total                     | 4
decoder.icmpv4.unknown_code                   | Total                     | 3
tcp.sessions                                  | Total                     | 1076745
tcp.pseudo                                    | Total                     | 2
tcp.syn                                       | Total                     | 1092657
tcp.synack                                    | Total                     | 1044310
tcp.rst                                       | Total                     | 246104
tcp.stream_depth_reached                      | Total                     | 153
tcp.reassembly_gap                            | Total                     | 42840
tcp.overlap                                   | Total                     | 2462128
detect.alert                                  | Total                     | 152193
app_layer.flow.http                           | Total                     | 372236
app_layer.tx.http                             | Total                     | 444021
app_layer.flow.ftp                            | Total                     | 716
app_layer.flow.smtp                           | Total                     | 1
app_layer.tx.smtp                             | Total                     | 1
app_layer.flow.tls                            | Total                     | 87327
app_layer.flow.ssh                            | Total                     | 28
app_layer.flow.ntp                            | Total                     | 5630
app_layer.flow.ftp-data                       | Total                     | 109
app_layer.flow.dhcp                           | Total                     | 229
app_layer.flow.failed_tcp                     | Total                     | 12474
app_layer.flow.dcerpc_udp                     | Total                     | 25587
app_layer.flow.dns_udp                        | Total                     | 3061237
app_layer.tx.dns_udp                          | Total                     | 3785026
app_layer.tx.ntp                              | Total                     | 6827
app_layer.tx.dhcp                             | Total                     | 461
app_layer.flow.failed_udp                     | Total                     | 453090
flow_mgr.closed_pruned                        | Total                     | 423740
flow_mgr.new_pruned                           | Total                     | 7846155
flow_mgr.est_pruned                           | Total                     | 332307
flow.spare                                    | Total                     | 10141
flow.tcp_reuse                                | Total                     | 818
flow_mgr.flows_checked                        | Total                     | 1389
flow_mgr.flows_notimeout                      | Total                     | 566
flow_mgr.flows_timeout                        | Total                     | 823
flow_mgr.flows_timeout_inuse                  | Total                     | 45
flow_mgr.flows_removed                        | Total                     | 778
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 63905
flow_mgr.rows_empty                           | Total                     | 451
flow_mgr.rows_maxlen                          | Total                     | 3
tcp.memuse                                    | Total                     | 2714840
tcp.reassembly_memuse                         | Total                     | 42586108
http.memuse                                   | Total                     | 56724240
ftp.memuse                                    | Total                     | 9411
app_layer.expectations                        | Total                     | 4
flow.memuse                                   | Total                     | 11095712

**Comment by sanpichen** [comment]
Date: 9/26/2019 -- 16:34:30 (uptime: 0d, 02h 19m 16s)
------------------------------------------------------------------------------------
Date: 9/26/2019 -- 16:34:48 (uptime: 0d, 02h 19m 34s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 105921252
capture.kernel_drops                          | Total                     | 64309063
decoder.pkts                                  | Total                     | 41367937
decoder.bytes                                 | Total                     | 18596591098
decoder.invalid                               | Total                     | 4
decoder.ipv4                                  | Total                     | 41315929
decoder.ipv6                                  | Total                     | 3694
decoder.ethernet                              | Total                     | 41367937
decoder.tcp                                   | Total                     | 34047942
decoder.udp                                   | Total                     | 6989263
decoder.icmpv4                                | Total                     | 244621
decoder.icmpv6                                | Total                     | 292
decoder.avg_pkt_size                          | Total                     | 449
decoder.max_pkt_size                          | Total                     | 1514
flow.tcp                                      | Total                     | 4969129
flow.udp                                      | Total                     | 3545773
flow.icmpv4                                   | Total                     | 76244
flow.icmpv6                                   | Total                     | 129
decoder.ipv4.trunc_pkt                        | Total                     | 4
decoder.icmpv4.unknown_code                   | Total                     | 3
tcp.sessions                                  | Total                     | 1076745
tcp.pseudo                                    | Total                     | 2
tcp.syn                                       | Total                     | 1092657
tcp.synack                                    | Total                     | 1044310
tcp.rst                                       | Total                     | 246104
tcp.stream_depth_reached                      | Total                     | 153
tcp.reassembly_gap                            | Total                     | 42840
tcp.overlap                                   | Total                     | 2462128
detect.alert                                  | Total                     | 152193
app_layer.flow.http                           | Total                     | 372236
app_layer.tx.http                             | Total                     | 444021
app_layer.flow.ftp                            | Total                     | 716
app_layer.flow.smtp                           | Total                     | 1
app_layer.tx.smtp                             | Total                     | 1
app_layer.flow.tls                            | Total                     | 87327
app_layer.flow.ssh                            | Total                     | 28
app_layer.flow.ntp                            | Total                     | 5630
app_layer.flow.ftp-data                       | Total                     | 109
app_layer.flow.dhcp                           | Total                     | 229
app_layer.flow.failed_tcp                     | Total                     | 12474
app_layer.flow.dcerpc_udp                     | Total                     | 25587
app_layer.flow.dns_udp                        | Total                     | 3061237
app_layer.tx.dns_udp                          | Total                     | 3785026
app_layer.tx.ntp                              | Total                     | 6827
app_layer.tx.dhcp                             | Total                     | 461
app_layer.flow.failed_udp                     | Total                     | 453090
flow_mgr.closed_pruned                        | Total                     | 423740
flow_mgr.new_pruned                           | Total                     | 7846155
flow_mgr.est_pruned                           | Total                     | 332307
flow.spare                                    | Total                     | 10141
flow.tcp_reuse                                | Total                     | 818
flow_mgr.flows_checked                        | Total                     | 1389
flow_mgr.flows_notimeout                      | Total                     | 566
flow_mgr.flows_timeout                        | Total                     | 823
flow_mgr.flows_timeout_inuse                  | Total                     | 45
flow_mgr.flows_removed                        | Total                     | 778
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 63905
flow_mgr.rows_empty                           | Total                     | 451
flow_mgr.rows_maxlen                          | Total                     | 3
tcp.memuse                                    | Total                     | 2714840
tcp.reassembly_memuse                         | Total                     | 42586108
http.memuse                                   | Total                     | 56724240
ftp.memuse                                    | Total                     | 9411
app_layer.expectations                        | Total                     | 4
flow.memuse                                   | Total                     | 11095712

**Comment by pevma** [comment]
Just to confirm - you modified the `ring-size` in `selks5-interfaces-config.yaml`. Then max-pending packets in `selks5-addin.yaml` , then restart suricata (`systemctl restart suricata`) - was that the sequence you did ?

**Comment by sanpichen** [comment]
YES ,I am sure

**Comment by pevma** [comment]
ok - then try increase those to 50 000 (max pending packets) and 150 000 (ringside) respectively.

Also what is  the max packet size you see on the interface  ?

**Comment by sanpichen** [comment]
about the packet size :
root@SELKS128:~# ethtool -S enp5s0
NIC statistics:
     rx_bytes: 3736895248362
     rx_error_bytes: 0
     tx_bytes: 92044
     tx_error_bytes: 0
     rx_ucast_packets: 9059045947
     rx_mcast_packets: 77724828
     rx_bcast_packets: 45412625
     tx_ucast_packets: 778
     tx_mcast_packets: 566
     tx_bcast_packets: 0
     tx_mac_errors: 0
     tx_carrier_errors: 0
     rx_crc_errors: 0
     rx_align_errors: 0
     tx_single_collisions: 0
     tx_multi_collisions: 0
     tx_deferred: 0
     tx_excess_collisions: 0
     tx_late_collisions: 0
     tx_total_collisions: 0
     rx_fragments: 0
     rx_jabbers: 0
     rx_undersize_packets: 0
     rx_oversize_packets: 0
     rx_64_byte_packets: 1250620336
     rx_65_to_127_byte_packets: 283667232
     rx_128_to_255_byte_packets: 498175538
     rx_256_to_511_byte_packets: 650569651
     rx_512_to_1023_byte_packets: 364953172
     rx_1024_to_1522_byte_packets: 1839230175
     rx_1523_to_9022_byte_packets: 0
     tx_64_byte_packets: 778
     tx_65_to_127_byte_packets: 566
     tx_128_to_255_byte_packets: 0
     tx_256_to_511_byte_packets: 0
     tx_512_to_1023_byte_packets: 0
     tx_1024_to_1522_byte_packets: 0
     tx_1523_to_9022_byte_packets: 0
     rx_xon_frames: 0
     rx_xoff_frames: 0
     tx_xon_frames: 0
     tx_xoff_frames: 0
     rx_mac_ctrl_frames: 0
     rx_filtered_packets: 42295640
     rx_ftq_discards: 0
     rx_discards: 0
     rx_fw_discards: 692

**Comment by sanpichen** [comment]
both alter:
Date: 9/29/2019 -- 08:45:00 (uptime: 0d, 06h 42m 11s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 152851447
capture.kernel_drops                          | Total                     | 89031612
decoder.pkts                                  | Total                     | 63361910
decoder.bytes                                 | Total                     | 20756601240
decoder.ipv4                                  | Total                     | 63200692
decoder.ipv6                                  | Total                     | 11474
decoder.ethernet                              | Total                     | 63361910
decoder.tcp                                   | Total                     | 56849604
decoder.udp                                   | Total                     | 5838689
decoder.icmpv4                                | Total                     | 400413
decoder.icmpv6                                | Total                     | 946
decoder.avg_pkt_size                          | Total                     | 327
decoder.max_pkt_size                          | Total                     | 1514
flow.tcp                                      | Total                     | 7888094
flow.udp                                      | Total                     | 4469821
flow.icmpv4                                   | Total                     | 149059
flow.icmpv6                                   | Total                     | 441
decoder.icmpv4.unknown_code                   | Total                     | 7
tcp.sessions                                  | Total                     | 2478728
tcp.pseudo                                    | Total                     | 1048
tcp.syn                                       | Total                     | 2503766
tcp.synack                                    | Total                     | 2422748
tcp.rst                                       | Total                     | 209400
tcp.stream_depth_reached                      | Total                     | 153
tcp.reassembly_gap                            | Total                     | 44316
....

I will   decrease it   respectively  later

**Comment by pevma** [comment]
Can you upload you “/var/log/suricata/suricata.log”  as well please ?

> -- 
> Regards,
> Peter Manev

**Comment by sanpichen** [comment]
.
just some reload info  as follow:
.....
[11380] 29/9/2019 -- 02:03:54 - (source-af-packet.c:509) <Info> (AFPPeersListReachedInc) -- All AFP capture threads are running.
[12837] 29/9/2019 -- 08:49:13 - (suricata.c:1058) <Notice> (LogVersion) -- This is Suricata version 5.0.0-dev (rev 69d0d484e)
[12837] 29/9/2019 -- 08:49:13 - (util-cpu.c:171) <Info> (UtilCpuPrintSummary) -- CPUs/cores online: 4
[12839] 29/9/2019 -- 08:49:13 - (util-privs.c:93) <Info> (SCDropMainThreadCaps) -- dropped the caps for main thread
[12839] 29/9/2019 -- 08:49:13 - (counters.c:264) <Warning> (StatsInitCtxPreOutput) -- [ERRCODE: SC_WARN_DEFAULT_WILL_CHANGE(317)] - in 5.0 the default for decoder event stats will go from 'decoder.<proto>.<event>' to 'decoder.event.<proto>.<event>'. See ticket #2225. To
 suppress this message, set stats.decoder-events-prefix in the yaml.
[12839] 29/9/2019 -- 08:49:13 - (util-logopenfile.c:478) <Info> (SCConfLogOpenGeneric) -- eve-log output device (regular) initialized: eve.json
[12839] 29/9/2019 -- 08:49:13 - (output-json-email-common.c:455) <Info> (OutputEmailInitConf) -- Going to log the md5 sum of email body
[12839] 29/9/2019 -- 08:49:13 - (output-json-email-common.c:459) <Info> (OutputEmailInitConf) -- Going to log the md5 sum of email subject
[12839] 29/9/2019 -- 08:49:13 - (output-json-dnp3.c:392) <Info> (OutputDNP3LogInitSub) -- DNP3 log sub-module initialized.
[12839] 29/9/2019 -- 08:49:13 - (output-json-dnp3.c:392) <Info> (OutputDNP3LogInitSub) -- DNP3 log sub-module initialized.
[12839] 29/9/2019 -- 08:49:13 - (output-json-stats.c:468) <Warning> (OutputStatsLogInitSub) -- [ERRCODE: SC_WARN_EVE_MISSING_EVENTS(318)] - eve.stats will not display all decoder events correctly. See #2225. Set a prefix in stats.decoder-events-prefix. In 5.0 the prefix
 will default to 'decoder.event'.
[12839] 29/9/2019 -- 08:49:13 - (util-logopenfile.c:478) <Info> (SCConfLogOpenGeneric) -- stats output device (regular) initialized: stats.log
[12839] 29/9/2019 -- 08:49:13 - (util-conf.c:115) <Info> (ConfUnixSocketIsEnable) -- Running in live mode, activating unix socket
[12839] 29/9/2019 -- 08:49:13 - (reputation.c:639) <Info> (SRepInit) -- Loading reputation file: /etc/suricata/rules/scirius-iprep.list
[12839] 29/9/2019 -- 08:49:22 - (detect-engine-loader.c:351) <Info> (SigLoadSignatures) -- 1 rule files processed. 19380 rules successfully loaded, 0 rules failed
[12839] 29/9/2019 -- 08:49:22 - (util-threshold-config.c:1126) <Info> (SCThresholdConfParseFile) -- Threshold config parsed: 0 rule(s) found
[12839] 29/9/2019 -- 08:49:23 - (detect-engine-build.c:1427) <Info> (SigAddressPrepareStage1) -- 19384 signatures processed. 10 are IP-only rules, 5142 are inspecting packet payload, 16411 inspect application layer, 0 are decoder event only
[12839] 29/9/2019 -- 08:50:16 - (util-runmodes.c:297) <Info> (RunModeSetLiveCaptureWorkersForDevice) -- Going to use 4 thread(s)
[12839] 29/9/2019 -- 08:50:16 - (util-conf.c:115) <Info> (ConfUnixSocketIsEnable) -- Running in live mode, activating unix socket
[12839] 29/9/2019 -- 08:50:16 - (unix-manager.c:131) <Info> (UnixNew) -- Using unix socket file '/var/run/suricata/suricata-command.socket'
[12839] 29/9/2019 -- 08:50:16 - (tm-threads.c:2157) <Notice> (TmThreadWaitOnThreadInit) -- all 4 packet processing threads, 4 management threads initialized, engine started.
[12843] 29/9/2019 -- 08:50:17 - (source-af-packet.c:509) <Info> (AFPPeersListReachedInc) -- All AFP capture threads are running.

**Comment by pevma** [comment]
ok -  i see no hints here. What does htop look like when you run the tests? 
also if you could upload a screenshot of  -  top -H -p `pidof suricata` , could help to see of one thread/cpu is is busier than others.

**Comment by sanpichen** [comment]
selks-user@SELKS128:~$ top -H -p 20168
top - 10:19:00 up 31 days, 20:47,  2 users,  load average: 2.82, 3.15, 3.27
Threads:  10 total,   1 running,   9 sleeping,   0 stopped,   0 zombie
%Cpu(s): 30.8 us,  1.5 sy, 25.6 ni, 40.6 id,  0.2 wa,  0.0 hi,  1.3 si,  0.0 st
KiB Mem :  6112760 total,   121228 free,  3521084 used,  2470448 buff/cache
KiB Swap:  6287356 total,  5986780 free,   300576 used.  2295728 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                   
20179 logstash  20   0 1618096 1.365g 338568 S 31.2 23.4 141:50.25 W#01-enp5s0                                                                                                                                                                                               
20180 logstash  20   0 1618096 1.365g 338568 S 30.6 23.4 141:38.62 W#02-enp5s0                                                                                                                                                                                               
20182 logstash  20   0 1618096 1.365g 338568 R 30.2 23.4 142:55.44 W#04-enp5s0                                                                                                                                                                                               
20181 logstash  20   0 1618096 1.365g 338568 S 27.2 23.4 142:00.50 W#03-enp5s0                                                                                                                                                                                               
20184 logstash  20   0 1618096 1.365g 338568 S  8.6 23.4  29:36.68 FR#01                                                                                                                                                                                                     
20183 logstash  20   0 1618096 1.365g 338568 S  1.3 23.4   5:50.01 FM#01                                                                                                                                                                                                     
20168 logstash  20   0 1618096 1.365g 338568 S  0.3 23.4   1:55.42 Suricata-Main                                                                                                                                                                                             
20185 logstash  20   0 1618096 1.365g 338568 S  0.0 23.4   0:00.36 CW                                                                                                                                                                                                        
20186 logstash  20   0 1618096 1.365g 338568 S  0.0 23.4   0:01.67 CS                                                                                                                                                                                                        
20187 logstash  20   0 1618096 1.365g 338568 S  0.0 23.4   0:04.02 US

**Comment by sanpichen** [comment]
![无标题](https://user-images.githubusercontent.com/38068938/66362660-368c6100-e9b6-11e9-9188-200952ebf306.png)

**Comment by pevma** [comment]
Do you mind sharing al the yaml configs ? (`selks5-interfaces-config.yaml`, `selks5-addin.yaml`)

**Comment by sanpichen** [comment]
here u r


[selks5-addin.yaml .txt](https://github.com/StamusNetworks/SELKS/files/3709968/selks5-addin.yaml.txt)
[selks5-interfaces-config.txt](https://github.com/StamusNetworks/SELKS/files/3709969/selks5-interfaces-config.txt)
[suricata.yaml.txt](https://github.com/StamusNetworks/SELKS/files/3709970/suricata.yaml.txt)

**Comment by pevma** [comment]
Sorry for the late reply. I see no "red cards" here - very interesting.  Can you try giving the VM 8GB ram and redo the tests ? with sharing the same screenshots as above?

Also if possible - would it be ok to share (privately) some of the traffic/pcap?

**Comment by sanpichen** [comment]
I have increased SWAP to 8G ,It seems not very significant .
I will try other tunes or servers.
Thank you so much !
