### ISSUE TITLE
How to reset all stats/logs/alerts?

### ISSUE THREAD

**Issue by bugsland** [StamusNetworks/SELKS#20]
Hi,

Is there a way to easily reset all stats/logs/alerts on SELKS?
I want to keep any custom config, but would like to start afresh with all the stats from the different dashboard.

Also, as I am running a VM, this would be useful to reset "captured" data before taking a snashpot so it reduces the size of the snaptop.

Cheers,
B.

**Comment by regit** [comment]
Hi,

You can try to run on SELKS:
```
curl -XDELETE 'http://localhost:9200/logstash*/'
```
It will delete all index in ES.

Also you may find interesting to delete suricata log:
- service suricata stop
- rm /var/log/suricata/*
- service suricata start

**Comment by bugsland** [comment]
Thanks it worked!

**Comment by pevma** [comment]
I updated the wiki here - 
https://github.com/StamusNetworks/SELKS/wiki/Reset-stats-and-logs
Thanks
