### ISSUE TITLE
Problem with IPS-mode (AF_PACKET)

### ISSUE THREAD

**Issue by GurovEugen** [StamusNetworks/SELKS#200]
Hello, I am trying to configure suricata in ips mode via af-packet. Here are my interface settings and suricata.yaml, suricata-start.log -- https://drive.google.com/open?id=1UZWZDr_IQmgtIiYBS_9w45mNmpCn2qyo.
I tried these settings and enable and disable:
sysctl net.ipv4.conf.all.arp_filter = 0
sysctl net.ipv4.ip_forward = 0
ip link set ens1f0 arp off
ip link set ens1f1 arp off

In tcpdump, only arp-request is visible on both interfaces, but packets are not copied between interfaces.

Thanks in advance for your reply.

**Comment by GurovEugen** [comment]
![8](https://user-images.githubusercontent.com/17644941/65812975-f8927e80-e1f8-11e9-8bdf-87d44c59a579.png)
![1](https://user-images.githubusercontent.com/17644941/65812976-f92b1500-e1f8-11e9-8dfe-f5ebd8f0fbc6.png)
![2](https://user-images.githubusercontent.com/17644941/65812977-f92b1500-e1f8-11e9-8d84-fe6ee46992ca.png)
![3](https://user-images.githubusercontent.com/17644941/65812978-f92b1500-e1f8-11e9-85a1-50dd0a343c2a.png)
![4](https://user-images.githubusercontent.com/17644941/65812979-f92b1500-e1f8-11e9-93db-c19876b534ff.png)
![5](https://user-images.githubusercontent.com/17644941/65812980-f9c3ab80-e1f8-11e9-9d2e-8fa669588140.png)
![6](https://user-images.githubusercontent.com/17644941/65812981-f9c3ab80-e1f8-11e9-8115-d4f6fd8e7df1.png)
![7](https://user-images.githubusercontent.com/17644941/65812982-f9c3ab80-e1f8-11e9-8f59-c9791d55dc86.png)

**Comment by pevma** [comment]
Hi,

Not sure but did you follow the guide in the docs for setting up IPS ?

https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---Suricata-IPS

Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by GurovEugen** [comment]
I tried that, too. The difference is that I have af-packet configurations in suricata.yaml

> Hi, Not sure but did you follow the guide in the docs for setting up IPS ? https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---Suricata-IPS Thank you

**Comment by pevma** [comment]
I think you should maybe follow it as it as working set up. Then start the troubleshooting from there.

You could also start with no rules (0) loaded to see if it would work ok.

> -- 
> Regards,
> Peter Manev
