### ISSUE TITLE
Failed to connect to localhost port 9200  selks-first-time-setup-stamus

### ISSUE THREAD

**Issue by OzzyKampha** [StamusNetworks/SELKS#203]
when i run selks-first-time-setup-stamus it failes when i tries to connect to localhost:9200.
it is a new install, so is there a command that needs to be ran first?

**Comment by pevma** [comment]
Do you have  a more verbose output?
I am sure you've seen this - but just wanted to confirm - you have followed the first time instructions here as well , right? (you have enough CPU/MEM etc..)

**Comment by OzzyKampha** [comment]
![image](https://user-images.githubusercontent.com/14088328/66733185-097cfa00-ee5f-11e9-96c6-e3cd6077c63a.png)

Im trying to run it in a vm with 2 cpu and 6Gig memory

**Comment by pevma** [comment]
Seems ES is not responding. Since this is the first time set up -  can you try adding cpl GBs more ram and see if any effect?

**Comment by OzzyKampha** [comment]
It was a memory issue. Did not notice that it was set to dynamic memory. Under 2 gig not working very well :P
