### ISSUE TITLE
Moloch doesn't rotate/delete pcap files.

### ISSUE THREAD

**Issue by kenzoawa** [StamusNetworks/SELKS#206]
Good morning guys,

Just tried and tested the moloch PCAP deletion following their guide with` freeSpaceG=30%` in config ini but still doesn't want to delete old files. 

One thing that is not clear to me is that in the docs they are saying : Make sure that dropUser or dropGroup can actually delete files in the pcap directory and has read/execute permissions in all parent directories. 

But when you go /data/moloch/raw the owner of that folder is `logstash` 

Any clue guys ?

**Comment by pevma** [comment]
If you make `dropUser` to be `logstash`  -would it work?

**Comment by kenzoawa** [comment]
Haven't tried, wouldn't that brake some changes  in log shipping ?

**Comment by pevma** [comment]
It should not as it is logstash doing the actual shipping of the eve.json or you mean the pcaps?

**Comment by kenzoawa** [comment]
Moloch should delete pcap files, but on their page says dropUser should have permissions on that folder, although dropUser doesn't exist. 

If i change the ownership and create dropUser with it removing logstash ownership of the files, will that break something ? 
Current situation :

```
total 1280
drwxr-xr-x   2 root     root        4096 ное 26 12:01 bin
drwxr-xr-x   2 root     root        4096 ное 26 12:01 db
drwxr-xr-x   2 root     root        4096 дек  6 12:00 etc
drwxr-xr-x   2 root     root        4096 ное 26 12:01 include
-rwxr-xr-x   1 root     root         729 ное 19 15:14 LICENSE
drwx------   2 logstash logstash    4096 дек 10 00:00 logs
drwxr-xr-x   2 root     root        4096 ное 26 12:01 lua
drwxr-xr-x 418 root     root       20480 ное 26 12:01 node_modules
drwxrwxr-x   7 root     root        4096 ное 26 12:01 node-v10.16.3-linux-x64
-rw-r--r--   1 root     root     1218116 ное 19 15:14 NOTICE.txt
drwxr-xr-x   2 root     root        4096 ное 26 12:01 notifiers
-rwxr-xr-x   1 root     root        1495 ное 19 15:09 package.json
drwxr-xr-x   4 root     root        4096 ное 26 12:01 parliament
drwxr-xr-x   2 root     root        4096 ное 26 12:01 parsers
drwxr-xr-x   3 root     root        4096 ное 26 12:01 plugins
drwx------   2 logstash logstash    4096 дек  6 12:28 raw
-rwxr-xr-x   1 root     root        1866 ное 19 15:14 README.txt
drwxr-xr-x   6 root     root        4096 ное 26 12:01 viewer
drwxr-xr-x   3 root     root        4096 ное 26 12:01 wiseService
```

**Comment by pevma** [comment]
I think you could test it out and see (maybe in a test environment is preferred). If it brakes something it an be reversed (reverse the config) I think

**Comment by kenzoawa** [comment]
Let me try in staging and report back here :)

**Comment by kenzoawa** [comment]
configured and waiting for the logs to be filled on the drive. 

btw @pevma by any chance you know if SELKS can capture ELB traffic with proxy protocol from AWS ? having some problems with source IP - all the sources are ELB ip, somehow enabling proxy protocol doesn't do the job on ELB.

**Comment by pevma** [comment]
Would be happy to have a look (VXLAN no problem) but for ELB I would love to have a loot a t a pcap if possible.

**Comment by pevma** [comment]
You could also adjust and make that change - https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L133  in the selks/suri yaml config

**Comment by kenzoawa** [comment]
i am dumping traffic with tcpdump and i am seeing that packet capture comes from the real source, not from ELB 

> You could also adjust and make that change - https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L133 in the selks/suri yaml config

made the change and restarted the server, and waiting to see what will come out of that .. i have enabled the proxy protocol V2 on the network load balancer on AWS also 

would you like me to send you the pcap files on email or any related capture status ? :) 

thanks for jumping on this man, appreciate it

**Comment by kenzoawa** [comment]
Enabled XFF on suricata.yaml but still i am getting packets with source of the ELB - no signs of proxy protocol / xff in the packet .. 

`{"timestamp":"2019-12-10T15:21:54.000553+0000","flow_id":1821434289851431,"in_iface":"eth0","event_type":"flow","src_ip":"192.168.211.13","src_port":16486,"dest_ip":"SELKS IP","dest_port":443,"proto":"TCP","app_proto":"http","flow":{"pkts_toserver":6,"pkts_toclient":4,"bytes_toserver":468,"bytes_toclient":597,"start":"2019-12-10T15:20:52.003111+0000","end":"2019-12-10T15:20:52.146302+0000","age":0,"state":"closed","reason":"timeout","alerted":false},"tcp":{"tcp_flags":"1f","tcp_flags_ts":"17","tcp_flags_tc":"1b","syn":true,"fin":true,"rst":true,"psh":true,"ack":true,"state":"closed"`

192.168.211.13 is the ELB

**Comment by pevma** [comment]
If forward or reverse proxy you should also consider adding in 
https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L135 (mode "overwrite")

Which file did you change that settings in ? (you also need suricata restart too , i think you already did that?)

**Comment by kenzoawa** [comment]
> You could also adjust and make that change - https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L133 in the selks/suri yaml config

I have added on line 133 - `yes ` for XFF on suricata and restarted the whole server but no luck with the source IP, i i only see the ELB IP in eve.json

> rd or reverse proxy you should also consider adding in
> https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L135 (mode "overwrite")

changed this line also and restarted suricata but still nothing

**Comment by pevma** [comment]
Hm it could be the proxy vs LB thing actually. If the LB  takes over completely it would be the case yes.

**Comment by kenzoawa** [comment]
Any chance Suricata on SELKS can capture ProxyProtocol V2 - seems like that's required, but i am not sure - still looking into it.

**Comment by kenzoawa** [comment]
No luck with proxy protocol V2 on AWS - i am looking into capturing traffic from 2 interfaces in suricata, is it possible with SELKS to capture traffic on 2 separate interfaces ? 

That way i don't need ELB on AWS.

**Comment by pevma** [comment]
Yes you can have 2 sniffing interfaces.

**Comment by kenzoawa** [comment]
Is it too much trouble to configure it in SELKS or ?

**Comment by pevma** [comment]
No , it is just adding in another interface in the selks5 yaml.

**Comment by kenzoawa** [comment]
This is in  /etc/suricata/selks5-interfaces-config.yaml i guess, but what about moloch config when configuring for packet capture ? I think you cannot choose 2 interfaces in config.ini in moloch.

**Comment by pevma** [comment]
In SELKS it is Suricata that does the packet capture - so you should be good.

**Comment by kenzoawa** [comment]
Just so i can be sure i don't break that's in `/etc/suricata/selks5-interfaces-config.yaml` right ? :)

**Comment by pevma** [comment]
You should be ok :)

**Comment by kenzoawa** [comment]
Thanks a lot pvma, i will close this thread now as solved ! :)
