### ISSUE TITLE
[SELKS 5] Curator doesn't work

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/SELKS#208]
Recently I realised that script /opt/selks/delete-old-logs.sh doesn't work and I have indexes from October 2019.
If I start it manually then I get the error:
```
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/python/3.7.4/lib/python3.7/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
/opt/selks/delete-old-logs.sh: line 18: 243690 Aborted                 (core dumped) /opt/elasticsearch-curator/cur                                             ator_cli delete_indices --filter_list '
[
  {
    "filtertype": "age",
    "source": "creation_date",
    "direction": "older",
    "unit": "days",
    "unit_count": 14
  },
  {
    "filtertype": "pattern",
    "kind": "prefix",
    "value": "logstash*"
  }
]
'
```
How to solve the problem?

**Comment by VN1977** [comment]
This package is installed already.
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g is already the newest version (1:1.2.8.dfsg-5).
```

**Comment by pevma** [comment]
Try installing `zlib1g-dev` ?

**Comment by VN1977** [comment]
The same
`Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.8.dfsg-5).
`

**Comment by pevma** [comment]
Do you do that as a regular user or as root?
Also what happens if you execute the command itself on the shell? (not via the script) ?

**Comment by VN1977** [comment]
I could not resolve this issue so implemented Index lifecycle policy instead of curator.
And corrected elasticsearch6-template.json 
```
{
  "template" : "logstash-*",
  "version" : 60001,
   "settings" : {
     "index" : {
       **"lifecycle" : {
         "name" : "logstash"
       }**,
       "number_of_replicas" : "0",
	   **"number_of_shards": "1",**
       "refresh_interval" : "5s"
     }
   },
  "mappings" : {
    "_default_" : {
      "dynamic_templates" : [ {
        "message_field" : {
          "path_match" : "message",
          "match_mapping_type" : "string",
          "mapping" : {
            "type" : "text",
            "norms" : false
          }
        }
      }, {
        "string_fields" : {
          "match" : "*",
          "match_mapping_type" : "string",
          "mapping" : {
            "type" : "text", "norms" : false,
            "fields" : {
              "keyword" : { "type": "keyword", "ignore_above": 256 }
            }
          }
        }
      } ],
      "properties" : {
        "@timestamp": { "type": "date"},
        "@version": { "type": "keyword"},
        "geoip"  : {
          "dynamic": true,
          "properties" : {
            "ip": { "type": "ip" },
            "location" : { "type" : "geo_point" },
            "latitude" : { "type" : "half_float" },
            "longitude" : { "type" : "half_float" }
          }
        }
      }
    }
  }
}
```

**Comment by esmelnikov** [comment]
I have exactly the same problem

**Comment by pevma** [comment]
Can you  paste the output of 
```
cat /opt/selks/delete-old-logs.sh 
```

I think the command inside should be with `curator-cli`

**Comment by esmelnikov** [comment]
> Can you paste the output of
> 
> ```
> cat /opt/selks/delete-old-logs.sh 
> ```
> 
> I think the command inside should be with `curator-cli`

`root@SELKS:~# cat /opt/selks/delete-old-logs.sh
#!/bin/bash

/opt/elasticsearch-curator/curator_cli delete_indices --filter_list '
[
  {
    "filtertype": "age",
    "source": "creation_date",
    "direction": "older",
    "unit": "days",
    "unit_count": 8
  },
  {
    "filtertype": "pattern",
    "kind": "prefix",
    "value": "logstash*"
  }
]
'
`

**Comment by pevma** [comment]
I think this would solve it - 
https://discuss.elastic.co/t/curator-python-related-error/206446 

in otherwords - use 
`/usr/bin/curator_cli` instead of `/opt/elasticsearch-curator/curator_cli`.

Does it fix the issue ?

**Comment by esmelnikov** [comment]
Thanks for the help, after fixing the script, deleting data works without errors. Thanks.
