### ISSUE TITLE
Moloch 

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#215]
Hi, 
I am testing a fresh installation of SELKS5. Moloch is not running, although the service is enabled. I followed all the first-time-setup steps and SELKS-upgrade to have all components updated to the last available version. Apparently "libssl.so.1.1" is missing. Do I need to install components manually after the initial setup? Here are the logs output. Please assist. Thank you

-------------------------------------------------------------------------
user1@testserver:~$ systemctl status molochpcapread-selks
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-08 10:00:11 EDT; 4h 27min ago
  Process: 34782 ExecStart=/bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1 (code=exited, status=1/FAILURE)
 Main PID: 34782 (code=exited, status=1/FAILURE)
user1@testserver:~$ cat /data/moloch/logs/capture.log
cat: /data/moloch/logs/capture.log: Permission denied
user1@testserver:~$ sudo cat /data/moloch/logs/capture.log
[sudo] password for user1:
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)

**Comment by pevma** [comment]
Can you please try the upgrade and see if it fixes it for you ?

https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-Buster-upgrade

Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by ManuelFFF** [comment]
After some time running updates, the issue persist

---------------------------------------------------------------
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-04-08 18:42:06 EDT; 1s ago
  Process: 28150 ExecStart=/bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1 (code=exited, status=1/FAILURE)
 Main PID: 28150 (code=exited, status=1/FAILURE)

Apr 08 18:42:06 testserver systemd[1]: molochviewer-selks.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 18:42:06 testserver systemd[1]: molochviewer-selks.service: Unit entered failed state.
Apr 08 18:42:06 testserver systemd[1]: molochviewer-selks.service: Failed with result 'exit-code'.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-04-08 18:41:59 EDT; 8s ago
  Process: 28109 ExecStart=/bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1 (code=exited, status=1/FAILURE)
 Main PID: 28109 (code=exited, status=1/FAILURE)
    Tasks: 0 (limit: 9830)
   CGroup: /system.slice/molochpcapread-selks.service

Apr 08 18:41:59 testserver systemd[1]: molochpcapread-selks.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 18:41:59 testserver systemd[1]: molochpcapread-selks.service: Unit entered failed state.
Apr 08 18:41:59 testserver systemd[1]: molochpcapread-selks.service: Failed with result 'exit-code'.
scirius                          STARTING
ii  elasticsearch                        6.8.8                             all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  elasticsearch-curator                5.8.1                             amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                               1:0.11.1                          amd64        no description given
ii  heartbeat-elastic                    6.8.8                             amd64        Ping remote services for availability and log results to Elasticsearch or send to Logstash.
ii  kibana                               6.8.8                             amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus             2019081202                        amd64        Kibana 6 dashboard templates.
ii  logstash                             1:6.8.8-1                         all          An extensible logging pipeline
ii  moloch                               2.2.3-1                           amd64        Moloch Full Packet System
iF  scirius                              3.4.0-5                           amd64        Django application to manage Suricata ruleset
ii  suricata                             2019030601-0stamus0               amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  4.9G     0  4.9G   0% /dev
tmpfs          tmpfs    1000M   65M  936M   7% /run
/dev/sda1      ext4       89G   17G   67G  21% /
tmpfs          tmpfs     4.9G     0  4.9G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     4.9G     0  4.9G   0% /sys/fs/cgroup
tmpfs          tmpfs    1000M   12K 1000M   1% /run/user/1001
user1@testserver:~$ sudo cat /data/moloch/logs/capture.log
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)
/data/moloch/bin/moloch-capture: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)

**Comment by ManuelFFF** [comment]
And also Scirius failed to be fully removed or installed and it won't start now :(

---------------------------------------------
rbarrero@IDSv3:~$ sudo selks-upgrade_stamus
NOTE:
Depending on the size and how busy the system is the upgrade may take a while.
Starting the upgrade sequence...

Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://packages.stamus-networks.com/selks5/debian buster InRelease
Hit:3 http://packages.stamus-networks.com/selks5/debian-kernel buster InRelease
Hit:4 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:5 https://packages.elastic.co/curator/5/debian9 stable InRelease
Hit:6 http://evebox.org/files/debian stable InRelease
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
Reading package lists... Done
Building dependency tree
Reading state information... Done
selks-scripts-stamus is already the newest version (2019102401).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up scirius (3.4.0-5) ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by python)
dpkg: error processing package scirius (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 scirius
E: Sub-process /usr/bin/dpkg returned an error code (1)
NOTE:
Starting second stage upgrade sequence...

outputs.7.pcap-log.enabled = yes
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://packages.stamus-networks.com/selks5/debian buster InRelease
Hit:4 http://packages.stamus-networks.com/selks5/debian-kernel buster InRelease
Hit:2 http://evebox.org/files/debian stable InRelease
Hit:5 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:6 https://packages.elastic.co/curator/5/debian9 stable InRelease
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  curl e2fslibs gir1.2-pango-1.0 libqt5dbus5 libqt5printsupport5 libqt5widgets5 libqt5xml5 libwbclient0 openssl qt5-gtk-platformtheme ssh
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up scirius (3.4.0-5) ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by python)
dpkg: error processing package scirius (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 scirius
E: Sub-process /usr/bin/dpkg returned an error code (1)
scirius: stopped
scirius: started
Job for molochpcapread-selks.service failed because the control process exited with error code.
See "systemctl status molochpcapread-selks.service" and "journalctl -xe" for details.

**Comment by ManuelFFF** [comment]
Also it looks like Scirius was affected during the installation and it won't start now :(

--------------------------------------------------------------------------
user1@testserver:~$ sudo selks-upgrade_stamus
NOTE:
Depending on the size and how busy the system is the upgrade may take a while.
Starting the upgrade sequence...

Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://packages.stamus-networks.com/selks5/debian buster InRelease
Hit:3 http://packages.stamus-networks.com/selks5/debian-kernel buster InRelease
Hit:4 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:5 https://packages.elastic.co/curator/5/debian9 stable InRelease
Hit:6 http://evebox.org/files/debian stable InRelease
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
Reading package lists... Done
Building dependency tree
Reading state information... Done
selks-scripts-stamus is already the newest version (2019102401).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up scirius (3.4.0-5) ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by python)
dpkg: error processing package scirius (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 scirius
E: Sub-process /usr/bin/dpkg returned an error code (1)
NOTE:
Starting second stage upgrade sequence...

outputs.7.pcap-log.enabled = yes
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://packages.stamus-networks.com/selks5/debian buster InRelease
Hit:4 http://packages.stamus-networks.com/selks5/debian-kernel buster InRelease
Hit:2 http://evebox.org/files/debian stable InRelease
Hit:5 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:6 https://packages.elastic.co/curator/5/debian9 stable InRelease
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:5 and /etc/apt/sources.list.d/selks6.list:12
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/selks6.list:6 and /etc/apt/sources.list.d/selks6.list:13
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  curl e2fslibs gir1.2-pango-1.0 libqt5dbus5 libqt5printsupport5 libqt5widgets5 libqt5xml5 libwbclient0 openssl qt5-gtk-platformtheme ssh
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up scirius (3.4.0-5) ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by python)
dpkg: error processing package scirius (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 scirius
E: Sub-process /usr/bin/dpkg returned an error code (1)
scirius: stopped
scirius: started
Job for molochpcapread-selks.service failed because the control process exited with error code.
See "systemctl status molochpcapread-selks.service" and "journalctl -xe" for details.

**Comment by ManuelFFF** [comment]
Will SELKS6 installer be released soon?

**Comment by pevma** [comment]
Was the upgrade successful ?
What is the output of 
```
 lsb_release -a
```

**Comment by ManuelFFF** [comment]
I had to reinstall the machine from scratch because previous install was lost during the upgrade. Scirius DB and other files were corrupted and I was unable to repair and access any data or even recover my visualizations and dashboards.

On the new machine I applied the upgrade before anything else and is working fine so far
