### ISSUE TITLE
SELKS/ELK backups

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#229]
Hi,

* Running SELKS 5 on premises (ELK 6.8.9)

I am looking for good ideas to backup SELKS/ELK. For now I have been using the "Saved Objects" in Kibana, but I would like to implement some automatic backup solution that could save me valuable time in case I need to re-deploy the system, but keep my progress.

Thank you

**Comment by pevma** [comment]
Think you can try something like (as root)
```
cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_export full && deactivate

```
Would it do the job ?

**Comment by ManuelFFF** [comment]
Can you tell me more about how this works?
Would this save:
1- Only dashboards and visualizations in Kibana?
2- All ELK?
3- ELK + Scirius?
4- ELK + Scirius + Suricata?

Where is the output of this command or backup stored?

I apologize for so many questions. 

Thank you

**Comment by pevma** [comment]
Sorry, this will extract all dashboards and visualizations.

**Comment by ManuelFFF** [comment]
Thank you. I will try this solution later.
