### ISSUE TITLE
Alert Severity Colors

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#23]
Hi,

Is there any way to change the colours of the alert severity in the ALERT dashboard (ALERT SEVERITY)?
Right now I have Severity one showing as green, Severity two as blue and severity 2 as orange...
A more standard Red, Orange, Green would make it easier to understand the graph.
Or at least having some king of logic in the colours, severe = red, not important = green/blue
(unless there is already a logic I missed :)

I wouldn't see any options to change the colours, so I am wondering if there is any way to change that?

Thanks,
B.

**Comment by pevma** [comment]
I don't see any way to change the color from Kibana.

**Comment by b-u-g-s** [comment]
This is indeed an issue with Kibana, lot of people have been requesting this... for a long time :(
https://github.com/elastic/kibana/issues/1362
