### ISSUE TITLE
Firt installation preconfigure listenning interface

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#233]
Hello,

Nice SELKSv6, the color is nice and clean. 👍 
Regarding the first boot script 'selks-first-time-setup_stamus'
Can we add in parameter the network interface and the FPC option so the script will run without asking something like : selks-first-time-setup_stamus eth0 1

Kind regards :)

**Comment by pevma** [comment]
Thank you for trying out SELKS !
It is a good  proposition , yes.

Maybe you can also try something like (and line up all needed answers?) :
```
printf 'eth0\n1\n' | selks-first-time-setup_stamus
```

**Comment by b4b857f6ee** [comment]
Nice, i didn't think this was working, thank you :D!!!
