### ISSUE TITLE
Build SELKS6 buster kernel-package

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#234]
Hello,

Debian 10, full update, but during the command : ./install-deps.sh
The command need kernel-package but i can't find any packet with this name.

This is my sources files

![image](https://user-images.githubusercontent.com/36012515/85117804-b6deb380-b21f-11ea-8cf0-0fe74d256e74.png)

Thank you :)

**Comment by pevma** [comment]
Hi,

Thank you for trying it.
Which package exactly is error-ing ? You can try removing it ?

> -- 
> Regards,
> Peter Manev

**Comment by b4b857f6ee** [comment]
The package is : "kernel-package", yes i remove it and no problem because i didn't force the kernel to build the iso.

**Comment by pevma** [comment]
`fixed` now in latest master, thank you for reporting !

**Comment by b4b857f6ee** [comment]
You'r very welcome.
