### ISSUE TITLE
A stop job running for logstash (Nmin Ns / no limit)

### ISSUE THREAD

**Issue by MaratKzn** [StamusNetworks/SELKS#239]
I made a clean installation of SELKS 6.0 from finished build: SELKS-6.0-nodesktop.iso

When you try to completely restart the Linux server, it hangs on the moment:
**"A stop job running for logstash (Nmin Ns / no limit)"**
In this state, it hangs for a long time, for the test I waited 40 minutes.
Only a cold reset helps.

![изображение](https://user-images.githubusercontent.com/67332500/85540505-be3afe00-b61f-11ea-8e94-29b5eff26202.png)

**Comment by pevma** [comment]
Ive seen that too - it seems it can happen and it is an OS thing waiting for some background job to finish  - if there is some auto job or heavy ES search left over for example.

**Comment by callifo** [comment]
Mine was dong this too, it would never stop, left it for over half hour and still going. I figured it was cleaner to kill logstash then to turn off the computer without shutting it down, so I edited the logstash.service file and set it to kill after 5 minutes.

**Comment by pevma** [comment]
Thanks for the feedback and help.
I've updated the docs here -  https://github.com/StamusNetworks/SELKS/wiki/A-stop-job-running-for-logstash-takes-too-long-on-shutdown
