### ISSUE TITLE
SELKS + WAZUH error

### ISSUE THREAD

**Issue by naal71** [StamusNetworks/SELKS#240]
Hello,

Cloud you help me, please... I'm desperated
I'm trying to use WAZUH but it is becoming impossible...

I'm getting the same error always when try to load on kibana:

> Request failed with status code 404 (/hosts/apis)
> 
> Cannot initialize Settings

I tried to use https with stamus self signed certificates.  

And in this is the menu:
![image](https://user-images.githubusercontent.com/62832672/85601326-8f884c00-b64e-11ea-9998-a7ae1d60dae0.png)

This seems normal
![image](https://user-images.githubusercontent.com/62832672/85602921-243f7980-b650-11ea-9ccd-e8c3761466e1.png)

Maybe something in nginx?

Thanks in advance!!!

**Comment by naal71** [comment]
Two more images explaining:

![image](https://user-images.githubusercontent.com/62832672/85603468-b0ea3780-b650-11ea-8eb3-7daee82e6956.png)
![image](https://user-images.githubusercontent.com/62832672/85603546-c1021700-b650-11ea-88b2-ebfdca577bb7.png)

**Comment by pevma** [comment]
I think you might need to add
'/hosts/apis' tot he nginx config and restart nginx - as explained here - https://github.com/StamusNetworks/SELKS/issues/238#issuecomment-648733016

**Comment by naal71** [comment]
I write this in the sites-enabled/selks6.conf
![image](https://user-images.githubusercontent.com/62832672/85990101-c87b4480-b9f1-11ea-9fe5-936a6b769361.png)


And now Im getting this error:

![image](https://user-images.githubusercontent.com/62832672/85990000-a84b8580-b9f1-11ea-918d-5da84f2934b3.png)

**Comment by naal71** [comment]
Wow!!!! I did nothing and now Its working:

![image](https://user-images.githubusercontent.com/62832672/85994352-f82d4b00-b9f7-11ea-9dfa-794bc56cb018.png)

Thanks

**Comment by naal71** [comment]
Hello again,

The problem is not resolved....  

I think that is working partialy... I think that wazuh Its not conecting to elastic index...

**Comment by naal71** [comment]
Hey I solved the problem.

I updated the system to 7.8.0 version.

Then I modify **/etc/nginx/sites-enabled/selks6.conf**

>   location /hosts {
>         proxy_pass http://127.0.0.1:5601/hosts;
>         proxy_redirect off;
>     }
> 
>   location /app/kibana {
>         proxy_pass http://127.0.0.1:5601/app/kibana;
>         proxy_redirect off;
>     }
> 
>   location /utils/configuration {
>         proxy_pass http://127.0.0.1:5601/utils/configuration;
>         proxy_redirect off;
>     }
> 
>   location /31997 {
>         proxy_pass http://127.0.0.1:5601/31997;
>         proxy_redirect off;
>     }
> 
>   location /app/wazuh {
>         proxy_pass http://127.0.0.1:5601/app/wazuh;
>         proxy_redirect off;
>    }
> 
>  location /elastic {
>         proxy_pass http://127.0.0.1:5601/elastic;
>         proxy_redirect off;
>    }

Check the brackets if you are doing copy & paste....

Then restart nginx & kibana and the magic will work...

**Comment by pevma** [comment]
Thank you for the feedback !
