### ISSUE TITLE
Can't access Moloch

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#242]
Hi @pevma ,

This is for a machine running SELKS 5 with ELK 6.8.9 (but also affecting machines with SELKS 5 and ELK 6.8.10)

I am experiencing the following issue with Moloch and I am unable to access it webUI anymore. I have tried https://hostp_ip:8005 like I used to and also by following FPC link from a SN dashboard in Kibana, like I used to as well. If I ran script selks-health-check_stamus, and even if both Moloch services are up and showing green status, there is a new error when attempt access to socket.py file. File is owned by root. I changed permissions to 777, but access error persist. 

I thought it was only affecting machines with SELKS 5 and ELK 6.8.10, after running the "selks-upgrade_stamus", but now I noticed it is affecting a machine running SELKS 5 with ELK 6.8.9.

Any idea about what could cause this and possible quick fix?

Thank you

```
Jun 26 10:26:51 server1 systemd[1]: Started Moloch Pcap Read.
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228

● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-06-26 10:26:45 EDT; 15s ago
 Main PID: 5473 (sh)
    Tasks: 12 (limit: 4915)
   Memory: 53.3M
   CGroup: /system.slice/molochviewer-selks.service
           ├─5473 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1
           └─5474 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini

Jun 26 10:26:45 server1 systemd[1]: Started Moloch Viewer.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-06-26 10:26:51 EDT; 9s ago
 Main PID: 5490 (sh)
    Tasks: 5 (limit: 4915)
   Memory: 141.5M
   CGroup: /system.slice/molochpcapread-selks.service
           ├─5490 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1
           └─5491 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m --copy --delete -R /data/nsm/

Jun 26 10:26:51 server1 systemd[1]: Started Moloch Pcap Read.
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
ii  elasticsearch                        6.8.10                              all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  elasticsearch-curator                5.8.1                               amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                               1:0.11.1                            amd64        no description given
ii  kibana                               6.8.10                              amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus             2019081202                          amd64        Kibana 6 dashboard templates.
ii  logstash                             1:6.8.10-1                          all          An extensible logging pipeline
ii  moloch                               2.3.1-1                             amd64        Moloch Full Packet System
ii  scirius                              3.4.0-5                             amd64        Django application to manage Suricata ruleset
ii  suricata                             1:2020033001-0stamus0               amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  5.9G     0  5.9G   0% /dev
tmpfs          tmpfs     1.2G   24M  1.2G   3% /run
/dev/sda1      ext4      450G   81G  347G  19% /
tmpfs          tmpfs     5.9G     0  5.9G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     5.9G     0  5.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     1.2G  4.0K  1.2G   1% /run/user/112
tmpfs          tmpfs     1.2G     0  1.2G   0% /run/user/1001
```

![moloch](https://user-images.githubusercontent.com/63368223/86276119-56962d00-bba2-11ea-9c7b-4068eb62ee2c.PNG)

**Comment by ManuelFFF** [comment]
**Update**

At least I could confirm Moloch is up and running since I was able to access using https://host_ip/moloch/sessions. But FPC links from Kibana are not working as you can see in the screenshot above (previous post). So it looks like maybe Moloch (or the process running the app) cannot access the socket connection?

**Comment by pevma** [comment]
That  is unusual
```
Jun 26 10:26:51 server1 systemd[1]: Started Moloch Pcap Read.
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
```

**Comment by pevma** [comment]
Do you hav e any other moloch references in the nginx config ?

**Comment by ManuelFFF** [comment]
Hi @pevma ,

Unfortunately I don't have any other reference I can provide. I know that by default Moloch should be listening for incoming connections on https://host:8005, but within SELKS, the server Nginx handles this (and other connections). This was working the last time I checked a couple of weeks ago. From dashboards in Kibana, the FPC link bundled to a report was working fine and by clicking on it, it used to take you to Moloch, so you could examine all the details related to that capture and the correlated events. 

Now I started to notice that access error. I know the owner of that file is root.root. Moloch does not seems to have a dedicated user to run on the system, so it is probably root or any of the others ELK components or Nginx. But the funny thing is that I elevated the file permissions to the top level 777 and still the access error remains. Not sure if re-running a script that deploys only Moloch and reset the access to all files it should work with....

**Comment by pevma** [comment]
Have you installed X-pack on this box or is it without it?

**Comment by ManuelFFF** [comment]
This one does not have X-Pack enabled yet

**Comment by ManuelFFF** [comment]
Hi @pevma ,

Any update on this? 

Thank you

**Comment by ManuelFFF** [comment]
Hi @pevma ,

Any update on this? I just noticed it is happening on machine running SELKS 5 + ELK 6.8.9 and also in machine running SELKS 5 + ELK 6.8.10.

Thank you

**Comment by pevma** [comment]
It seems some ides can be found here how to fix it -  
https://github.com/Supervisor/supervisor/issues/173
https://stackoverflow.com/questions/39310584/provision-supervisor-worker-on-homestead

**Comment by ManuelFFF** [comment]
Update:

I was unable to resolve the issue that prevents Scirius from working properly and also affecting Moloch, due to my lack of knowledge, so I had to use a backup of the entire machine, when Scirius was still working.

The issue is resolved

Thank you
