### ISSUE TITLE
http rule doesn't match

### ISSUE THREAD

**Issue by romanoff971** [StamusNetworks/SELKS#243]
Hi !
Thanks for this wonderfull tool!

I have a little problem with http rules

I'll try to explain.

I wrote this rule :

alert http any any -> any any (msg:"http rule test";content:"facebook"; http_uri; sid:2020000001; rev:1)
it doesn't work

i tried :
alert ip any any -> any any (msg;"ip rule test"; content:"facebook"; sid: 2020000002; rev:1)
it work

So i've tried :
alert http any any -> any any (msg;"http rule test"; sid: 2020000001; rev:2)
no match

so i've tried to use a pcap containing facebook with this command :
suricata -c /etc/suricata/suricata.yaml -r /data/moloch/raw/SELKS-200701-00000150.pcap -S scirius.rules --runmode=autofp
and http rule test matching

so my rules and suricata working properly, but i can't make it work in "live mode"
(i've tried http and https website, same issue)

i hope you understood everything.

Thanks you again

**Comment by pevma** [comment]
If you are trying the command in SELKS you need to also specify a log path - otherwise it will log in the current folder.

So something like so in SELKS it should work.
`suricata -c /etc/suricata/suricata.yaml -r /data/moloch/raw/SELKS-200701-00000150.pcap -S test.rules --runmode=autofp -l /var/log/suricata/`

**Comment by romanoff971** [comment]
Hi, thanks for you response.

The issue is not this command line, i used it just to test my rule, and it works. 
The issue is if i inject the same rule in scirus, it never match. The rule is correctly loaded and activated in the ruleset, but it never match. 

And this rule work in command line for a pcap, but never for and interface (-i) or in selks.

**Comment by pevma** [comment]
oh ok - can you try adjusting the sid to be correct - for local rules
https://doc.emergingthreats.net/bin/view/Main/SidAllocation   

You should probably try to import the rule via scirius  - as an upload instead of `injecting` it into the scirius.rules - it is the expected way to do it with Scirius , after which you should `Update and Push ` (From the Suricata tab)

**Comment by romanoff971** [comment]
The rule is correctly injected with scirius, that is not the problem at all. The problem is with the « http » field in the rule, it does’t work. 
If i make the same rule with « ip » keyword it work. But any rule with « http » keyword never match. 
It’s not an issue about injecting rule, it’s an issue about http keyword never matching. 

If i write this rule :
Alert http any any -> any any (msg:"test http"; sid:000000001; rev:1;) 
Every http traffic have to match, nothing matching. 
It’s not about the traffic, i’ve tried Alert tcp any 80,443... working i’ve tried alert ip any 80,443... working too. But http never match.

**Comment by pevma** [comment]
I could not reproduce it.

What i did was load exactly the same rule into SELKS and run basically some `wget` on random sites     - 
![Screenshot from 2020-07-05 18-55-42](https://user-images.githubusercontent.com/1405917/86540353-dc98d780-bf04-11ea-9629-18263742e529.png)


Then the results   
![Screenshot from 2020-07-05 20-24-08](https://user-images.githubusercontent.com/1405917/86540363-ea4e5d00-bf04-11ea-8dfb-d0becf8dfb84.png)
![Screenshot from 2020-07-05 20-23-41](https://user-images.githubusercontent.com/1405917/86540364-eb7f8a00-bf04-11ea-8da1-4b9dbc1a30d0.png)
![Screenshot from 2020-07-05 20-23-32](https://user-images.githubusercontent.com/1405917/86540365-eb7f8a00-bf04-11ea-942a-c0daaa522409.png)
![Screenshot from 2020-07-05 20-23-23](https://user-images.githubusercontent.com/1405917/86540366-ec182080-bf04-11ea-9e9c-fadec112793f.png)
![Screenshot from 2020-07-05 20-23-12](https://user-images.githubusercontent.com/1405917/86540367-ecb0b700-bf04-11ea-89b2-258332e5b205.png)

**Comment by romanoff971** [comment]
i did exactly the same, a second rule was added to test if there is some matching traffic :

![2020-07-06 07_57_51-Scirius - Source - Add - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560729-51006480-bf5f-11ea-80dd-d9e2428621ff.png)
![2020-07-06 07_59_09-Scirius - Category - 59 - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560733-52ca2800-bf5f-11ea-86db-303bb88f9d31.png)
![2020-07-06 07_59_18-Scirius - Rule - 202000002 - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560736-5493eb80-bf5f-11ea-8ddc-65358076a8ab.png)
![2020-07-06 07_59_25-Scirius - Rule - 202000003 - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560737-55c51880-bf5f-11ea-876a-6f53800c4965.png)
![2020-07-06 08_04_56-Scirius - Hunt - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560822-8442f380-bf5f-11ea-930d-202be4dc65ca.png)
![2020-07-06 08_05_27-Scirius - Hunt - Firefox Developer Edition](https://user-images.githubusercontent.com/52663035/86560823-85742080-bf5f-11ea-9876-701daab2b779.png)


The http one never match

**Comment by pevma** [comment]
In that case  - you might want to troubleshoot the traffic. If you can tcpdump, confirm it is there as expected?
The IP rule works - but it sees only one part of the traffic  - "to server bytes/pyckets" (the to client ones are `0`) in the flow section of the alert (in your screenshot above). That means there is no complete 3WHS.

**Comment by romanoff971** [comment]
that's why i've tried this rule on a moloch pcap (from selks) to see if i miss a part of the flow and with the same rule, and same suricata config, its working, there is my tests :

i've used a pcap generated this morning:
![2020-07-06 10_31_33-bnl@SELKS_ ~](https://user-images.githubusercontent.com/52663035/86573318-86fc1380-bf74-11ea-9be8-8cf320e59786.png)
here is my command :
![2020-07-06 10_34_02-bnl@SELKS_ ~](https://user-images.githubusercontent.com/52663035/86573325-8a8f9a80-bf74-11ea-9c6f-e89b611dc800.png)

11056 match, and 10158 with "http"
![2020-07-06 10_35_31-bnl@SELKS_ ~](https://user-images.githubusercontent.com/52663035/86573445-b4e15800-bf74-11ea-8dcb-2e0c5da02aa9.png)

is it means that all the flow is captured?

**Comment by pevma** [comment]
You can export the pcap and have a look?Would be more than happy to look at it if you can share too.

**Comment by romanoff971** [comment]
Hi, there is an extract of this pcap
https://we.tl/t-8pNnAzAyXl

**Comment by pevma** [comment]
There are alerts with the pcap on  a first read.
So there is no reason not to have them in the Kibana/Hunt, so that sid should be appearing.
Is the sid present in the ruleset that is currently active ?

**Comment by romanoff971** [comment]
yes the current set is the "default ruleset" and as you can see in the previous screenshot, the rule is activated for this ruleset.
I think too there is no reason to not have them in Kibana/Hunt, that's why i'm here :)

**Comment by pevma** [comment]
if you grep for the alert in the eve json logs ....would you find it?
```
grep  2020000002 /var/log/suricata/*.json
```

**Comment by romanoff971** [comment]
No results

**Comment by romanoff971** [comment]
we've tried ssh and ftp too, same.

**Comment by pevma** [comment]
How is traffic mirrored onto the sniffing interface ?

**Comment by romanoff971** [comment]
After a lot of tests and configuration's changes, we found that the problem was the mirroring.
To fix it, now we use a TAP instead of a switch mirroring and everything's fine.

Thanks for your support and your advices. 
I close this issue.

**Comment by pevma** [comment]
Thank you for the feedback !
