### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#259]
Hello,

This will be cool to ad a script to activate properly the file extraction :)

Kind regards

**Comment by pevma** [comment]
You mean - the configuration part?

**Comment by b4b857f6ee** [comment]
Yes :D. You already have a lot of script to configure the interface, tunning... etc... maybe you can add this one like you activate the FPC etc...

**Comment by b4b857f6ee** [comment]
Update your image on the SELKS main github page, you still have the old GUI on https://github.com/StamusNetworks/SELKS

**Comment by pevma** [comment]
@b4b857f6ee  - thank you
https://twitter.com/StamusN/status/1318946677181632517

**Comment by b4b857f6ee** [comment]
> @b4b857f6ee - thank you
> https://twitter.com/StamusN/status/1318946677181632517

Yes thank you!  As i tell to Eric it's Grafana, not "Grifana" x'D.
