### ISSUE TITLE
Suricata rules for Windows is Disabled... why and where?

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#26]
Hi,

This is related to the issue I raised on the Suricata github:
https://redmine.openinfosecfoundation.org/issues/1533

Why is rule 2000419 disabled? it does not appear as disabled in Scirius...
Could you please tell me where else it has been disabled? (so I can re-enable it again!)

This is a very useful rule to detect windows update activities on the network and some people, like me, are interested in seeing those events :)

Thanks.

**Comment by regit** [comment]
This rules is not disabled by scirius or SELKS. It is in fact commented in the emerging threat file so scirius is not parsing it.
So the solution is to add this rules in a custom file and upload it to scirius. I will open a ticket on scirius so we know that in a perfect world we should try to find rules in comment.

**Comment by b-u-g-s** [comment]
Thanks. That does work as a temporary solution. 
There actually quite a few disable rules that way

**Comment by b-u-g-s** [comment]
I understand this has been fixed in Scirius 1.1.2
as per: https://github.com/StamusNetworks/scirius/issues/50

Any ideas when this version will make it to SELKS? just did apt-get update/upgrade/dist-upgrade and we are still using 1.1.1

Thanks.
b.

**Comment by pevma** [comment]
Which version do you have now exactly -1.1.1-2 ?

**Comment by b-u-g-s** [comment]
If I go on the web portal to Ruleset management -> about, all I see is Scirius 1.1.1
Is there another way to check Scirius version?

**Comment by pevma** [comment]
dpkg -l |grep scirius

**Comment by b-u-g-s** [comment]
Thanks. I get: 1.1.1-2
But I cannot see any deleted rules in Scirius web gui... am I looking in the wrong place?

**Comment by pevma** [comment]
1.1.2 is available now - thanks @regit 
@b-u-g-s  - please feel free to  upgrade (apt-get update && apt-get dist-upgrade) and close this issue upon confirmation.

**Comment by b-u-g-s** [comment]
Thanks much!! and it works beautifully! :)
I can also confirm that when you enable a disabled rule and then update the ruleset again, those changes are persistant and the enabled rules remain...
I had to test ;)
And searching on keyword also searches through the disabled rules... perfect!
Thanks again for the very quick turn around!

PS: Not too sure why you need to toggle availablity before enabling the rule... but that's not a problem! I will close this issue now!
