### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#262]
Hello,

Is anyone try to configure Grafana to get data from the elasticsearch?

Thank you :)

**Comment by b4b857f6ee** [comment]
Ok i have start one :)
![image](https://user-images.githubusercontent.com/36012515/96346380-c7068280-109b-11eb-9a30-e0fe8b84779c.png)

**Comment by pevma** [comment]
Nice !
If you have any docs/config process would be happy to add it in the wiki of SELKS.

**Comment by b4b857f6ee** [comment]
> 
> 
> Nice !
> If you have any docs/config process would be happy to add it in the wiki of SELKS.

Let me reproduce all the Kibana dashboard and i will add a repository about this with information about how to do it :)

**Comment by pevma** [comment]
Sounds great !
Thank you

> -- 
> Regards,
> Peter Manev

**Comment by b4b857f6ee** [comment]
@pevma Can you provide me some pcap to replay it to do this dashboard :
KRB5
NFS
RFB
SIP
TFTP

Please :)  or i will do it without but i'm not going to be sure i have the right dashboard configuration.

**Comment by b4b857f6ee** [comment]
@pevma 
Enjoy!
https://github.com/b4b857f6ee/selks_grafana_dashboard

**Comment by pevma** [comment]
@b4b857f6ee  - thank you very much for the contribution !
I think some pcaps could be useful form here  - https://wiki.wireshark.org/SampleCaptures  / https://packettotal.com/

**Comment by pevma** [comment]
I updated the wiki adding the Grafana dashboards repo too - FYI - here https://github.com/StamusNetworks/SELKS/wiki#tutorials

**Comment by b4b857f6ee** [comment]
@pevma Thank you!
I will continue following the task i wrote on the github repo :)
On the Splunk part of the wiki, could you please remove my name :).

**Comment by b4b857f6ee** [comment]
And i have started to add the dashboard on the grafana website :)


    SN-ALERTS https://grafana.com/grafana/dashboards/13204
    SN-ALL https://grafana.com/grafana/dashboards/13205
    SN-ANOMALY https://grafana.com/grafana/dashboards/13206
    SN-DHCP https://grafana.com/grafana/dashboards/13207
    SN-DNS https://grafana.com/grafana/dashboards/13208
    SN-FILE-Transactions https://grafana.com/grafana/dashboards/13209
    SN-FLOW https://grafana.com/grafana/dashboards/13210
    SN-HTTP https://grafana.com/grafana/dashboards/13211
    SN-IDS https://grafana.com/grafana/dashboards/13212
    SN-IKEv2 https://grafana.com/grafana/dashboards/13213
    SN-OVERVIEW https://grafana.com/grafana/dashboards/13214
    SN-RDP https://grafana.com/grafana/dashboards/13215
    SN-SIP https://grafana.com/grafana/dashboards/13216
    SN-SMB https://grafana.com/grafana/dashboards/13217
    SN-SNMP https://grafana.com/grafana/dashboards/13218
    SN-SSH https://grafana.com/grafana/dashboards/13219
    SN-STATS https://grafana.com/grafana/dashboards/13220

**Comment by pevma** [comment]
@b4b857f6ee  - adjusted the wiki. Thank you.

**Comment by b4b857f6ee** [comment]
I have add 

KRB5
NFS
DNP3
NOC - Services

We got Grafana invaded ahah : https://grafana.com/grafana/dashboards?search=SELKS

**Comment by pevma** [comment]
Nice !

**Comment by b4b857f6ee** [comment]
So i can close this fake issue :)
