### ISSUE TITLE
Index "logastash-alerts" without data

### ISSUE THREAD

**Issue by ngms17** [StamusNetworks/SELKS#263]
The index pattern "logstash-alerts" not showing any data

**Comment by pevma** [comment]
Do you have data coming in?
selks-health-check_stamus`` passes ok, all services are green / up and running?

**Comment by ngms17** [comment]
Yes, it´s all up and running. Plus, i can´t upgrade run the upgrade selks command. It gives me this error.

![Capturar](https://user-images.githubusercontent.com/19928515/96036828-eb285080-0e5c-11eb-88da-d5ac92ac4efb.PNG)


And on the first page of selks web browser, some data are not showing up.

![Capturar2](https://user-images.githubusercontent.com/19928515/96036882-0004e400-0e5d-11eb-997d-5eadc753e1c5.PNG)

**Comment by pevma** [comment]
It seems the Moloch upgrade failed. Can you try to rerun the upgrade ? or manually `dpkg -i ...` the moloch deb pkg file ?
Also  - make sure the Elasticsearch service is up and running.

**Comment by ngms17** [comment]
If i re-run the upgrade it gives me the same error. I will try manually. But the error is “buster release does not have a release file”

**Comment by pevma** [comment]
Can you please share the full output of the health check (not just a screenshot)?

**Comment by ngms17** [comment]
Sure.

root@suricata:~# selks-health-check_stamus
● suricata.service - LSB: Next Generation IDS/IPS
   Loaded: loaded (/etc/init.d/suricata; generated)
   Active: active (running) since Thu 2020-10-15 02:01:57 WEST; 9h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1579 ExecStart=/etc/init.d/suricata start (code=exited, status=0/SUCCESS)
    Tasks: 22 (limit: 4915)
   Memory: 12.5G
   CGroup: /system.slice/suricata.service
           └─1585 /usr/bin/suricata -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid --af-packet -D -v --user=logstash

Oct 15 02:01:56 suricata systemd[1]: Starting LSB: Next Generation IDS/IPS...
Oct 15 02:01:57 suricata suricata[1579]: Starting suricata in IDS (af-packet) mode... done.
Oct 15 02:01:57 suricata systemd[1]: Started LSB: Next Generation IDS/IPS.
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-10-14 20:30:36 WEST; 15h ago
     Docs: https://www.elastic.co
 Main PID: 19018 (java)
    Tasks: 194 (limit: 4915)
   Memory: 4.2G
   CGroup: /system.slice/elasticsearch.service
           ├─19018 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djav…
           └─19237 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

Oct 14 20:30:09 suricata systemd[1]: Starting Elasticsearch...
Oct 14 20:30:36 suricata systemd[1]: Started Elasticsearch.
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-10-13 16:48:58 WEST; 1 day 18h ago
 Main PID: 525 (java)
    Tasks: 62 (limit: 4915)
   Memory: 1.8G
   CGroup: /system.slice/logstash.service
           └─525 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encodin…

Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,484][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,484][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,502][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,504][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,504][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,506][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,506][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:32 suricata logstash[525]: [2020-10-14T20:30:32,507][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:34 suricata logstash[525]: [2020-10-14T20:30:34,303][ERROR][logstash.outputs.elasticsearch][main][e55f734d663b7fb7ca21a05c69227f334d0c6198948f303fac6e50c03be43b13] …
Oct 14 20:30:36 suricata logstash[525]: [2020-10-14T20:30:36,885][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://127.0.0.1:9200/"}
Hint: Some lines were ellipsized, use -l to show in full.
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-10-14 20:30:36 WEST; 15h ago
 Main PID: 19355 (node)
    Tasks: 11 (limit: 4915)
   Memory: 387.6M
   CGroup: /system.slice/kibana.service
           └─19355 /usr/share/kibana/bin/../node/bin/node /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

Oct 14 20:39:22 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:22Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:22 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:22Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/api/ui_metri…
Oct 14 20:39:37 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:36Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:38 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:37Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:39 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:38Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:40 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:39Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:41 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:40Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:42 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:41Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:39:42 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:39:42Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/internal/sea…
Oct 14 20:40:10 suricata kibana[19355]: {"type":"response","@timestamp":"2020-10-14T19:40:10Z","tags":[],"pid":19355,"method":"post","statusCode":200,"req":{"url":"/api/ui_metri…
Hint: Some lines were ellipsized, use -l to show in full.
● evebox.service - EveBox Server
   Loaded: loaded (/lib/systemd/system/evebox.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-10-13 16:48:58 WEST; 1 day 18h ago
 Main PID: 524 (evebox)
    Tasks: 20 (limit: 4915)
   Memory: 33.6M
   CGroup: /system.slice/evebox.service
           └─524 /usr/bin/evebox server

Oct 13 16:50:18 suricata evebox[524]: 2020-10-13 16:50:18 (server.go:165) <Info> -- Authentication disabled.
Oct 13 16:50:18 suricata evebox[524]: 2020-10-13 16:50:18 (server.go:261) <Info> -- Listening on [127.0.0.1]:5636
Oct 14 13:08:10 suricata evebox[524]: 2020-10-14 13:08:10 (anonymous.go:64) <Info> -- Logging in anonymous user {suricata-admin} from 127.0.0.1:49570
Oct 14 14:13:18 suricata evebox[524]: 2020-10-14 14:13:18 (sessionstore.go:64) <Info> -- Expiring session -- addr=127.0.0.1:49570 username=suricata-admin
Oct 14 16:59:30 suricata evebox[524]: 2020-10-14 16:59:30 (anonymous.go:64) <Info> -- Logging in anonymous user {suricata-admin} from 127.0.0.1:55366
Oct 14 18:09:18 suricata evebox[524]: 2020-10-14 18:09:18 (sessionstore.go:64) <Info> -- Expiring session -- username=suricata-admin addr=127.0.0.1:55366
Oct 14 20:42:11 suricata evebox[524]: 2020-10-14 20:42:10 (anonymous.go:64) <Info> -- Logging in anonymous user {suricata-admin} from 127.0.0.1:36616
Oct 14 20:44:57 suricata evebox[524]: 2020-10-14 20:44:57 (anonymous.go:64) <Info> -- Logging in anonymous user {suricata-admin} from 127.0.0.1:37292
Oct 14 21:46:18 suricata evebox[524]: 2020-10-14 21:46:18 (sessionstore.go:64) <Info> -- Expiring session -- username=suricata-admin addr=127.0.0.1:37292
Oct 14 21:51:18 suricata evebox[524]: 2020-10-14 21:51:18 (sessionstore.go:64) <Info> -- Expiring session -- username=suricata-admin addr=127.0.0.1:36616
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-10-14 20:31:44 WEST; 15h ago
 Main PID: 19665 (sh)
    Tasks: 12 (limit: 4915)
   Memory: 57.1M
   CGroup: /system.slice/molochviewer-selks.service
           ├─19665 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1
           └─19666 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini

Oct 14 20:31:44 suricata systemd[1]: Started Moloch Viewer.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-10-14 20:31:44 WEST; 15h ago
 Main PID: 19661 (sh)
    Tasks: 5 (limit: 4915)
   Memory: 3.2G
   CGroup: /system.slice/molochpcapread-selks.service
           ├─19661 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1
           └─19662 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/

Oct 14 20:31:44 suricata systemd[1]: Started Moloch Pcap Read.
scirius                          RUNNING   pid 20235, uptime 15:02:55
ii  elasticsearch                   7.7.0                        amd64        Distributed RESTful search engine built for the cloud
ii  elasticsearch-curator           5.8.1                        amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                          1:0.11.1                     amd64        no description given
ii  kibana                          7.7.0                        amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus        2020042401                   amd64        Kibana 6 dashboard templates.
ii  logstash                        1:7.7.0-1                    all          An extensible logging pipeline
ii  moloch                          2.2.3-1                      amd64        Moloch Full Packet System
ii  scirius                         3.5.0-3                      amd64        Django application to manage Suricata ruleset
ii  suricata                        1:2020050401-0stamus0        amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs   12G     0   12G   0% /dev
tmpfs          tmpfs     2.4G   17M  2.4G   1% /run
/dev/sda2      ext4      134G  7.9G  119G   7% /
tmpfs          tmpfs      12G     0   12G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      12G     0   12G   0% /sys/fs/cgroup
/dev/sdb1      ext4      672G  122G  517G  19% /var
tmpfs          tmpfs     2.4G     0  2.4G   0% /run/user/0

**Comment by ngms17** [comment]
If i run the dpkg command...

 dpkg -i moloch_2.2.3-1_amd64.deb
dpkg: error: cannot access archive 'moloch_2.2.3-1_amd64.deb': No such file or directory

**Comment by ngms17** [comment]
The result of apt update. Dpkg -i doesnt work as well

root@suricata:~# apt update
Ign:1 cdrom://[Debian GNU/Linux 10 _Buster_ - Official Snapshot amd64 LIVE/INSTALL Binary 20200603-01:03] buster InRelease
Err:2 cdrom://[Debian GNU/Linux 10 _Buster_ - Official Snapshot amd64 LIVE/INSTALL Binary 20200603-01:03] buster Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://files.evebox.org/evebox/debian stable InRelease
Hit:4 http://packages.stamus-networks.com/selks6/debian buster InRelease
Hit:5 http://packages.stamus-networks.com/selks6/debian-kernel buster InRelease
Hit:6 http://packages.stamus-networks.com/selks6/debian-test buster InRelease
Hit:7 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:8 https://packages.elastic.co/curator/5/debian9 stable InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 10 _Buster_ - Official Snapshot amd64 LIVE/INSTALL Binary 20200603-01:03] buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pevma** [comment]
Did the first time install/setup script pass ok ? There should be a log file under `/opt/`. It seems it is still reaching out to the CDROM for updates and it shouldn't after an install.
The upgrade should be done via the selks upgrade script (`selks-upgrade_stamus` command)

**Comment by ngms17** [comment]
I had to comment the deb cdrom lines.

![Capturar](https://user-images.githubusercontent.com/19928515/96369577-d1d01e80-1152-11eb-99f8-23161b6bbb80.PNG)

**Comment by ngms17** [comment]
I had to comment the deb cd rom lines.

![Capturar](https://user-images.githubusercontent.com/19928515/96369601-f0361a00-1152-11eb-8088-eb4dbcdf52e1.PNG)

**Comment by pevma** [comment]
Does it upgrade ok now ?

**Comment by ngms17** [comment]
Yup, it´s all ok. But i keep not receiving http and ssh information for exemple. If i enable http.log is always empty

**Comment by pevma** [comment]
Anything in the SN-HTTP dashboard?

**Comment by ngms17** [comment]
No, nothing

**Comment by ngms17** [comment]
![Screenshot 2020-10-18 at 16 25 05](https://user-images.githubusercontent.com/19928515/96372400-828feb00-115e-11eb-9cfb-883cdd4514b0.png)
![Screenshot 2020-10-18 at 16 24 57](https://user-images.githubusercontent.com/19928515/96372401-83288180-115e-11eb-96b0-e0996a95d003.png)
![Screenshot 2020-10-18 at 16 24 45](https://user-images.githubusercontent.com/19928515/96372402-8459ae80-115e-11eb-9a13-ee2e56ec6bf0.png)

**Comment by pevma** [comment]
Is there traffic on the sniffing interface ?

> -- 
> Regards,
> Peter Manev

**Comment by ngms17** [comment]
Yes, there is traffic on the sniffing interface

**Comment by pevma** [comment]
Ok
Do you have event type logs other than “stats” when you tail the eve.json ?


> -- 
> Regards,
> Peter Manev

**Comment by ngms17** [comment]
The eve.json only shows event_type: "flows"

**Comment by pevma** [comment]
Interesting - no stats ? Just event type flow ?
Hm .. do you mind sharing the output of (this is going to be long so maybe upload it as a file)
suricata —dump-config > suri.conf

> -- 
> Regards,
> Peter Manev

**Comment by ngms17** [comment]
Here it is. I removed my home_net values for safety reasons.
[suricata.txt](https://github.com/StamusNetworks/SELKS/files/5398053/suricata.txt)

**Comment by ngms17** [comment]
On eve box not a single event of the type http, ssh, tls and smb

**Comment by pevma** [comment]
It seems there is just no traffic? Is the traffic comming on the correct interface?

**Comment by ngms17** [comment]
I have traffic passing on the interface 

![Capturar](https://user-images.githubusercontent.com/19928515/96472800-c8b18100-1228-11eb-960d-fbe3ed002cd4.PNG)


Its a port mirror from a router interface

**Comment by ngms17** [comment]
And if i do a tcpdump on ports 80 and 443 the output is ok

**Comment by pevma** [comment]
what is th eoutput of 
`suricata --dump-config |grep enp2s0f1` ?

**Comment by ngms17** [comment]
Here it is

[selks.txt](https://github.com/StamusNetworks/SELKS/files/5409940/selks.txt)

**Comment by ngms17** [comment]
root@suricata:~# suricata --dump-config | grep enp2s0f1

af-packet.1.interface = enp2s0f1

**Comment by pevma** [comment]
It does not make sense to have only flow. It either means that maybe the protocol logging is not enabled or customized in a diff yaml.
You should have flow and stats records in that case?

**Comment by ngms17** [comment]
I finally figured out. I changed "vlan-use-for-tracking" to false and it worked. Although SSH, SMTP and SMB info are not being filled. HTTP and TLS are ok
