### ISSUE TITLE
Telegraf - Suricata

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#265]
Hello, 

Can we add 2 eve-log section?

I'm trying to add this

- eve-log:
    enabled: yes
    type: unix_stream
    filename: /var/run/suricata-stats.sock
    types:
      - stats:
         threads: yes

But it's not starting... i think suricata don't want 2 eve-log outpout right?

If yes, how to do it?

**Comment by pevma** [comment]
What is the error it gives?

**Comment by b4b857f6ee** [comment]
Nothing.
I'm on HardenedBSD, in OPNsense. I manage to start it by adding this one after the rest of the eve-log file but nothing.
I'm going to reply to this issue and don't flood the SELKS issue section sorry.
https://forum.opnsense.org/index.php?topic=16966.msg77206#msg77206
