### ISSUE TITLE
ES changes to Red after some days

### ISSUE THREAD

**Issue by ngms17** [StamusNetworks/SELKS#266]
After some days, ES changes it´s status to red. To resolve this, i simply clean up all databases with the script. But after some time, ES turns to red again.

The error is "shards failed: logstash_flow"

**Comment by pevma** [comment]
You might need shorter retention time or more Ram/disk ?
https://github.com/StamusNetworks/SELKS/wiki/Data-lifecycle

**Comment by ngms17** [comment]
I resolved thanks. Yet, i have another problem. After the 2 am suricata gives me an error od suricata.pid is stale

**Comment by pevma** [comment]
What is the output exactly ?

**Comment by ngms17** [comment]
suricata.pid exists but appears to be stale. It gives me this error after some hours of correct functioning.

**Comment by ngms17** [comment]
root@suricata:~# tail -f /var/log/suricata/suricata.log
1/11/2020 -- 02:03:08 - <Info> - Going to use 16 thread(s)
1/11/2020 -- 02:03:09 - <Info> - Running in live mode, activating unix socket
1/11/2020 -- 02:03:09 - <Info> - Using unix socket file '/var/run/suricata/suricata-command.socket'
1/11/2020 -- 02:03:09 - <Notice> - all 16 packet processing threads, 4 management threads initialized, engine started.
1/11/2020 -- 02:03:09 - <Info> - All AFP capture threads are running.
1/11/2020 -- 15:28:47 - <Notice> - This is Suricata version 6.0.0 RELEASE running in SYSTEM mode
1/11/2020 -- 15:28:47 - <Info> - CPUs/cores online: 16
1/11/2020 -- 15:28:47 - <Info> - Found an MTU of 1500 for 'enp2s0f1'
1/11/2020 -- 15:28:47 - <Info> - Found an MTU of 1500 for 'enp2s0f1'
1/11/2020 -- 15:28:47 - <Error> - [ERRCODE: SC_ERR_INITIALIZATION(45)] - pid file '/var/run/suricata.pid' exists but appears stale. Make sure Suricata is not running and then remove /var/run/suricata.pid. Aborting!

**Comment by pevma** [comment]
Can you try ` rm /var/run/suricata.pid` and then restart (as per the instructions)?

**Comment by ngms17** [comment]
Yes, it works if i do that. But after some time, it happens again
