### ISSUE TITLE
Capture filters (BPF) for Suricata

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#267]
Hi,

Does Scirius GUI have a way to set a capture rule exception for Suricata? I need to exclude an IP or range of IPs from Suricata traffic capture.

Thank you

**Comment by pevma** [comment]
You can pass the bpf on the command line or inside the config 
https://suricata.readthedocs.io/en/suricata-6.0.0/performance/ignoring-traffic.html

**Comment by ManuelFFF** [comment]
Hi @pevma ,

I already resolved my issue. In fact I used the same Suricata official documentation. I was just wondering if Scirius had that functionality implemented graphically or if there were plans to do so in the near future, if it doesn't already exist.

Thank you
