### ISSUE TITLE
Increase Disk Space

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/SELKS#268]
Hello,
I found strange your LVM configuration.

![image](https://user-images.githubusercontent.com/36012515/97605002-6a498700-1a0e-11eb-92fd-422f14ae5baf.png)

How i can proceed to increase it properly?

**Comment by pevma** [comment]
Hi,
Just as you would increase it normally for a LVM on a Debian.

**Comment by b4b857f6ee** [comment]
No, i never saw an Extended and a LVM in the same sectors with 2 /dev/sdaX ^^. How i have to deal with it? 
Thank's :)

**Comment by syst3** [comment]
Hello,
SELKS does not install by default on a LVM.
If you're trying to create a new LVM partition or migrate to LVM that's another story.

**Comment by b4b857f6ee** [comment]
> Hello,
> SELKS does not install by default on a LVM.
> If you're trying to create a new LVM partition or migrate to LVM that's another story.

Yes,. In this case i don't understand how to increase the size... Why i got a extended and a lvm partition on the same sector here...?

**Comment by syst3** [comment]
Use a live-cd partition tool like gparted and increase the partition. I don't understand how a LVM got there in the first place.

**Comment by b4b857f6ee** [comment]
Ok so it strange for you too :).

**Comment by syst3** [comment]
Maybe if you could elaborate how did you install it , is it a VM or HW and what you're trying to accomplish will "un"-strange it :)

**Comment by b4b857f6ee** [comment]
I just install the SELKS VM using the ISO that's all ^^. you don't have this?

**Comment by syst3** [comment]
Suggestion: Do a clean install. 
Are you using virtualbox ?

**Comment by b4b857f6ee** [comment]
Reinstall is not an answer to understand the problem ahah :p.
No esxi. But i will check later how to deal with this :)

**Comment by pevma** [comment]
Can you try on a diff VM to see if you have the same result?
This is what looks on one of my VMs
```
root@SELKS:~# df -lhT
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  4.8G     0  4.8G   0% /dev
tmpfs          tmpfs     981M   95M  887M  10% /run
/dev/sda1      ext4      530G   22G  482G   5% /
tmpfs          tmpfs     4.8G     0  4.8G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     4.8G     0  4.8G   0% /sys/fs/cgroup
tmpfs          tmpfs     981M     0  981M   0% /run/user/1000


...
root@SELKS:~# fdisk -l
Disk /dev/sda: 548.7 GiB, 589140852736 bytes, 1150665728 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8004df45

Device     Boot      Start        End    Sectors   Size Id Type
/dev/sda1  *          2048 1129687039 1129684992 538.7G 83 Linux
/dev/sda2       1129689086 1150664703   20975618    10G  5 Extended
/dev/sda5       1129689088 1150664703   20975616    10G 82 Linux swap / Solaris

```

**Comment by b4b857f6ee** [comment]
> 
> 
> Can you try on a diff VM to see if you have the same result?
> This is what looks on one of my VMs
> 
> ```
> root@SELKS:~# df -lhT
> Filesystem     Type      Size  Used Avail Use% Mounted on
> udev           devtmpfs  4.8G     0  4.8G   0% /dev
> tmpfs          tmpfs     981M   95M  887M  10% /run
> /dev/sda1      ext4      530G   22G  482G   5% /
> tmpfs          tmpfs     4.8G     0  4.8G   0% /dev/shm
> tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
> tmpfs          tmpfs     4.8G     0  4.8G   0% /sys/fs/cgroup
> tmpfs          tmpfs     981M     0  981M   0% /run/user/1000
> 
> 
> ...
> root@SELKS:~# fdisk -l
> Disk /dev/sda: 548.7 GiB, 589140852736 bytes, 1150665728 sectors
> Disk model: QEMU HARDDISK   
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: dos
> Disk identifier: 0x8004df45
> 
> Device     Boot      Start        End    Sectors   Size Id Type
> /dev/sda1  *          2048 1129687039 1129684992 538.7G 83 Linux
> /dev/sda2       1129689086 1150664703   20975618    10G  5 Extended
> /dev/sda5       1129689088 1150664703   20975616    10G 82 Linux swap / Solaris
> ```

Ok so you have the same like me. But i don't succeed to extend the hdd because like you you have
/dev/sda2       1129689086 1150664703   20975618    10G  5 Extended
/dev/sda5       1129689088 1150664703   20975616    10G 82 Linux swap / Solaris
With the same Start and End sectors.

**Comment by b4b857f6ee** [comment]
The solution : https://geekeries.org/2017/05/augmenter-la-taille-dun-disque-dur-sous-linux-avec-lvm/?cn-reloaded=1

**Comment by pevma** [comment]
Thank you for posting the solution.
