### ISSUE TITLE
selks reading only two NIC

### ISSUE THREAD

**Issue by yehias** [StamusNetworks/SELKS#27]
hey I tried to run suricata as IPS on my machine I have 3 nic so I want to use 2 nic as bridge and the 3rd as management port but selks read only two nic so I get it up using ifconfig eth2 up but seems eht2  not getting ip it's like a sniff port which will not let me do bridge mode because I want my traffic being monitored using suricata IPS from wan---->lan, and vice versa is there anyone can help me please thanks

**Comment by pevma** [comment]
Hi,
It seems your problem is related more to networking (creating a bridge interface?) than SELKS itself.
Is that correct?

**Comment by yehias** [comment]
I think so but it's related to selks since is a pre-built operating system

**Comment by pevma** [comment]
Then it is just regular Linux configuration for bridged interfaces - SELKS is actually based on Debian Jessie.

However if i understood correctly you want IPS mode - so traffic from one interface will be inspected and passed over to the other interface - correct?

**Comment by yehias** [comment]
Right and I can't find any clear tutorial can you help me

**Comment by pevma** [comment]
Ok - got it. Then you should follow a regular Suricata IPS set up with af_packet mode (default one in SELKS).
Yes - i need to put down a SELKS specific instruction - but you can use this guide form @regit which is very good - https://home.regit.org/2012/09/new-af_packet-ips-mode-in-suricata/

**Comment by yehias** [comment]
I followed it but eth1 and eth2 still not getting ip or  forward packets
while I setup a bridge between them and forward packets using iptables

**Comment by pevma** [comment]
I am not sure i understand you. AF_PACKET IPS mode is separate from the firewall stack - one packet is copied over from one interface to another so packets are not seen by the firewall stack (as discussed in the comments of the article as well btw)

**Comment by yehias** [comment]
So I deleted the bridge and edit suricata.yaml and still not working after
some of research it's seem an issue with the os itself not the suricata
because using ifconfig eht1 & eth2 are up but no ip assigned

**Comment by yehias** [comment]
thanks a lot! pevma it worked like charm! edit suricata.yaml and on af-packet: part delete everything and replace it with

af-packet:
  - interface: eth0
    threads: 1
    defrag: yes
    cluster-type: cluster_flow
    cluster-id: 98
    copy-mode: ips
    copy-iface: eth1
    buffer-size: 64535
    use-mmap: yes
  - interface: eth1
    threads: 1
    cluster-id: 97
    defrag: yes
    cluster-type: cluster_flow
    copy-mode: ips
    copy-iface: eth0
    buffer-size: 64535
    use-mmap: yes

and change interface name to your desired interface name, then restart suricata, and it will work like charm

even after that maybe you will face some issues during rules update just restart scirius using 
/etc/init.d/scirius restart
