### ISSUE TITLE
Why do i disable rules, but I can still see them in "Rules activity"

### ISSUE THREAD

**Issue by Product** [StamusNetworks/SELKS#272]
Why do i disable rules, but I can still see them in "Rules activity"

**Comment by pevma** [comment]
Did you update the ruleset (from the Suricata tab) ?

**Comment by Product** [comment]
when i update ruleset , the error occurred

Error during update: Can not fetch data: [Errno 1] Source "Suricata Traffic ID ruleset" update failed: Connection error 'HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jasonish/suricata-trafficid/master/rules/traffic-id.rules (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0bb6c1a2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))'

**Comment by Product** [comment]
> Did you update the ruleset (from the Suricata tab) ?

when i update ruleset , the error occurred

Error during update: Can not fetch data: [Errno 1] Source "Suricata Traffic ID ruleset" update failed: Connection error 'HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jasonish/suricata-trafficid/master/rules/traffic-id.rules (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0bb6c1a2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))'

**Comment by pevma** [comment]
It seems either there is no connection or the url is not correct.
Can you please share details of the rulesets that are enabled?
