### ISSUE TITLE
Evebox question

### ISSUE THREAD

**Issue by ngms17** [StamusNetworks/SELKS#274]
Hi!

My evebox is working fine except for one thing.

If i select the "Alerts" tab, it shows me all the alerts, but when i click on them it does not show any details about the alert.

However, if i go to "Events -> Alerts" it shows all the details about the alerts.

<img width="1677" alt="Screenshot 2020-11-20 at 15 08 32" src="https://user-images.githubusercontent.com/19928515/99815519-53e0a800-2b42-11eb-8c1c-83f921ae11b9.png">

**Comment by pevma** [comment]
What version is your ES ?

**Comment by ngms17** [comment]
Version 7.10.0. 

For example, if i escalate this exact same alert of the screenshot the details show up.

**Comment by jasonish** [comment]
It working for me on a fully up to date SELKS with Elastic 7.10.0.  I think it might be the web page choking on something in the event that is unexpected, which I suppose could occur based on your environment.  Can you see if there is anything in the web console?

On the included Firefox you can:
- Click on hamburger menu
- "Web Developer"
- "Web Console"

Then click around to get to this point again and see if any ugly errors are thrown?

**Comment by ngms17** [comment]
<img width="1680" alt="Screenshot 2020-11-20 at 16 35 54" src="https://user-images.githubusercontent.com/19928515/99825127-87c1ca80-2b4e-11eb-8ba8-a40a52e97055.png">

In this case it's safari

**Comment by jasonish** [comment]
Are you able to test quickly with Chrome and/or Firefox? I need to
determine if I hit a Safari quirk or something more general.  Can you also
include the EveBox version, from the terminal on SELKS type `evebox
version`. This does look familiar to something I fixed recently.

**Comment by ngms17** [comment]
Sure. Here it is.
<img width="1679" alt="Screenshot 2020-11-20 at 16 46 29" src="https://user-images.githubusercontent.com/19928515/99826324-1edb5200-2b50-11eb-99f9-b92cf87a2a50.png">
<img width="298" alt="Screenshot 2020-11-20 at 16 47 13" src="https://user-images.githubusercontent.com/19928515/99826342-23a00600-2b50-11eb-8ac2-2afa4205683f.png">

**Comment by jasonish** [comment]
I think I have a fix ready for the next release.  You can give it an early try if you like:
```
https://evebox.org/files/development/evebox-latest-amd64.deb
```
```
sudo dpkg -i evebox-latest-amd64.deb
```
When I release the final 0.13.0, apt should update to it from this dev release without issue.

**Comment by ngms17** [comment]
@jasonish 
![evebox](https://user-images.githubusercontent.com/19928515/99854528-e605a200-2b7c-11eb-8cf3-79dffe6c1fae.PNG)

Every time i open evebox on the browser my elasticsearch crashes

**Comment by jasonish** [comment]
Interesting. A query is causing it run out of memory.  How much memory does your machine have?

**Comment by ngms17** [comment]
For now I have an old machine with 24GB

**Comment by jasonish** [comment]
I'd think that would be plenty, but maybe not. I see my relatively quiet
Elastic process is using 22 some gigs of ram.

Do the Kibana Dashboards work?  The "Events" tab should be very very cheap
on Elasticsearch. If loading that is causing crashes there is something
more serious wrong.

The "Inbox", "Escalated" and "Alerts" tab are more expensive as they do
some aggregations which can burn up memory on the Elastic side.  However,
choosing a small time slice, like the last hour should be pretty easy on
it.  Choosing something like "All", or even "24 hours" can be too much for
some Elasticsearch installs depending on the number of events.

**Comment by ngms17** [comment]
All ok now!

I forgot to increase the elastic search heap space...

And now the alerts are showing the details! Thank you very much for the help provided
