### ISSUE TITLE
update-suricata error

### ISSUE THREAD

**Issue by cmiscloni** [StamusNetworks/SELKS#292]
Hi all,

I noted that Suricata rulesets  doesn't update anymore.
When i try to execute the command manually, i have this error below:

`/bin/su -s /bin/bash -c 'cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py updatesuricata && deactivate' www-data`

  ```
File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/suricata/management/commands/updatesuricata.py", line 29, in handle
    suricata = Suricata.objects.all()[0]
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

```

**Comment by pevma** [comment]
If you do it from the GUI - is there any difference ?

> -- 
> Regards,
> Peter Manev

**Comment by cmiscloni** [comment]
Yes, it works from GUI

**Comment by cmiscloni** [comment]
manage.py works with others options but not for update-suricata

**Comment by pevma** [comment]
There is an example of how the update should be done in /etc/crontab - is that working as expected from the command line ?

> -- 
> Regards,
> Peter Manev

**Comment by cmiscloni** [comment]
No same problem, only works with the GUI

**Comment by pevma** [comment]
```
root@SELKS:~# cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py updatesuricata && deactivate 
Successfully pushed ruleset to suricata "SELKS"
root@SELKS:/usr/share/python/scirius# 

```
i just tried on the cmd - it seems to work.
Do you run as root ?
The other thing maybe is - if there is something specific to a ruleset ? do you use custom or default ones ?

**Comment by cmiscloni** [comment]
I tried with root and www-data
I ‘m using the default one, just add some public pre defined rulesets
I test from scratch and i have the same behaviour, maybe a python update ?

**Comment by pevma** [comment]
Which scirius pkg version are you running ?(dpkg -l |grep scirius)

**Comment by cmiscloni** [comment]
3.5.0-3

**Comment by pevma** [comment]
Same here.
Anything custom you have installed maybe?

**Comment by cmiscloni** [comment]
HTOP package
Bnx2 firmware
python-pyldap
Django-auth-ldap : to allow ldap auth, I tried to revert back to check but same issue, maybe installation of python-ldap broken something ?

**Comment by pevma** [comment]
It looks like some pkg mixed up to be honest. Any config changes maybe ?

**Comment by cmiscloni** [comment]
Reinstall from scratch without install python ldap did the trick for me

**Comment by pevma** [comment]
So it is ldap it seems that triggered? 
We need to make sure we cover/look at that in our next release.

**Comment by pevma** [comment]
Thank you for the feedback!

**Comment by cmiscloni** [comment]
For me yes it’s ldap package because i have already tried to reinstall from scratch with iso on your website and after installed python-ldap package, exact same problem occured

**Comment by cmiscloni** [comment]
Thanks for your support
