### ISSUE TITLE
alerting on more than one rule

### ISSUE THREAD

**Issue by kdy1968** [StamusNetworks/SELKS#299]
will alerts be logged on more than one rule...i have a very broad geoip rule ..
i got hit by someone, and it triggered around 3000000 alerts in a couple hours..on my geoip rule...however it didnt trigger any other alerts..
if a packet/packets meets more than one rule are they all triggered...or just one...and is there order of priority on how he rules are processed..

**Comment by pevma** [comment]
You should not use very broad rules for that purpose. If you have to  - then I suggest you use thresholding inside the rule

https://suricata.readthedocs.io/en/latest/rules/thresholding.html?highlight=Threshold

> -- 
> Regards,
> Peter Manev

**Comment by kdy1968** [comment]
thanks, i was looking into that..threshold..
if i have a rule that alerts on a packet from RU
someone from RU attempts connection to my machine ...that persons ip is in the iprep list..thers is a rule that shoiuld drop the packet..

would  both rules be matched and packet dropped

**Comment by kdy1968** [comment]
i found it.....
action-order: 
 - pass
 - drop
 - reject
 - alert
