### ISSUE TITLE
Scirius doesn't start

### ISSUE THREAD

**Issue by Leolrus** [StamusNetworks/SELKS#303]
hi, after update and restart server scirius web ui doesn't start.  `selks-health-check_stamus` all green. Kibana works properly, i just can't manage the ruleset.

**Comment by pevma** [comment]
Do you get an err logging in or ? 
Can you please post the result of the health check ?
Thank you 

> -- 
> Regards,
> Peter Manev

**Comment by Leolrus** [comment]
> Do you get an err logging in or ? Can you please post the result of the health check ? Thank you
> […](#)
> -- Regards, Peter Manev On 2 Apr 2021, at 11:44, Leolrus ***@***.***> wrote: ﻿ hi, after update and restart server scirius web ui doesn't start. selks-health-check_stamus all green. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

● suricata.service - LSB: Next Generation IDS/IPS
   Loaded: loaded (/etc/init.d/suricata; generated)
   Active: active (running) since Fri 2021-04-02 11:23:56 MSK; 2h 27min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10611 ExecStart=/etc/init.d/suricata start (code=exited, status=0/SUCCESS)
    Tasks: 30 (limit: 9830)
   Memory: 4.2G
   CGroup: /system.slice/suricata.service
           └─10619 /usr/bin/suricata -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid --af-packet -D -v --user=logstash
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 11:23:46 MSK; 2h 27min ago
     Docs: https://www.elastic.co
 Main PID: 10131 (java)
    Tasks: 200 (limit: 9830)
   Memory: 13.8G
   CGroup: /system.slice/elasticsearch.service
           ├─10131 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -D…
           └─10364 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 09:56:42 MSK; 3h 55min ago
 Main PID: 746 (java)
    Tasks: 101 (limit: 9830)
   Memory: 1.4G
   CGroup: /system.slice/logstash.service
           └─746 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.he…
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 11:23:46 MSK; 2h 27min ago
     Docs: https://www.elastic.co
 Main PID: 10461 (node)
    Tasks: 11 (limit: 9830)
   Memory: 239.6M
   CGroup: /system.slice/kibana.service
           └─10461 /usr/share/kibana/bin/../node/bin/node /usr/share/kibana/bin/../src/cli/dist --logging.dest=/var/log/kibana/kibana.log --pid.file=/run/kibana/kibana.pid
● evebox.service - EveBox Server
   Loaded: loaded (/lib/systemd/system/evebox.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 09:56:42 MSK; 3h 55min ago
 Main PID: 735 (evebox)
    Tasks: 25 (limit: 9830)
   Memory: 5.6M
   CGroup: /system.slice/evebox.service
           └─735 /usr/bin/evebox server
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 11:23:51 MSK; 2h 27min ago
 Main PID: 10573 (sh)
    Tasks: 12 (limit: 9830)
   Memory: 49.5M
   CGroup: /system.slice/molochviewer-selks.service
           ├─10573 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1
           └─10574 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 11:23:51 MSK; 2h 27min ago
 Main PID: 10569 (sh)
    Tasks: 5 (limit: 9830)
   Memory: 283.9M
   CGroup: /system.slice/molochpcapread-selks.service
           ├─10569 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/  >> /data/moloch/logs/capture.log 2>&1
           └─10571 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/
● fast2mikrotik.service - PHP Daemon Service
   Loaded: loaded (/etc/systemd/system/fast2mikrotik.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-02 09:56:42 MSK; 3h 55min ago
 Main PID: 738 (php)
    Tasks: 1 (limit: 9830)
   Memory: 13.3M
   CGroup: /system.slice/fast2mikrotik.service
           └─738 /usr/bin/php -f /usr/local/bin/fast2mikrotik.php > /dev/null 2>/dev/n$
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
ii  elasticsearch                         7.12.0                                amd64        Distributed RESTful search engine built for the cloud
ii  elasticsearch-curator                 5.8.3                                 amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                                1:0.13.0                              amd64        no description given
ii  kibana                                7.12.0                                amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus              2020122001                            amd64        Kibana 6 dashboard templates.
ii  logstash                              1:7.12.0-1                            amd64        An extensible logging pipeline
ii  moloch                                2.7.1-1                               amd64        Moloch Full Packet System
ii  scirius                               3.7.0-1                               amd64        Django application to manage Suricata ruleset
ii  suricata                              1:2021030201-0stamus0                 amd64        Suricata open source multi-thread IDS/IPS/NSM system.
Файловая система Тип      Размер Использовано  Дост Использовано% Cмонтировано в
udev             devtmpfs    12G            0   12G            0% /dev
tmpfs            tmpfs      2,4G         9,8M  2,4G            1% /run
/dev/sda2        ext4       3,6T          62G  3,4T            2% /
tmpfs            tmpfs       12G          16M   12G            1% /dev/shm
tmpfs            tmpfs      5,0M            0  5,0M            0% /run/lock
tmpfs            tmpfs       12G            0   12G            0% /sys/fs/cgroup
tmpfs            tmpfs      2,4G          12K  2,4G            1% /run/user/1000
tmpfs            tmpfs      2,4G         4,0K  2,4G            1% /run/user/115

**Comment by pevma** [comment]
I see something with permission denied right under the mikrotik php service ... 

> -- 
> Regards,
> Peter Manev

**Comment by Leolrus** [comment]
> I see something with permission denied right under the mikrotik php service ...
This service was added in script by me and it was not correlate with scirius (the service is for uploading fast.log to mikrotik by api and this is all)
