### ISSUE TITLE
no connection to dashboards via Scirius 

### ISSUE THREAD

**Issue by admiralmor** [StamusNetworks/SELKS#304]
Hello everyone ! I can't connect to dashbords through the Scirius interface, that is, if I go to the upper right corner, select the dashboards tab there, then I will be redirected to https: // selks / app / home, but there is a white page waiting for me
At the same time, if I connect to localhost: 5601, then everything is successful, I get access to dashboards, editing them, and so on.
I would still like to get access through Scirius, how can I fix the problem?

**Comment by pevma** [comment]
Hi,

Is that SELKS or custom Scirius installation  ?

If SELKS did the first time setup complete successfully 

https://github.com/StamusNetworks/SELKS/wiki/First-time-setup
?


What is the output of the “selks-health-check-stamus” ?


> -- 
> Regards,
> Peter Manev

**Comment by admiralmor** [comment]
This is SELKS 
`systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: en
   Active: active (running) since Sat 2021-04-03 13:06:39 MSK; 1h 18min ago
     Docs: man:nginx(8)
  Process: 949 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process o
  Process: 1028 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code
 Main PID: 1029 (nginx)
    Tasks: 5 (limit: 14338)
   Memory: 32.5M
   CGroup: /system.slice/nginx.service
           ├─1029 nginx: master process /usr/sbin/nginx -g daemon on; master_pro
           ├─1030 nginx: worker process
           ├─1031 nginx: worker process
           ├─1032 nginx: worker process
           └─1033 nginx: worker process

апр 03 13:06:37 SELKS systemd[1]: Starting A high performance web server and a r
апр 03 13:06:39 SELKS systemd[1]: Started A high performance web server and a re
root@SELKS:/etc/nginx/sites-available# nano selks6.conf 
root@SELKS:/etc/nginx/sites-available# selks-health-check_stamus 
● suricata.service - LSB: Next Generation IDS/IPS
   Loaded: loaded (/etc/init.d/suricata; generated)
   Active: active (running) since Sat 2021-04-03 13:16:37 MSK; 1h 19min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2274 ExecStart=/etc/init.d/suricata start (code=exited, status=0/SUCCESS)
    Tasks: 10 (limit: 14338)
   Memory: 400.5M
   CGroup: /system.slice/suricata.service
           └─2282 /usr/bin/suricata -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid --af-packet -D -v --u…

апр 03 13:16:37 SELKS systemd[1]: Starting LSB: Next Generation IDS/IPS...
апр 03 13:16:37 SELKS suricata[2274]: Starting suricata in IDS (af-packet) mode... done.
апр 03 13:16:37 SELKS systemd[1]: Started LSB: Next Generation IDS/IPS.
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:07:33 MSK; 1h 28min ago
     Docs: https://www.elastic.co
 Main PID: 1001 (java)
    Tasks: 96 (limit: 14338)
   Memory: 6.7G
   CGroup: /system.slice/elasticsearch.service
           ├─1001 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddres…
           └─1335 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

апр 03 13:06:38 SELKS systemd[1]: Starting Elasticsearch...
апр 03 13:07:33 SELKS systemd[1]: Started Elasticsearch.
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:06:35 MSK; 1h 29min ago
 Main PID: 894 (java)
    Tasks: 41 (limit: 14338)
   Memory: 968.1M
   CGroup: /system.slice/logstash.service
           └─894 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFracti…

апр 03 13:08:15 SELKS logstash[894]: [2021-04-03T13:08:15,828][INFO ][logstash.outputs.elasticsearch][main] Attemptin…
апр 03 13:08:15 SELKS logstash[894]: [2021-04-03T13:08:15,904][INFO ][logstash.outputs.elasticsearch][main] I…logstash
апр 03 13:08:16 SELKS logstash[894]: [2021-04-03T13:08:16,601][INFO ][logstash.filters.geoip   ][main] Using …y.mmdb"}
апр 03 13:08:17 SELKS logstash[894]: [2021-04-03T13:08:17,482][INFO ][logstash.filters.geoip   ][main] Using …y.mmdb"}
апр 03 13:08:17 SELKS logstash[894]: [2021-04-03T13:08:17,731][INFO ][logstash.javapipeline    ][main] Starting pipel…
апр 03 13:08:20 SELKS logstash[894]: [2021-04-03T13:08:20,702][INFO ][logstash.javapipeline    ][main] Pipeli…"=>2.96}
апр 03 13:08:21 SELKS logstash[894]: [2021-04-03T13:08:21,317][INFO ][logstash.javapipeline    ][main] Pipeli…>"main"}
апр 03 13:08:21 SELKS logstash[894]: [2021-04-03T13:08:21,428][INFO ][logstash.agent           ] Pipelines ru…nes=>[]}
апр 03 13:08:21 SELKS logstash[894]: [2021-04-03T13:08:21,460][INFO ][filewatch.observingtail  ][main][d4aef1…lections
апр 03 13:08:22 SELKS logstash[894]: [2021-04-03T13:08:22,033][INFO ][logstash.agent           ] Successfully…t=>9600}
Hint: Some lines were ellipsized, use -l to show in full.
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:06:38 MSK; 1h 29min ago
     Docs: https://www.elastic.co
 Main PID: 1002 (node)
    Tasks: 11 (limit: 14338)
   Memory: 320.8M
   CGroup: /system.slice/kibana.service
           └─1002 /usr/share/kibana/bin/../node/bin/node /usr/share/kibana/bin/../src/cli/dist --logging.dest=/var/log/k…

апр 03 13:06:38 SELKS systemd[1]: Started Kibana.
● evebox.service - EveBox Server
   Loaded: loaded (/lib/systemd/system/evebox.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:06:35 MSK; 1h 29min ago
 Main PID: 865 (evebox)
    Tasks: 5 (limit: 14338)
   Memory: 17.6M
   CGroup: /system.slice/evebox.service
           └─865 /usr/bin/evebox server

апр 03 13:06:35 SELKS systemd[1]: Started EveBox Server.
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36   INFO evebox::version: This is EveBox version 0.12.0 …nux-musl
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36   INFO evebox::server::main: Using temporary in-memory…database
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36   INFO evebox::sqlite::configrepo: Initializing SQLite database
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36   INFO evebox::sqlite::configrepo: Updating SQLite dat…ersion 1
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36  ERROR evebox::server::main: Failed to get Elasticsear…ror 111)
апр 03 13:06:36 SELKS evebox[865]: 2021-04-03 13:06:36   INFO evebox::server::main: Starting server on 127.0.…ls=false
Hint: Some lines were ellipsized, use -l to show in full.
● molochviewer-selks.service - Moloch Viewer
   Loaded: loaded (/etc/systemd/system/molochviewer-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:08:32 MSK; 1h 27min ago
 Main PID: 2033 (sh)
    Tasks: 12 (limit: 14338)
   Memory: 46.2M
   CGroup: /system.slice/molochviewer-selks.service
           ├─2033 /bin/sh -c /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.…
           └─2034 /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini

апр 03 13:08:32 SELKS systemd[1]: Started Moloch Viewer.
● molochpcapread-selks.service - Moloch Pcap Read
   Loaded: loaded (/etc/systemd/system/molochpcapread-selks.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-04-03 13:08:06 MSK; 1h 28min ago
 Main PID: 1737 (sh)
    Tasks: 5 (limit: 14338)
   Memory: 214.3M
   CGroup: /system.slice/molochpcapread-selks.service
           ├─1737 /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/  >> /dat…
           └─1738 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -m -s -R /data/nsm/

апр 03 13:08:06 SELKS systemd[1]: Stopped Moloch Pcap Read.
апр 03 13:08:06 SELKS systemd[1]: Started Moloch Pcap Read.
scirius                          RUNNING   pid 1099, uptime 1:29:41
ii  elasticsearch                         7.11.2                              amd64        Distributed RESTful search engine built for the cloud
ii  elasticsearch-curator                 5.8.3                               amd64        Have indices in Elasticsearch? This is the tool for you!\n\nLike a museum curator manages the exhibits and collections on display, \nElasticsearch Curator helps you curate, or manage your indices.
ii  evebox                                1:0.12.0                            amd64        no description given
ii  kibana                                7.11.2                              amd64        Explore and visualize your Elasticsearch data
ii  kibana-dashboards-stamus              2020122001                          amd64        Kibana 6 dashboard templates.
ii  logstash                              1:7.11.2-1                          amd64        An extensible logging pipeline
ii  moloch                                2.7.1-1                             amd64        Moloch Full Packet System
ii  scirius                               3.5.0-3                             amd64        Django application to manage Suricata ruleset
ii  suricata                              1:2021030201-0stamus0               amd64        Suricata open source multi-thread IDS/IPS/NSM system.`

**Comment by admiralmor** [comment]
first setup completes successfully

**Comment by admiralmor** [comment]
![изображение](https://user-images.githubusercontent.com/50439418/113473097-23096b80-9470-11eb-81a2-1fd7ad4c7395.png)

**Comment by pevma** [comment]
Did you log in to Scirius before ?

https://your.selks.IP.here/
?(example https://192.168.2.5)


> -- 
> Regards,
> Peter Manev

**Comment by admiralmor** [comment]
> 
> Did you log in to Scirius before ? https://your.selks.IP.here/ ?(example https://192.168.2.5)
> […](#)
> -- Regards, Peter Manev On 3 Apr 2021, at 10:31, admiralmor ***@***.***> wrote: ﻿ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, I used to have access

**Comment by pevma** [comment]
Can you try a different browser?

**Comment by admiralmor** [comment]
> Can you try a different browser?

tried google chrome, everything is also a white tap
Maybe the problem is in the nginx proxy?

**Comment by pevma** [comment]
hm, did you make any changes there? 
Please check -  https://github.com/StamusNetworks/SELKS/wiki/Kibana-did-not-load-properly

**Comment by admiralmor** [comment]
> hm, did you make any changes there?

no, I have not edited config files

**Comment by pevma** [comment]
Does the nginx config look the same as in the docs ?

> -- 
> Regards,
> Peter Manev

**Comment by admiralmor** [comment]
> Does the nginx config look the same as in the docs ?
> […](#)
> -- Regards, Peter Manev On 3 Apr 2021, at 12:17, admiralmor ***@***.***> wrote: ﻿ hm, did you make any changes there? no, I have not edited config files — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I checked two nginx configuration files, and found that for some reason it was different for me (I did not edit it) and after I completely copied the config from the documentation, it worked for me! Thanks for the help!!!

**Comment by pevma** [comment]
Glad to help!
