### ISSUE TITLE
Suricata listening on multiple interfaces

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#306]
Hi,

Notes: 
- Using SELKS 6 + ELK 7.11.2
- Suricata in IDS mode

We have the need to add a USB Ethernet adapter to our server, so Suricata can listen traffic from the local net and also from a mirrored port, which will be bringing traffic from other sub-nets. 

1. Will Suricata be able to handle multiple Ethernet interfaces while configured for IDS mode?
2. If the above is possible, can you please assist on what/where modifications will be needed to do on SELKS suite? I think affected configs will be Suricata and Moloch.

If you need more details, please let me know.

Thank you

**Comment by pevma** [comment]
Yes sure , you can just use/run the setup interface script (`selks-setup-ids-interface`)

**Comment by ManuelFFF** [comment]
Will this script allow me to use both Ethernet interfaces (local and USB), or will just allow me to switch to a new Ethernet interface?

**Comment by ManuelFFF** [comment]
**Update:**

- Confirmed script allows to add multiple network interfaces
- Confirmed new config block was added to `/etc/suricata/selks6-interfaces-config.yaml` for the new network interface, so the file includes both interfaces

I also updated this line under `/data/moloch/etc/config.ini`. The second interface below a wifi card on a test machine

```
# Semicolon ';' seperated list of interfaces to listen on for traffic
interface=enp2s0;wlp3s0
```

**Question:** Do I need to run script `selks-setup-ids-interface` AND manually add the 2nd interface to Moloch's config file, or running the script will be enough? Or how Moloch will detect/use the 2nd interface?

**Comment by pevma** [comment]
The Moloch part should be added manually for now yes.

**Comment by ManuelFFF** [comment]
I think it would be a good idea to include Moloch config modification in the script `selks-setup-ids-interface` for future versioons.
Thank you!

**Comment by pevma** [comment]
Yes sure - please feel free to open a feature request ticket.
Thank you !
