### ISSUE TITLE
PCAP recipe for optimizing disk usage?

### ISSUE THREAD

**Issue by wicknet** [StamusNetworks/SELKS#315]
Despite 500Gb assigned to the SELKS VM, available space shrank to less than 10% in 12 hours of usage. Using FCP_Retain (Option 2) with 30 min rotation and 10Gb max file size. Most of the data usage appears to be localised in /data/moloch/raw/

Have read the documentation re. difference between different pcap options as well as optimizing disk usage but it seemed confusing.

Currently using using cron to run selks-db-logs-cleanup_stamus every 3 hours but wondering if there is a better/recommended way to ensure disk space is not overwhelmed due to a faulty setup? For a 500Gb drive, what would you recommend as ideal capture type, max file size and rotation timing options?

THANKS!

**Comment by pevma** [comment]
If you are planing on doing a full packet capture , you can find a very good disk size calculator here - 
https://arkime.com/estimators

**Comment by wicknet** [comment]
Thank you!
