### ISSUE TITLE
Desktop Environment Corrupted after dist-upgrade

### ISSUE THREAD

**Issue by yehias** [StamusNetworks/SELKS#32]
I got desktop environment corrupted after dist-upgrade and what I see that selks run LXDE so when I tried to login with the user it's just lof me off directly while I can login through CLI and using root I can run through GUI and CLI, and when I tried to acess user settings just stay loading and not working any suggestions? thanks.

**Comment by pevma** [comment]
Strange.
There is nothing SELKS specific in the desktop environment - it is a regular Debian Jessie with LXDE.
What exactly is the corruption? You can log in with root but not with the selks-user?

**Comment by yehias** [comment]
sorry for late reply the issue can be resolved through chown -R youruser:yourgroup /home/youruser
