### ISSUE TITLE
Problem in the First Time Setup

### ISSUE THREAD

**Issue by mohamedislem97** [StamusNetworks/SELKS#321]
Hello ,I just installed Selks6  and when i want do the first time setup in vm machine , this prblm showed up 

<div class="nH if" style="margin: 0px 16px 0px 0px; padding: 0px;"><div class="nH aHU" style="position: relative;"><div class="nH hx" style="background-color: transparent; color: rgb(34, 34, 34); min-width: 502px; padding: 0px;"><div class="nH" jslog="20686; u014N:xr6bB" role="list"><div class="h7 ie nH oy8Mbf" role="listitem" tabindex="-1" style="clear: both; padding-bottom: 0px; max-width: 100000px; outline: none;"><div class="Bk" style="position: relative; margin-bottom: 0px; border-width: 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(239, 239, 239); border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: initial; border-radius: 0px; float: none !important; width: 1191.2px;"><div class="G3 G2" style="padding-top: 0px; background-color: transparent; border-right: 0px; border-bottom: 0px rgba(100, 121, 143, 0.12); border-left: 0px; border-image: initial; border-top: none; border-radius: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px;"><div><div id=":nu"><div class="adn ads" data-message-id="#msg-f:1702458960633935402" data-legacy-message-id="17a059679944362a" style="border-left: none; padding: 0px; display: flex;"><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1119.2px;"><div class=""><div id=":nr" class="ii gt" style="font-size: 0.875rem; direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative;"><div id=":ns" class="a3s aiL " style="overflow: hidden; font: small / 1.5 Arial, Helvetica, sans-serif;"><div dir="auto"><div dir="auto">Please supply a network interface(s) to set up SELKS Suricata IUPS thread detection on</div><div dir="auto"><br></div><div dir="auto">0: ens33</div><div dir="auto"><br></div><div dir="auto">1: lo Please type in interface or space delimited interfaces below and hit "Enter", Example: ethl</div><div dir="auto"><br></div><div dir="auto">OR Example: ethl eth2 eth3</div><div dir="auto"><br></div><div dir="auto">Configure threat detection for INTERFACE(S): ens33</div><div dir="auto"><br></div><div dir="auto">The supplied network interface(s): ens33</div><div dir="auto"><br></div><div dir="auto">DONE!</div><div dir="auto"><br></div><div dir="auto">FPC Full Packet Capture. Suricata will rotate and delete the pcap captured files. FPC Retain- Full Packet Capture with having Moloch's pcap retention/rotation. Keeps th e pcaps as long as there is space available. None- disable packet capture</div><div dir="auto"><br></div><div dir="auto">1)-FPC</div><div dir="auto"><br></div><div dir="auto">2) FPC Retain</div><div dir="auto"><br></div><div dir="auto">3) NONE Please choose an option. Type in a number and hit "Enter" 1 Enable Full Pcacket Capture</div><div dir="auto"><br></div><div dir="auto">### Starting Moloch DB set up ###</div><div dir="auto"><div dir="auto"><br></div><div dir="auto"><br></div><div dir="auto">&amp; Total</div><div dir="auto"><br></div><div dir="auto">Received Xferd Average Speed Time Time</div><div dir="auto"><br></div><div dir="auto">Dload Upload Total</div><div dir="auto"><br></div><div dir="auto">Spent</div><div dir="auto"><br></div><div dir="auto">0 0 0</div><div dir="auto"><br></div><div dir="auto">0</div><div dir="auto"><br></div><div dir="auto">0</div><div dir="auto"><br></div><div dir="auto">Failed to connect to localhost port 9200: Connexion refusée</div><div dir="auto"><br></div><div dir="auto">Traceback (most recent call last): File "bin/manage.py", line 10, in &lt;module&gt;</div><div dir="auto"><br></div><div dir="auto">execute_from_command_line (sys.argv)</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/django/core/managem ent/ init.py", line 364, in execute_from_command line</div><div dir="auto"><br></div><div dir="auto">utility.execute()</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/django/core/managem</div><div dir="auto"><br></div><div dir="auto">ent/ init .py", line 356, in execute</div><div dir="auto"><br></div><div dir="auto">self.fetch_command (subcommand).run_from_argv(<wbr>self.argv)</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/django/core/managem</div><div dir="auto"><br></div><div dir="auto">ent/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options)</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/django/core/managem ent/base.py", line 330, in execute</div><div dir="auto"><br></div><div dir="auto">output self.handle(*args, **options)</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/rules/management/co mmands/kibana_reset.py", line 38, in handle</div><div dir="auto"><br></div><div dir="auto">self.kibana reset()</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/rules/es data.py", line 1972, in kibana reset</div><div dir="auto"><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/elasticsearch/clien t/indices.py", line 268, in exists return self.transport.perform request("HEAD", make path(index), params-params)</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/elasticsearch/trans port.py", line 358, in perform request</div><div dir="auto"><br></div><div dir="auto">timeout-timeout,</div><div dir="auto"><br></div><div dir="auto">File "/usr/share/python/scirius/<wbr>local/lib/python2.7/site-<wbr>packages/elasticsearch/conne ction/http_urllib3.py", line 224, in perform request raise ConnectionError("N/A", str(e), e)</div><div dir="auto"><br></div><div dir="auto">elasticsearch.exceptions.<wbr>ConnectionError: ConnectionError(&lt;urllib3.<wbr>connection.HTTPConne ction object at 0x7f42856ac6d0&gt;: Failed to establish a new connection: [Errno 111] Conn ection refused) caused by: NewConnectionError(&lt;urllib3.<wbr>connection.HTTPConnection object at 0x7f42856ac6d0&gt;: Failed to establish a new connection: [Errno 111] Connection refus ed)</div><div dir="auto"><br></div><div dir="auto">Dashboards Loading set up job failed...Exiting... ### Exited with ERROR ###</div><div dir="auto"><br></div><div dir="auto">FINISH of first time setup script dimanche 13 juin 2021, 15:08:40 (UTC+0200)</div><div dir="auto"><br></div><div dir="auto">Exited with FAILED</div><div dir="auto"><br></div><div dir="auto">Full log located at /opt/selks/log/selks-first-<wbr>time-setup_stamus.log Press enter to continue</div></div></div></div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: transparent;"><div class="gB xu" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":nq">
&nbsp; | RépondreTransférer
-- | --

</div></div></div></div></div></div></div></div></div></div><div class="nH"></div><div class="nH"></div></div></div><div class="nH"><div class="l2 pfiaof" role="contentinfo" style="margin: 0px 0px 16px; padding: 0px 16px 0px 72px; text-align: center; text-shadow: none; visibility: hidden;"><div id=":mk" class="aeV" style="float: left; width: 367.362px; text-align: left;"><div><div class="ajd" style="display: flex;"><a target="_blank" href="https://drive.google.com/u/0/settings/storage?hl=fr&amp;utm_medium=web&amp;utm_source=gmail&amp;utm_campaign=storage_meter&amp;utm_content=storage_normal" class="aiF" style="text-decoration: none; width: 220px;"><div class="aiC" jslog="108909; u014N:cOuCgd,Kr2w4b,xr6bB; 40:WzFd" style="background-color: rgb(218, 220, 224); border-radius: 8px; height: 6px; margin: 7px 0px;"><div class="aiA" style="background-color: rgb(95, 99, 104); border-radius: 8px; height: 6px; width: 6.6px;"></div></div><div class="aiG" jslog="108910; u014N:cOuCgd,Kr2w4b,xr6bB; 40:WzFd" style="align-items: center; display: flex;"><div class="aiD " style="-webkit-font-smoothing: auto; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: 0.75rem; letter-spacing: 0.3px; color: rgb(95, 99, 104); font-weight: normal; text-decoration: none; text-shadow: none;"><span dir="ltr"></span><span dir="ltr"></span></div><div class="aiz" role="img" aria-label="Cliquez sur le lien pour gérer l'espace de stockage" style="background-image: url(&quot;https://www.gstatic.com/images/icons/material/system_gm/1x/launch_gm_grey_18dp.png&quot;); background-size: 18px; height: 20px; width: 20px; margin: 0px 8px; opacity: 1;"></div></div></a></div></div></div><div class="aeU" style="float: left; width: 367.362px;"><div id=":ml"><div><div class="ma" style="font-size: 0.75rem; color: rgb(95, 99, 104); padding-top: 0px; text-shadow: none; -webkit-font-smoothing: auto; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.3px; line-height: 20px;"><a href="https://www.google.com/intl/fr/policies/terms/" target="_blank" class="l9" style="color: rgb(34, 34, 34); text-decoration: none; text-shadow: none;"></a><a href="https://www.google.com/intl/fr/policies/privacy/" target="_blank" class="l9" style="color: rgb(34, 34, 34); text-decoration: none; text-shadow: none;"></a><a href="https://www.google.com/gmail/about/policy/" target="_blank" class="l9" style="color: rgb(34, 34, 34); text-decoration: none; text-shadow: none;"></a></div></div></div></div><div id=":mn" class="ae3" style="float: left; width: 367.362px; text-align: right;"><div><div class="l6" style="padding-top: 0px; font-size: 0.75rem; color: rgb(95, 99, 104); -webkit-font-smoothing: auto; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.3px; line-height: 20px; text-shadow: none;"><div></div><span id=":o5" class="l8 LJOhwe" tabindex="0" role="link" style="color: rgb(34, 34, 34); text-decoration: none; cursor: pointer; text-shadow: none;"></span></div></div></div><div style="clear: both;"></div></div></div></div><div class="Bt" style="height: 0px; overflow: hidden; width: 0px;"></div><div class="nH" style="width: 0px;"><div class="no" style="float: left;"><div class="nH nn" style="min-height: 1px; float: left; width: 0px;"><div style="height: 64ex;"></div></div></div><div class="dJ" style="height: 0px; overflow: hidden; clear: both;"></div></div><div class="Bt" style="height: 0px; overflow: hidden; width: 647px; color: rgb(32, 33, 36); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div class="nH bno adC" role="complementary" style="right: 32px; top: 0px; width: 0px; margin: 0px; color: rgb(32, 33, 36); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute;"><div class="nH"></div></div><br class="Apple-interchange-newline">

**Comment by timguyuk** [comment]
Im having the same issue. Ive downloaded the desktop and non desktop iso.

I am running it on a VM on hyperv 2016, I have 4 processors assigned and 10Gb memory. I just cant get past that error.

Tim

**Comment by pevma** [comment]
Seems the issue is that Es i snot up yet
```
Failed to establish a new connection: [Errno 111] Conn ection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f42856ac6d0>: Failed to establish a new connection: [Errno 111] Connection refus ed)
```
Can you also please check that the minimum CPU/RAM resources are in place - https://github.com/StamusNetworks/SELKS/wiki/First-time-setup

**Comment by timguyuk** [comment]
Recommendation is 2VCPU and 8Gb ram, Im running 4VCPU and 10Gb. Hyperv, I am running Gen one not Gen Two

**Comment by pevma** [comment]
Ok perfect.
If you rerun the first time setup again?

**Comment by timguyuk** [comment]
ok,. I'm further forward, I have completed selks-first-time-setup_stamus by logging in as root, selks-user was the problem.

**Comment by pevma** [comment]
Glad you are moving forward! I updated the docs to be more clear.
