### ISSUE TITLE
Error when updating source in Suricata Management tab

### ISSUE THREAD

**Issue by absentrecall** [StamusNetworks/SELKS#326]
I get the following error when I manually update rulesets in the Suricata Management tab.

> Error during update: no such table: my_cache_table

Looking back at cron logs, it looks like the nightly cron job for updating the rules also ran into the same problem.  The following error is in the cron logs:

> Unable to update ruleset for suricata "SELKS": no such table: my_cache_table

According to the cron logs, this error began the day after I updated scirius to 3.7.0-2 and ran into the problem described in Issue #323 (https://github.com/StamusNetworks/SELKS/issues/323).  perma's instructions fixed the broken scirius update.  I think this my_cache_table issue may be related to the previous scirius update issue but I'm not sure.

How do I restore the ability to update suricata rulesets?

**Comment by zentavr** [comment]
Running this helped:
```
. /usr/share/python/scirius/bin/activate
cd /usr/share/python/scirius/bin

python3 manage.py createcachetable
```

**Comment by absentrecall** [comment]
Thanks for the suggestion.  I get a file permission error when I issue the python3 command from the selks-user account:

> (scirius) selks-user@selks:/usr/share/python/scirius/bin$ python3 manage.py createcachetable
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/logging/config.py", line 562, in configure
>     handler = self.configure_handler(handlers[name])
>   File "/usr/lib/python3.7/logging/config.py", line 735, in configure_handler
>     result = factory(**kwargs)
>   File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> PermissionError: [Errno 13] Permission denied: '/var/log/scirius/elasticsearch.log'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
>     django.setup()
>   File "/usr/share/python/scirius/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
>     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
>   File "/usr/share/python/scirius/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
>     logging_config_func(logging_settings)
>   File "/usr/lib/python3.7/logging/config.py", line 799, in dictConfig
>     dictConfigClass(config).configure()
>   File "/usr/lib/python3.7/logging/config.py", line 570, in configure
>     '%r' % name) from e
> ValueError: Unable to configure handler 'elasticsearch'
> (scirius) selks-user@selks:/usr/share/python/scirius/bin$
> 
> 

The permission error is because the /var/log/scirius/elasticsearch.log  file is rw only for www-data user.

Should I run the python3 command with sudo? 

Thanks very much for your help!

**Comment by pevma** [comment]
Yes, try it out ?

**Comment by absentrecall** [comment]
Using sudo, I get the following error:

> selks-user@selks:~$ . /usr/share/python/scirius/bin/activate
> (scirius) selks-user@selks:~$ cd /usr/share/python/scirius/bin
> (scirius) selks-user@selks:/usr/share/python/scirius/bin$ sudo python3 manage.py createcachetable
> [sudo] password for selks-user:
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ModuleNotFoundError: No module named 'django'
> (scirius) selks-user@selks:/usr/share/python/scirius/bin$
> 
> 

Suggestions?

**Comment by pevma** [comment]
Can you try doing 
```
source bin/activate
```
than followed by the command ?

**Comment by absentrecall** [comment]
I think the reason sudo python3 manage.py createcachetable did not work is because the bin/activate occurred in the selks-user environment and not the root environment in the sudo.  I think that's what @pevma is saying as well.  To have both the bin/activate and the python3 manage.py commands run in the same environment, I probably need to go into root before all of the commands. 

My only concern is that running these commands as root will mess up more file permissions that I would not know how to restore. Is there any risk of that?  If there is risk, I would rather take a backup of the machine before proceeding. 

What's your thoughts on the risk?

**Comment by absentrecall** [comment]
I executed the commands as root and it appears to have worked.  I can now update rulesets again.  Will have to check in the morning to see if tonight's automatic ruleset update works as well. 

Thanks for everyone's help!
