### ISSUE TITLE
syslog increasing too crazy!

### ISSUE THREAD

**Issue by yehias** [StamusNetworks/SELKS#33]
hey syslog, kern.log, and messages increasing in insane way 400GB filled into couple of hourse! I just checked them and what I saw same message which's
kernel :device eth2 left promiscuous mode
kernel : device eth2 enter promiscuous mode
till hard disk is full

**Comment by pevma** [comment]
I think then you need to find out what causes the eth2 leaving and entering so often the mode.

**Comment by yehias** [comment]
I just to know if suricata involved since this mode related to the packet
capture and sniffing thanks in advance

**Comment by pevma** [comment]
Ok.
It should not - but you can do a test to confirm. Stop Suricata and if the logging continues - then it is not Suri related I suppose.

**Comment by yehias** [comment]
Nope not suricata issue already stopped it it's weird everything happened
after distro upgrade

**Comment by yehias** [comment]
Issue been solved by getting down lo interface loopback is that an issue?
Thanks

**Comment by pevma** [comment]
It should not be.

**Comment by pevma** [comment]
It seems outdated atm for both Debian and SELKS.
We will reopen if needed/related.
