### ISSUE TITLE
Cyberchef not accessible

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/SELKS#333]
Hello!
I have a fresh installation of SELKS 6 which is fully upgraded by _selks-upgrade_stamus_. But I can not open Cyberchef if click in image in right corner. I get the error from nginx that URL ..../static/cyberchef/ not found. How to fix the problem?

**Comment by pevma** [comment]
This is actually enabled/disabled in the `/etc/scirius/local_settings.py` 
as a variable
```
USE_CYBERCHEF = True
CYBERCHEF_URL = '/static/cyberchef/'
```
so if you install it (in `/var/www/scirius/static/cyberchef`) there it will become available.
The installation sould be simple enough , basically download fomr here https://github.com/gchq/CyberChef/releases/
and untar in the folder above.

**Comment by VN1977** [comment]
yes, everything works.

**Comment by pevma** [comment]
Thanks for the feedback - i have setup a small wiki here
https://github.com/StamusNetworks/SELKS/wiki/Enable-CyberChef
