### ISSUE TITLE
Using proxy for Scirius

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/SELKS#335]
In order to update sources I need using proxy. Do these settings work in file **local_settings.py**?
```
USE_PROXY = False
PROXY_PARAMS = {'http': "http://proxy:3128", 'https': "http://proxy:3128"}
```
My scirius is 3.7.0. and I have allready tried to use them but didn't have any success. When I try to update sources I don't see anything in scirius logs. I see only red warning window saying 
`
Can not fetch data: [Errno 3] Source "ETOpen Ruleset" update failed: Connection error 'HTTPSConnectionPool(host='rules.emergingthreats.net', port=443): Max retries exceeded with url: /open/suricata-5.0/version.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e87eb8978>: Failed to establish a new connection: [Errno 111] Connection refused'))' Source "SSLBL abuse.ch" update failed: Connection error 'HTTPSConnectionPool(host='sslbl.abuse.ch', port=443): Max retries exceeded with url: /blacklist/sslblacklist_tls_cert.rules (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8b3980f0>: Failed to establish a new connection: [Errno 111] Connection refused'))' Source "Suricata Traffic ID ruleset" update failed: Connection error 'HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jasonish/suricata-trafficid/master/rules/traffic-id.rules (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8b398630>: Failed to establish a new connection: [Errno 111] Connection refused'))'
`
And I don't see any packets which are sent to my proxy to port 3128.

**Comment by pevma** [comment]
Did you try ``USE_PROXY = True`` ?

**Comment by VN1977** [comment]
Yes, sure.

**Comment by pevma** [comment]
Should probably - add it in via the GUI
![Screenshot from 2021-09-06 15-08-24](https://user-images.githubusercontent.com/1405917/132222548-b80447c3-35b1-40fb-91f8-e9a04632ad9c.png)

**Comment by VN1977** [comment]
yea, it works.
