### ISSUE TITLE
What should be done with SECRET_KEY in /etc/scirius/local_settings.py

### ISSUE THREAD

**Issue by cwwade** [StamusNetworks/SELKS#344]
The Django settings for Scirius appear to be found in the /etc/scirius/local_settings.py. This file includes the SECRET_KEY that is presumably used for various signing and data protection functions in Django operations. However, every SELKS installation uses the same random string, and there is no documentation (that I can find) that provides guidance on changing this value to a unique random string for each installation. The comments included in the local_settings.py file certainly imply that this SECRET_KEY should be changed.

It is possible that the actual secret used by Django is located elsewhere, and is already initialized to be unique. Alternatively, it might be that features that rely on the SECRET_KEY value are not used by Scirius. On the other hand, it is just as likely that this is an important security setting for Scirius that should be changed to something unique and random.

It would be much appreciated if some guidance could be provided for what to do with this SECRET_KEY.

**Comment by pevma** [comment]
Forgot to update - this is fixed in SELKS docker version for some time now.
