### ISSUE TITLE
No fast.log, no alerts!

### ISSUE THREAD

**Issue by Linn1** [StamusNetworks/SELKS#345]
I have been used the SELKS6.0 about half a year. Recently  I checked the dir `/var/log/suricata` and found there is no fast.log in this dir. I don't know why and I tried to restart suricata. But it still didn't work. No fast.log,no alerts! It is sooooo terrible!
Help!

**Comment by pevma** [comment]
SELKS does not use legacy `fast.log` (it has always been disabled by default). It uses default Suricata `eve.json` log output.

**Comment by Linn1** [comment]
So that's why I can't see any alerts in event viewer?
I choose the event lab and it shows different colors. But when I choose the alert lab, it doesn't show any thing.
If I want to use the `fast.log`, what should I do?
I want to  collect the different `fast.log`  in different devices. So I can use one device to to monitor the traffic of other network segments.
Thanks for your reply!

**Comment by pevma** [comment]
Did you complete successfully the first time set up procedure ?
https://github.com/StamusNetworks/SELKS/wiki/First-time-setup

**Comment by Linn1** [comment]
Yes， I tried many times  and I am sure that I complete successfully the first time set up procedure.
But there is no `fast.log`.

**Comment by pevma** [comment]
Its explicitly disabled as it is legacy.     
eve.json is the one that should be used.
You can if course enable the fast log again form the selks6 yaml config if that is a must.

**Comment by Linn1** [comment]
Thanks sooooo much!  The `fast.log` appears！
