### ISSUE TITLE
SMTP events not created in eve.json

### ISSUE THREAD

**Issue by dblazquezl** [StamusNetworks/SELKS#346]
Hi, I am using the latest docker deployment in my fw and everything looks to be ok.
```
# suricata -V       
This is Suricata version 7.0.0-dev (416575ea0 2021-10-22)
```

Just I am not having any smtp event, and no elastic index created for smtp. I have a mail server behind the fw and I should have some logs.
I already have http logs, which is the same scenario than smtp, I mean a server behind the fw with same port forward config 

I checked the eve.json file and no smtp event are shown:
```
# cat eve.json | grep '"event_type":"smtp"'

# 
```
In my config I test a lot of different combinations, but even the simplest one is not logging smtp events.
This is my current selks6.yaml config related to smtp. (using the official git repo one)

```
outputs:
  - eve-log:
      types:
       - smtp:
            #extended: yes # enable this for extended logging information
            custom: [received, x-mailer, x-originating-ip, relays, reply-to, bcc,
            reply-to, bcc, message-id, subject, x-mailer, user-agent, received,
            x-originating-ip, in-reply-to, references, importance, priority,
            sensitivity, organization, content-md5, date]
            md5: [body, subject]
app-layer:
  protocols:
    smtp:
      enabled: yes
      mime:
        decode-mime: yes
        decode-base64: yes
        decode-quoted-printable: yes
        header-value-depth: 2000
        extract-urls: yes
        body-md5: no
      inspected-tracker:
        content-limit: 100000
        content-inspect-min-size: 32768
        content-inspect-window: 4096
    imap:
      enabled: detection-only

```

I cannot see any error message in the suricata logs.
Any ideas?

Thanks

**Comment by pevma** [comment]
Do you see traffic from that mail server - aka if you tcpdump on the interface , would you see the traffic you expect being mirrored from that server?

**Comment by dblazquezl** [comment]
Hi, yes, I see smtp packages but they are in the tls, or flow category, not in the smtp. 
The fours first messages is me doing a telnet to the port 25,
The latest just a real mail arriving
![Screenshot from 2021-11-03 18-27-51](https://user-images.githubusercontent.com/31306132/140161977-dd544f6f-fd51-4942-8d14-145d64e8c969.png)

**Comment by pevma** [comment]
Hmm , is it possible part of the traffic is missing ? I see some Anomaly messages?

**Comment by dblazquezl** [comment]
Hi.
I don't think so. Suricata is running on the fw. It is in IPS mode. All the traffic from the INPUT, FORWARD and OUTPUT in the FW  is going to suricata, no mirror port
Also if I look for smtp in Evebox events, I can find a lot of them, but always in other Event Types, like Flow, Anomaly or TLS, but the SMTP Event Type is not there, Is not in the Evebox Filter, The elastic index does not exits...
The HTTP(S) server is running in the same machine as the mail server, And the redirect rule is the same, And I have a HTTP elastic index with a lot of entries of HTTP Event Type. I really think is suricata not setting that packets as smtp event type, but I am not an expert and probably I am wrong.

**Comment by dblazquezl** [comment]
I found this, look like the smtp protocol is not supported in my build?
```
suricata --list-app-layer-protos
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:278) <Info> (ConfYamlParse) -- Including configuration file selks6-addin.yaml.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'reputation-categories-file' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'default-reputation-path' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'reputation-files' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'default-rule-path' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'rule-files' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'threshold-file' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'detect' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'default-log-dir' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'stats' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'outputs' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'logging' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'app-layer' redefined.
[51] 7/11/2021 -- 21:15:06 - (conf-yaml-loader.c:302) <Info> (ConfYamlParse) -- Configuration node 'asn1-max-frames' redefined.
=========Supported App Layer Protocols=========
http
ftp
smtp
tls
ssh
imap
smb
dcerpc
dns
modbus
enip
dnp3
nfs
ntp
ftp-data
tftp
ike
krb5
dhcp
snmp
sip
rfb
mqtt
rdp
http2
```

**Comment by pevma** [comment]
The fact that the SMTP events are not find-able in Es means it is not seeing or not seeing the complete SMTP traffic.  
If you tcpdump smtp only  on the interface, save the pcap file and open it wit Wireshark - would it be "clean/regular" - aka full sessions with 3WHS etc?

**Comment by dblazquezl** [comment]
Hi, thanks for your response.
I captured some packages in a pcap file, and open it with wireshark, but being honest I don't know how to check it is clean/regular" - aka full sessions with 3WHS.
The last package is colored in red, I guess something related with the sequence number?
This is how it looks
![Screenshot from 2021-11-08 22-14-35](https://user-images.githubusercontent.com/31306132/140819823-baedb010-3529-43e4-81e0-147300070571.png)

**Comment by dblazquezl** [comment]
I also deployed a mail container in the fw with the same config, sent and received some mails,  and have same behavior, no elastic index created for smtp.
Maybe related to use port 587 (mail submission agent) and not only 25. Also POP and IMAP are provided just by secure ports 993 and 995 and not by standard ones

**Comment by pevma** [comment]
I think it seems good. We need to find out why it is not showing up though.
Is it possible to privately share a pcap for investigation ?

**Comment by dblazquezl** [comment]
Hi, I sent you a mail.
Thanks

**Comment by pevma** [comment]
Thank you for sharing the pcap privately. What I see is basically Suricata highlighting that there is only one side of the traffic:
```
{
  "app_proto": "smtp",
  "type": "applayer",
  "event": "APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION",
  "layer": "proto_detect"
}

``` 

So it seems the mirror is not complete.

**Comment by dblazquezl** [comment]
Hi, Thanks you.
I can read this is expected for smtp trafik:

6.29.2.1.3. applayer_detect_protocol_only_one_direction
Protocol detection only succeeded in one direction. For FTP and SMTP this is expected.

https://suricata.readthedocs.io/en/suricata-6.0.0/rules/app-layer.html.

I cannot understand how is possible just one side of the traffic is logged when suricata is running in the fw, and all the traffic from iptables INPUT, OUTPUT and FORWARD are redirected to suricata NFQueue. This traffic should be in the FORWARD queue, it does not have other way to return to internet

**Comment by pevma** [comment]
Apologies - you are correct about the pattern/traffic , i did not look complete to me at first. As it is encrypted (and the starttls), seemed normal but there is SMTP info that we can still log.
There is a fix under way and the issue is doc-ed here -  https://redmine.openinfosecfoundation.org/issues/4817 
I will update Suricata as soon as it is in.

**Comment by dblazquezl** [comment]
Thanks a lot!

**Comment by dblazquezl** [comment]
Hi @pevma.
Just updated to the latest master version and smtp elastic index is created.
I have no alerts, just events, but I will check that.

Thanks a lot!

**Comment by pevma** [comment]
No problem!
