### ISSUE TITLE
Scirius did not show any data on Suricata

### ISSUE THREAD

**Issue by naimhusin** [StamusNetworks/SELKS#35]
Hi, I am using Selks 2.1, right now I had some difficulties to view data on Scirius. 

I can view data in Kibana, but the Scirius did not show any data about Suricata (Alert Activity, Rules Activity, Capture Stats, Memory Usage, Problem indicators)

Hopefully someone can help pointing out what I am missing. Thanks.

**Comment by pevma** [comment]
If this is the first time at start up - it will take some time (a few minutes ) for the graph to populate.
If not - can you please try changing the time span - 24hr or something and see if any diff?

**Comment by naimhusin** [comment]
Hi, I don't see any different. The sensor has been running for around 12 hours now. Is there any way to check scirius is fetching the suricata's data?

**Comment by regit** [comment]
Did you change the hostname ? this is a case where you can loose the link. To get back the data you need to go to Suricata -> Edit to sync the name.

**Comment by naimhusin** [comment]
It works, thank you! Yes I changed the hostname.
