### ISSUE TITLE
Django error after upgrading

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#36]
Hi,

I just did a apt-get update/upgrade, the last upgrade I did before that was in November 2015.
Everything seems to have worked, it did tell me I had to upgrade my DB which I accepted.
But now, if I go to any URL I get the following error:
(rebooting does not solve the problem)

ImproperlyConfigured at /accounts/login/

Error importing module django.template.context_processors: "No module named context_processors"

Request Method: 	GET
Request URL: 	https://selks/accounts/login/
Django Version: 	1.6.6
Exception Type: 	ImproperlyConfigured
Exception Value: 	

Error importing module django.template.context_processors: "No module named context_processors"

Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py in import_module, line 40
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/opt/selks/scirius',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']

Server time: 	Sat, 30 Jan 2016 17:49:21 +0000

**Comment by b-u-g-s** [comment]
I can confirm there is an upgrade problem as I have the same issue on another SELKS box.
Now... I paid attention when the scirius upgrade was taking place and the DB was being upgraded here is what I think the problem is:
-----------------------------
Setting up scirius (1.1.5-1) ...
Installing new version of config file /etc/nginx/sites-available/stamus.conf ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf
creating database backup in /var/cache/dbconfig-common/backups/scirius_1.1.2-1.sqlite3.
applying upgrade script for 1.1.2-1 -> 1.1.5-1.
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.messages
 > django.contrib.staticfiles
 > django_tables2
 > bootstrap3
 > south

**Not synced (use migrations):
 - rules
 - suricata
 - accounts
(use ./manage.py migrate to migrate these)**
Running migrations for rules:
- Nothing to migrate.
 - Loading initial data for rules.
Installed 0 object(s) from 0 fixture(s)
Running migrations for suricata:
- Nothing to migrate.
 - Loading initial data for suricata.
Installed 0 object(s) from 0 fixture(s)
Running migrations for accounts:
- Nothing to migrate.
 - Loading initial data for accounts.
Installed 0 object(s) from 0 fixture(s)
/
--------------------------

It looks like the error is because Rules/Suricata/accounts haven't been synced and need to be migrated using ./manage.py

So I am assuming this is referring to /opt/selks/scirius/manage.py

But with what kind of parameters??
startmigration?

**Comment by pevma** [comment]
@b-u-g-s  - i tried to reproduce your issue and could not. What was your upgrade command?

**Comment by b-u-g-s** [comment]
apt-get update
apt-get upgrade

done that from a plain SELKS distribution.
last time I ran those commands was in November 2015.

Is there any command I can run to complete the migration?

**Comment by pevma** [comment]
you should do -
> apt-get update && apt-get dist-upgrade

I think @regit  can help out with the exact command to complete the migration...
you can always  try to reinstall/remove/install the package - but please try on a test system first.

**Comment by b-u-g-s** [comment]
it didn't make any difference to use dist-upgrade instead.
Ok will wait for @regit to give me the magic command :)

Will also try to reinstall the package...
The scirius package right?
Thanks.

**Comment by pevma** [comment]
yes - you can simply do- 
> apt-get remove scirius

choose "no" to purging the DB (second question i think) so that you keep your settings and then 

> apt-get install scirius

**Comment by pevma** [comment]
btw @b-u-g-s  - which Scirius version were you upgrading from?

**Comment by b-u-g-s** [comment]
This is what I could see in the install messages:

creating database backup in /var/cache/dbconfig-common/backups/scirius_1.1.2-1.sqlite3.
applying upgrade script for 1.1.2-1 -> 1.1.5-1.
Syncing...

Looks like upgrading from scirius 1.1.2.1

Will try the manual package install in a couple of hours.

**Comment by b-u-g-s** [comment]
The apt-get remove scirius
and
apt-get install scirius

did not solve the problem...

**Comment by pevma** [comment]
Did  you purge the DB ?

**Comment by b-u-g-s** [comment]
I didn't. I mean when I reinstalled scirius it asked me if I wanted to reconfigure the DB and I said no (I thought it was what you suggested).

**Comment by pevma** [comment]
strange - I cant reproduce your case - including upgrades from 1.1.2-1 -> 1.1.5-1 and 1.1.1-1 -> 1.1.5-1

**Comment by b-u-g-s** [comment]
I did change the default login for Scirius to something different than selks-users by the way...
and I did change the password for Selks-users at the OS level (but kept that userid for the OS).

**Comment by b-u-g-s** [comment]
also, I am monitoring on eth10 not eth0, so have a slightly different suricata.yaml
but I did accept the new suricata.yaml file when upgrading.

Maybe @regit will be able to provide a command to manually do the migration of the DB...

**Comment by b-u-g-s** [comment]
It may not migrate accounts if one uses a different userid than selks-users ?

**Comment by regit** [comment]
Looks like django is too old.  1.6.6 may not have a feature recently used in scirius. @b-u-g-s are you using the wheezy based SELKS ?

**Comment by b-u-g-s** [comment]
Hi @regit 
I am using the latest version of SELKS (or so I think!), SELKS 2?
lsb_release -a gives me:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

**Comment by pevma** [comment]
Was just discussing with @regit about this..... - it seems 
> Django Version: 1.6.6
is wrong ...Jessie comes with 1.7.7 so a 
> apt-get update && apt-get dist-upgrade 
should in theory upgrade the Django to that level. @b-u-g-s  - Could you have  a look and see why has it not done so?

**Comment by b-u-g-s** [comment]
Right... So I used SELKS 2.0 image and back in July, the SELKS Debian Jessie had Django 1.6.6
I even registered a problem related to that version on github below:
https://github.com/StamusNetworks/scirius/issues/40

July seems very faaaaaar away...
I am pretty certain (but not completely) that at least on one of the 2 VM I have this issue I did a fresh SELKS 2.0 install and did not upgrade to Django 1.8 and then back to 1.6 (which maybe could have screwed your django upgrade path)

Anyway... I see 2 options:
1. Upgrading Django manually using similar instructions in the issue ticket referenced above but this time upgrade to 1.7.7 (got that version from: https://packages.debian.org/jessie/python-django)

Problem: I think it might just be a temporary fix as it doesn't explain why the upgrade from 1.6.6 didn't happened in the first place and if the SELKS distribution upgrades Django again it might not work in the future


2. Fresh install...
I am now downloading SELKS 2.1 and will reinstall from scratch on at least one of the VM

Problem: have to reconfigure everything... doh!

Anyway... will wait a few days but then will close this issue.
Looks like I might be the only one with this issue so probably not worth spending too much time troubleshooting... must be the gremlins I fed last night.
B.

**Comment by regit** [comment]
Only thing I see possible in the upgrade process leading to current state is that `apt-get upgrade` was not enough and `dist-upgrade` was needed.

**Comment by b-u-g-s** [comment]
@regit you could be right... I always do this:
apt-get update
apt-get upgrade
apt-get dist-upgrade

in that order... 
So here is the latest attempt I did to fix this issue:
- Restore to a working SELKS 
- update manually django to 1.7.7 using the following command:
pip install django==1.7.7
- apt-get update
- apt-get dist-upgrade

still have the same issue...
the gremlins have won... reinstalling from SELKS 2.1!

**Comment by b-u-g-s** [comment]
by the way, the upgrade process seems to have worked better though! as per the logs:
http://pastebin.com/XGCG8hzb

but well... the end result was still an error!

**Comment by yehias** [comment]
Try to do ap-get update && apt-get upgrade && apt-get dist-upgrade then when finish restart scirius I was facing same issue then update suricata from scirius gui

**Comment by b-u-g-s** [comment]
Thanks @yehias but this did not help either. Am now about to reinstall from SELKS 2.1 !

**Comment by pevma** [comment]
@b-u-g-s  -  I think your case was similar - 
https://github.com/StamusNetworks/SELKS/issues/37

**Comment by b-u-g-s** [comment]
Almost... there seems to be progress following the instructions in that other thread, but now I am getting a 502 Bad Getaway
After full reboot...
restarting nginx
tried to restart scirius and I get the following error:
Job for scirius.service failed. See 'systemctl status scirius.service' and 'journalctl -xn' for details.

If I run that command I get:
systemctl status scirius.service
● scirius.service - LSB: Start FastCGI servers with Django.
   Loaded: loaded (/etc/init.d/scirius)
   Active: failed (Result: exit-code) since Tue 2016-02-09 23:39:22 GMT; 15s ago
  Process: 2406 ExecStart=/etc/init.d/scirius start (code=exited, status=1/FAILURE)

Feb 09 23:39:22 BSE-S scirius[2406]: File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
Feb 09 23:39:22 BSE-S scirius[2406]: from .base import library, BoundColumn, BoundColumns, Column
Feb 09 23:39:22 BSE-S scirius[2406]: File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 12, in <module>
Feb 09 23:39:22 BSE-S scirius[2406]: from django_tables2.utils import A, AttributeDict, OrderBy, OrderByTuple
Feb 09 23:39:22 BSE-S scirius[2406]: File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 109, in <module>
Feb 09 23:39:22 BSE-S scirius[2406]: @six.python_2_unicode_compatible
Feb 09 23:39:22 BSE-S scirius[2406]: AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
Feb 09 23:39:22 BSE-S systemd[1]: scirius.service: control process exited, code=exited status=1
Feb 09 23:39:22 BSE-S systemd[1]: Failed to start LSB: Start FastCGI servers with Django..
Feb 09 23:39:22 BSE-S systemd[1]: Unit scirius.service entered failed state.

Any idea?

**Comment by pevma** [comment]
hmmm
What is the output of -

>  python -c "import django; print(django.get_version())"
?

**Comment by b-u-g-s** [comment]
1.8.7

**Comment by pevma** [comment]
It seems it is specific to - django_tables2 in this case. @regit any ideas?

**Comment by regit** [comment]
That looks like the six problem. Try to do 'pip install --upgrade six'. It should fix this problem.

**Comment by b-u-g-s** [comment]
Unfortunately even after running that command I am getting the same error on the Web Portal...
