### ISSUE TITLE
ImproperlyConfigured at /rules/

### ISSUE THREAD

**Issue by JeffreyRoberson** [StamusNetworks/SELKS#37]
I upgraded the server using apt-get update && apt-get upgrade.  After the upgrade, I'm receiving this message on the web console:

ImproperlyConfigured at /rules/
Error importing module django.template.context_processors: "No module named context_processors"
Request Method:	GET
Request URL:	https://cohids.hutchgov.com/rules/
Django Version:	1.6.6
Exception Type:	ImproperlyConfigured
Exception Value:	
Error importing module django.template.context_processors: "No module named context_processors"
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py in import_module, line 40
Python Executable:	/usr/bin/python
Python Version:	2.7.10
Python Path:	
['/opt/selks/scirius',
 '/usr/lib/python2.7/site-packages',
 '/',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']
Server time:	Tue, 9 Feb 2016 20:54:49 +0000
Traceback Switch to copy-and-paste view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/opt/selks/scirius/rules/views.py in index
    return scirius_render(request, 'rules/index.html', context) ...
▶ Local vars
/opt/selks/scirius/scirius/utils.py in scirius_render
    return render(request, template, context) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py in render
        context_instance = RequestContext(request, current_app=current_app) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/template/context.py in __init__
        for processor in get_standard_processors() + processors: ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/template/context.py in get_standard_processors
            func = import_by_path(path) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py in import_by_path
                    sys.exc_info()[2]) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py in import_by_path
        module = import_module(module_path) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py in import_module
        __import__(name) ...
▶ Local vars
Request information

I've posted the complete error over at Pastebin: http://pastebin.com/NycXUeGD

**Comment by yehias** [comment]
Restart scirius service

**Comment by JeffreyRoberson** [comment]
It's giving that error after a full reboot of the server.  Is there a misconfiguration in one of my config files?

**Comment by pevma** [comment]
What is the output of - 
> python -c "import django; print(django.get_version())"

Thanks

**Comment by JeffreyRoberson** [comment]
1.6.6

**Comment by pevma** [comment]
Can you try - 
> pip install --upgrade django==1.8.7 django-tables2 South GitPython pyinotify flup six

then restart Scirius and let us know how it goes?

**Comment by JeffreyRoberson** [comment]
That fixed it!  Thank you!
