### ISSUE TITLE
Suricata Update Rules Error

### ISSUE THREAD

**Issue by svgdrch** [StamusNetworks/SELKS#38]
Can someone please help me out with this please?

OperationalError at /suricata/

no such column: rules_rule.state_in_source

Request Method: 	GET
Request URL: 	https://192.168.6.27/suricata/
Django Version: 	1.8.7
Exception Type: 	OperationalError
Exception Value: 	

no such column: rules_rule.state_in_source

Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/opt/selks/scirius',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']

Server time: 	Mon, 29 Feb 2016 18:46:57 +0000

---------------Traceback-----------------------------

Environment:

Request Method: GET
Request URL: https://192.168.6.27/suricata/

Django Version: 1.8.7
Python Version: 2.7.9
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_tables2',
 'bootstrap3',
 'rules',
 'suricata',
 'accounts',
 'revproxy')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'scirius.loginrequired.LoginRequiredMiddleware',
 'scirius.utils.TimezoneMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/selks/scirius/suricata/views.py" in index
  58.             supp_rules = list(suri.ruleset.suppressed_rules.all())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in __iter__
  162.         self._fetch_all()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
  965.             self._result_cache = list(self.iterator())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  238.         results = compiler.execute_sql()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  840.             cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py" in __exit__
  98.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py" in execute
  318.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /suricata/
Exception Value: no such column: rules_rule.state_in_source

**Comment by regit** [comment]
Hello, it seems a migration is missing. Can you try to run:
```
cd /opt/selks/scirius/
python manage.py makemigrations
python manage.py migrate
```

**Comment by svgdrch** [comment]
That worked perfectly, thank you for your help!
