### ISSUE TITLE
SELKS6 ISO without desktop🐞💿

### ISSUE THREAD

**Issue by nyukers** [StamusNetworks/SELKS#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to use SELKS6 ISO via VirtualBox. It's starting ok.

### Expected Behavior

Sorry, but I can't find any preinstalled Suricata dashboards in Kibana. No one. Where they are?

**Comment by pevma** [comment]
Thank you for your posting.
Did you go through the first time setup ok 
https://github.com/StamusNetworks/SELKS/wiki/First-time-setup
?

**Comment by nyukers** [comment]
System settings (from the Stamus logo drop down menu in the left upper corner) -> Kibana ->(Reset SN dashboards) Reset.
Done. Thanks.
