### ISSUE TITLE
🐞💿 <FirstTimeSetup went wrong!>

### ISSUE THREAD

**Issue by Linn1** [StamusNetworks/SELKS#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to run 
```
cd /opt/selksd/SELKS/docker/ && \
./easy-setup.sh --non-interactive --no-pull-containers -i tppdummy0 \
--iA --restart-mode always --es-memory 8G && \
docker-compose up -d
``` 
 and there is a error : 
```
Pulling cron (docker : latest) ...
Error : Get ”https://registry-1.docker.io/v2/" : dial tcp : lookup registry-1.docker.io : no such host
```
I run it offline and I can't make the PC get into internet. What should I do?
Thanks for your patience for reading my question.

### Expected Behavior

I hope that error can be fixed with offline status.

### Anything else?

If I want check the health of suricata/elasticsearch/logstash, which command should I use?
Which command is same as "selks-health-check_stamus" in selks6.0?

**Comment by pevma** [comment]
What host OS are you running ?

**Comment by Linn1** [comment]
The host OS is debian 11 which SELKS7.0 contains. I just download the ISO and start installer it on pc. 
Now I tried to make device connect into internet, I solved this problem. Thanks for your reply.
By the way,I want to export the alert log from suricata container. I don't know how the containers communicate.
If I want to export the fast.log from the suricata container, what should I do?

**Comment by Linn1** [comment]
I enabled the fast.log and there is a file named "fast.log" in container-data. 
I know how to export the log. Sorry for asking the stupid question!

**Comment by pevma** [comment]
You should probably consider using the JSON formated log (`eve.json`) as fast.log is extremely limited in terms of useful data for alerts - and also being retired.

**Comment by Linn1** [comment]
But eve.json is too big and exporting it will occupy  a lot of bandwidth.

**Comment by pevma** [comment]
something to have in mind is that `"event_type":"alerts"` offer more content and metadata than old type `fast.log`

**Comment by Linn1** [comment]
Thanks for your  reminder！
