### ISSUE TITLE
Update elasticsearch and logstash packages to the 2.x branches

### ISSUE THREAD

**Issue by SleuthKid** [StamusNetworks/SELKS#41]
For various security updates in elasticsearch and logstash since the 1.x major release the repositories configured in staging/etc/apt/sources.list.d/elasticsearch.list should be updated if there are no breaking changes in the frontend packages for scirius or other depending software in SELKS.

**Comment by regit** [comment]
This is work in progress, we should have a beta of SELKS with update ELK stack that should be available in the coming weeks. Regarding breaking changes, there is a lot of them. Upgrading to 2.x is killing almost everything in the chain.
