### ISSUE TITLE
🐞🐋 <Suricata have no rules!>

### ISSUE THREAD

**Issue by Linn1** [StamusNetworks/SELKS#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use the SELKS7.0 and start the docker-compose.
But I found there is no rules of suricata. 
I didn't change any setup of the suricata docker container.
I download a lot suricata rules from internet.
But I don't know how to import these rules and import the rules to which dir.

### Docker version

Docker versin 20.10.14, build a224086

### Docker version

docker-compose version 1.29.2, build 5beacea4c

### OS Version

Debian GUN/Linux 11 (bullseye)

### Content of the environnement File

COMPOSE_PROJECT_NAME=SELKS
INTERFACES= -i enp33s0f1
ELASTIC_MEMORY=8G
SCIRIUS_SECRET_KEY=-RUp4Ti68G1fysETgffySaqCktEck6zSgqONDAFEzk24

### Version of SELKS

commit 2aa150e9004efa84c4747a1da69c036c9147959 ( HEAD -> master, origin/master. origin/HEAD)
Author: Peter Manev <petermanev@gmail.com>
Date: Mon Apr 4 21:42:27 2022 +0200

    doc: Update landing wiki page

### Anything else?

I want to konw why there is no rules in suricata container.

**Comment by pevma** [comment]
Did you update the ruleset?
In Scirius , Suricata tab -> click `Ruleset actions` (left hand side panel) -> select `Update,Build, Push` -> click on `Apply`

**Comment by Matt-M-ironnet** [comment]
I am seeing similar issues. Suricata is being reported as up and green, but no ruleset. There is indeed a ruleset present, albeit small. Every time I attempt to `update, build, push`, I'm getting a "Server Error (500)". 

![Screen Shot 2022-09-08 at 07 10 34](https://user-images.githubusercontent.com/79164937/189118905-336c5396-8bd0-4247-9945-d218e11bb373.png)
![Screen Shot 2022-09-08 at 07 09 35](https://user-images.githubusercontent.com/79164937/189118902-801a4303-d527-4b38-983d-cd17b45189b7.png)
![Screen Shot 2022-09-08 at 07 12 18](https://user-images.githubusercontent.com/79164937/189118906-cda87884-e533-41c4-b151-4d838ee80130.png)

**Comment by pevma** [comment]
I can not reproduce it. 
Can you please share some details around the setup or how is it reproducible ?

This is what i did on Debian/Ubuntu:

```
git clone https://github.com/StamusNetworks/SELKS.git && \
cd SELKS/docker/ ; \
time ./easy-setup.sh  --non-interactive -i tppdummy0 --iA && \
time docker-compose up -d 
``` 

![Screenshot from 2022-09-09 09-32-50](https://user-images.githubusercontent.com/1405917/189296678-7dbffdf6-9e4a-4c86-b554-2a0e76fbf1e7.png)

**Comment by Matt-M-ironnet** [comment]
@pevma, I think I may have found the issue and I probably need to create a separate issues ticket. If you delete the default ruleset and attempt to create a new one, you will be greeted with the "Server Error (500)" Any attempts to then create a new ruleset after that will be greeted with a "Server Error (500)" as well. I noticed this behavior on both a Debian Docker image as well as a Debian 11 minimal VM.

**Comment by pevma** [comment]
@Matt-M-ironnet  - I could not reproduce that either. I deleted a default ruleset then created a new one - it worked fine. I had added previously custom sources to my default ruleset as well.   
Maybe i am missing something - what are our exact steps ? (start from default spin up, delete the rulesets and add a new one ?)

**Comment by Linn1** [comment]
I never delete the default ruleset .
When I try to create a new ruleset, the server will tell me "Server Error(500)".
I have no ruleset, and just one source without any categroies and rules.
The only source named ETOpen Ruleset.

**Comment by pevma** [comment]
I could not reproduce that either - just tested it. Added a new ruleset without an issue.
You running latest docker etc correct ?

**Comment by Linn1** [comment]
I want to recreate a new container but it didn't work.
The new suricata container  also has no rulesets!
I can't  make the server connect to trhe internet.

**Comment by Linn1** [comment]
> 

I am sure I run latest docker etc correct.
Because it worked at first and had default ruleset.

**Comment by pevma** [comment]
That actually happens on updates it seems, not on creation. Investigating and will feedback

**Comment by Linn1** [comment]
I solved this problem! 
I import the rules.tar.gz and create a new source with the new rules.Then I create a new ruleset with the new source.
I click the "suricata" but it shows that I should new something.It let me fill these blanks. Such as "name","Descr","Rules directory","Suricata configuration file" and "Ruleset".I fill them and choose "update","build","push" to apply. Finally, it apply successfully. But there is no alerts. I think it is nothing with suricata but the net.
I can close this problem.Thanks for your patience!

**Comment by pevma** [comment]
I think I found the issue. 
Can you confirm that when using the SELKS branch there is no issue?
```
./easy-setup.sh --scirius-version selks 
```

so the full setup would be something like:   
```
git clone https://github.com/StamusNetworks/SELKS.git && cd SELKS/docker/ ; \
./easy-setup.sh --scirius-version selks --non-interactive -i tppdummy0 --iA --es-memory 4G --ls-memory 2G  && \
docker-compose up -d 
```
