### ISSUE TITLE
🐞🐋 Suricata management - need Suricata create

### ISSUE THREAD

**Issue by ctropamer** [StamusNetworks/SELKS#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

i install SELKS behind a proxy and on default web interface when i click on suricata tab, interface ask me to create a suricata

he ask me:

name
Descr
Rules directory
Suricata configuration file
Ruleset

I put following
Name : server name
Descr: server name
Rules directory : /etc/suricata/rules
Suricata configuration file : /etc/suricata/suricata.yaml
Ruleset : my default rule set

But after that no info display

### Expected Behavior

Having something in Rules Activity or others tab

### Steps To Reproduce

cd /opt
git clone https://github.com/StamusNetworks/SELKS.git
cd SELKS/docker/
./easy-setup.sh --non-interactive --no-pull-containers -i ens192 --iA --restart-mode always --es-memory 8G
docker-compose up -d

i set some env for docker scirius / kibana / suricata

USE_PROXY	True
HTTP_PROXY	http://xx.xx.xx.xx:3128
HTTPS_PROXY	http://xx.xx.xx.xx:3128

### Docker version

Docker version 20.10.18, build b40c2f6

### Docker version

docker-compose version 1.29.2, build 5becea4c

### OS Version

Ubuntu 22.04.1 LTS

### Content of the environnement File

COMPOSE_PROJECT_NAME=SELKS
INTERFACES= -i ens192
ELASTIC_MEMORY=8G
SCIRIUS_SECRET_KEY=5Yzd8D0OvQx4jIAVSuDhtWg8lGa7T2aQkVXbbcXr05g

### Version of SELKS

commit 11d0d696cad50ab563da966db0758315cd6fda64 (HEAD -> master, origin/master, origin/HEAD)
Merge: d874ad5 83e757c
Author: Peter Manev <petermanev@gmail.com>
Date:   Sat Sep 24 08:36:57 2022 +0200

    Merge pull request #415 from pevma/default-to-selks-branch-v2

    docker: Make selks the default branch

**Comment by pevma** [comment]
You should just be presented with a log in screen, once you log in, you should be good to go and use it.
There is no creation step of suricata.

Can you please describe in  a bit more detail what are the steps that you are trying to complete?

**Comment by ctropamer** [comment]
Hi,

in my case suricata is empty

**Comment by pevma** [comment]
You mean the Hunt interface ?
Do you have anything in the `SN-FLOW` dashboard in Kibana or in EveBox for the last 24 hrs lets say ?

**Comment by ctropamer** [comment]
[](url)hi,

i have flow in Kibana and EveBox

it's just here i have nothing (check attach img)
![suricata](https://user-images.githubusercontent.com/64972587/194819902-68c9879e-8e33-44a5-8849-b22ddf56541a.jpg)

**Comment by pevma** [comment]
Ok - so you have the logs , just not alerts i think is what you are referencing to ? (The screenshot above shows just stats , not events)

You should most probably also have events in SN-DNS or SN-TLS dashboards for example.

**Comment by ctropamer** [comment]
Hi,

yes missing alerts and stats, i have SN-DNS & SN-TLS

do you have an idea why alerts and stats are empty ?

Thanks

**Comment by pevma** [comment]
It can be normal not to have alerts.    
Suricata produces network protocol, file transactions and flow data independently of alerts.   
One thing to check would be the `HOME_NET` variable definition in the yaml config. (`containers-data/suricata/etc/suricata.yaml `)

**Comment by ctropamer** [comment]
Hi,

ok 👍 
 HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    #HOME_NET: "[192.168.0.0/16]"
    #HOME_NET: "[10.0.0.0/8]"
    #HOME_NET: "[172.16.0.0/12]"
    #HOME_NET: "any"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"
    DC_SERVERS: "$HOME_NET"
    DNP3_SERVER: "$HOME_NET"
    DNP3_CLIENT: "$HOME_NET"
    MODBUS_CLIENT: "$HOME_NET"
    MODBUS_SERVER: "$HOME_NET"
    ENIP_CLIENT: "$HOME_NET"
    ENIP_SERVER: "$HOME_NET"

look like fine right ?

thanks for your time

**Comment by ctropamer** [comment]
works with correct entries

![Uploading suricata.jpg…]()

**Comment by ctropamer** [comment]
thanks for help

**Comment by pevma** [comment]
Thanks for trying it out !
