### ISSUE TITLE
how to upgrade Kibana from 3 to 4 in SELKS?

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/SELKS#42]
Hi! 
First thank you for this amazing project!
I'm wandering if there any reason why do you still use kibana 3 in SELKS distro? And are there any ways to upgrade Kibana from 3 to 4 version in the distro?

**Comment by regit** [comment]
Hello @Drewshg312, thanks for the compliment. There is a good reason Kibana 4 is not yet on board. Kibana 4 is completely incompatible with Kibana 3. @pevma has to redo all the dashboards among other problems. SELKS 3.0 is coming and will feature Kibana 4.

**Comment by Drewshg312** [comment]
Ic. Thanks...
