### ISSUE TITLE
pulling cron (docker:latest)

### ISSUE THREAD

**Issue by hearts1137** [StamusNetworks/SELKS#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found an issue on the same topic but it was resolved by connecting the system to the internet. This is not an option for me and shouldn't be necessary given the guides say the ISO can be run on an air gapped network.

Running right after install on an offline network using the Wiki as a guide; https://github.com/StamusNetworks/SELKS/wiki/Docker-ISO-setup

My command as root is;
cd /opt/selksd/SELKS/docker/ && ./easy-setup.sh --non-interactive --no-pull-containers -i ens33 --iA --restart-mode always --es-memory 8G && docker-compose up -d 
The error;
To start SELKS, run 'sudo docker-compose up -d'

Pulling cron (docker:latest)...
ERROR: Get "https://registry-1.docker.io/v2/": context deadline exceeded

### Expected Behavior

All services start

### Steps To Reproduce

Install an offline system using the nodesktop ISO of SELKS V7
Sudo to root
Run command as wiki suggests, replacing adapter name

### Anything else?

No internet access but can transfer files to it

**Comment by pevma** [comment]
I think the reason why it is pulling it it is  because the container is not on the ISO. Can you please check ? or share if you can the output of `docker  ps -a` run from the same folder?

**Comment by hearts1137** [comment]
`selks-user@SELKS7:/opt/selksd/SELKS/docker$ sudo docker ps -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED      STATUS         PORTS                                                           NAMES
e81886369ee5   portainer/portainer-ce   "/portainer --logo h…"   2 days ago   Up 2 minutes   8000/tcp, 9000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp   portainer`


I can reach the portainer interface and it shows the following images. All unused. I do not see cron

elastic/elasticsearch:7.16.1 	642.1 MB 	2021-12-10 23:12:34
elastic/kibana:7.16.1 	1.3 GB 	2021-12-10 19:30:15
elastic/logstash:7.16.1 	999.2 MB 	2021-12-10 19:51:20
ghcr.io/stamusnetworks/arkimeviewer:master 	610.5 MB 	2022-03-29 06:36:59
ghcr.io/stamusnetworks/scirius:master 	442.6 MB 	2022-03-20 11:32:50
hello-world:latest 	13.3 kB 	2021-09-23 18:47:57
jasonish/evebox:master 	22.6 MB 	2022-04-01 12:54:08
jasonish/suricata:master-amd64 	470.9 MB 	2022-04-04 16:33:25
nginx:latest 	141.5 MB 	2022-03-29 11:02:44
portainer/portainer-ce:latest 	279.6 MB 	2022-02-08 19:03:58
python:3.9.5-slim-buster 	114.8 MB 	2021-06-28 20:30:45

**Comment by pevma** [comment]
Can you copy the missing docker there , same folder on that machine?
Something like this would be good enough:

```
git clone https://github.com/NotGlop/docker-drag.git 
python3 docker-drag/docker_pull.py docker:latest
cp *.tar remote_selks_machine:/opt/selksd/SELKS/docker/tar_images/
```
Then rerun the setup script again.

**Comment by pevma** [comment]
yes, you can copy those over from a different location , where you have access to the internet.
