### ISSUE TITLE
Old Forgot Password Instructions

### ISSUE THREAD

**Issue by AnthonyVO** [StamusNetworks/SELKS#428]
I found the following instructions to help me recover from a lost password but they appeared to be out of date.

I no longer need this personally as I managed to remember my password but just in case someone else needs it in the future.  Who knows, it might be me :)

https://github.com/StamusNetworks/SELKS/wiki/Forgot-Scirius-web-log-in-password

**Comment by pevma** [comment]
For the SELKS 7 (docker version) this link should be used for password reset:  
https://github.com/StamusNetworks/SELKS/wiki/Docker#password-reset

**Comment by AnthonyVO** [comment]
Thank you very much.  Please consider fixing the original page with a link to the current instructions.  It is not clear that it only applies to SELKS6.

**Comment by pevma** [comment]
Fixed.
Thank you for the feedback !

**Comment by AnthonyVO** [comment]
Thank you very much...
