### ISSUE TITLE
Bookmark is 404

### ISSUE THREAD

**Issue by gardner** [StamusNetworks/SELKS#43]
Thanks for making SELKS! I just wanted to let you know that the bookmark link titled `IDS-ALL-Events` goes to a 404.

Version: 3.0rc1-desktop running on VirtualBox

![virtualbox_selks_24_04_2016_11_47_39](https://cloud.githubusercontent.com/assets/787026/14765589/a5c5fc84-0a12-11e6-8d1d-193fea60d047.png)

**Comment by pevma** [comment]
Thanks for trying it out and for the report!
Fix is implemented int he git master scirpts to address that - https://github.com/StamusNetworks/SELKS/commit/f62319b95a095227a36a0184f7d8505b6c055360  

(alternatively you can access all the dashboards from within Scirius)

**Comment by gardner** [comment]
Thanks. I found it on the desktop. :)
