### ISSUE TITLE
🐞💿 Easy-setup does not create opt/selksd/SELKS/docker/containers-data/scirius directory

### ISSUE THREAD

**Issue by SmoochSmackers** [StamusNetworks/SELKS#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running "docker-compose pull", in the context of the Docker ISO instructions page, I get the following error:

ERROR: Named volume "$\{PWD\}/containers-data/scirius/logs:/logs:rw" is used in service "scirius" but no declaration was found in the volumes section.

### Expected Behavior

I expected docker-compose pull to run without an error.

### Steps To Reproduce

1. Install the SELKS ISO in a VM.
2. Follow the steps on the Docker ISO setup page until you...
3. Try to run docker-compose pull.

### Anything else?

I've been trying to set SELKS up for a few weeks. In that time I have wiped my VM and started from scratch about half a dozen times or so. When following the [Docker ISO instructions](https://github.com/StamusNetworks/SELKS/wiki/Docker-ISO-setup#first-time-setup), every time I get to the point of using the command "docker-compose pull", I get the following error:

ERROR: Named volume "$\{PWD\}/containers-data/scirius/logs:/logs:rw" is used in service "scirius" but no declaration was found in the volumes section.

The error seems, to a novice like me, to suggest an issue with the docker-compose yml, but in reality it seems like the host directory is just not created by the ISO install or easy-setup.sh. The error disappears when I manually create said directory.

I'm still not 100% on whether I caused this issue somehow, but after so many instances of installing and following your setup instructions, I'm leaning towards it being a bug.

This is my first bug report, so I'm sorry if I did anything wrong. Let me know if there is anything you need me to change. I mostly wanted to give you all a heads up, in case it is actually a bug, and also making a record so that maybe someone else in the same predicament might have more luck in their google searches than I did. 

Edit: Well, to anyone reading this, don't follow my initial solution, I think I messed it up further. I clearly don't know what the heck is going on. Sorry!

**Comment by pevma** [comment]
Related to https://github.com/StamusNetworks/SELKS/pull/433   
This has been fixed actually.  I think you need to pull the latest SELKS github code

**Comment by SmoochSmackers** [comment]
I just re-downloaded the ISO, but the file hashes are the same as the file which I'd been using. This is the nodesktop version of SELKS ISO that I got from the [Stamus website](https://www.stamus-networks.com/selks?hsCtaTracking=dd5d142c-b97d-4ceb-8d18-bba111faaafd%7Cf49de916-a48a-46af-ab71-7780426002bf#Download). 

I apologize for my ignorance, but I'm not exactly sure how to do what you're asking, given the context I provided. I downloaded the ISO, installed it on a VM with more than enough compute resources allocated to it, and from there I follow the instructions for installation to which I provided a link in my initial post. 

If you mean the "docker-compose pull" command, that's precisely the command that throws the error I described. :/

**Comment by SmoochSmackers** [comment]
I was able to make some progress. My solution was one of two things either it was:
1.) Specifically log in as root, instead of selks-user
2.) Temporarily turning off adblock on my Pi-Hole

Or it was both in combination. Regardless, this specific issue seems to be resolved.
