### ISSUE TITLE
🐞🐋 404 page not found

### ISSUE THREAD

**Issue by aidrees** [StamusNetworks/SELKS#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi team, I have just installed SELKS on Docker on Ubuntu 20.04. I did not get any error running ./easy-setup.sh. and all containers are running.

sudo docker ps                                                                                                                                                          k3s-1: Wed Sep  6 13:53:36 2023

CONTAINER ID   IMAGE                                        COMMAND                  CREATED             STATUS                       PORTS                                           NAMES
89f5823fa2e0   elastic/logstash:7.16.1                      "/usr/local/bin/dock   "   About an hour ago   Up About an hour (healthy)   5044/tcp, 9600/tcp                              logstash
c0ea058e700d   jasonish/suricata:master-amd64               "/etc/suricata/new_e   "   About an hour ago   Up About an hour                                                             suricata
9f221ccd3dfc   nginx                                        "/docker-entrypoint.   "   About an hour ago   Up About an hour             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx
e517af049be1   jasonish/evebox:master                       "/docker-entrypoint.   "   About an hour ago   Up About an hour                                                             evebox
3b8670b199ca   elastic/kibana:7.16.1                        "/bin/tini -- /usr/l   "   About an hour ago   Up About an hour (healthy)   5601/tcp                                        kibana
b5a71cfe2fda   ghcr.io/stamusnetworks/arkimeviewer:master   "/start-arkimeviewer   "   About an hour ago   Up 8 minutes                 8005/tcp                                        arkime
7a0d8a127347   docker:latest                                "dockerd-entrypoint.   "   About an hour ago   Up About an hour             2375-2376/tcp                                   cron
d2521e315d70   ghcr.io/stamusnetworks/scirius:selks         "/opt/scirius/bin/st   "   About an hour ago   Up About an hour (healthy)   8000/tcp                                        scirius
2ce2b78045bb   elastic/elasticsearch:7.16.1                 "/bin/tini -- /usr/l   "   About an hour ago   Up About an hour (healthy)   9200/tcp, 9300/tcp                              elasticsearch

![image](https://github.com/StamusNetworks/SELKS/assets/9464275/44476555-c804-43b8-bcf1-24e8d67a527e)

I am not sure what is causing the problem. Any guidance is appreciated.

### Expected Behavior

reach out to the page

### Steps To Reproduce

git clone https://github.com/StamusNetworks/SELKS.git
cd SELKS/docker/
./easy-setup.sh
docker-compose up -d

https://VM-IP-ADDRESS
or
curl https://VM-IP-ADDRESS -k

### Docker version

Docker version 24.0.5, build ced0996

### Docker version

N/A

### OS Version

Ubuntu 20.04.3 LTS

### Content of the environnement File

COMPOSE_PROJECT_NAME=selks
INTERFACES= -i ens33
SCIRIUS_DEBUG=True
NGINX_EXEC=nginx-debug
SCIRIUS_SECRET_KEY=ojtB9cR27IJJfN2VMjJE3rybZc2o8bP8NqPhi3apJgg
PWD=$\{PWD\}

### Version of SELKS

commit f57617669bc36c32056ccdc83c776abbb843407f (HEAD -> master, origin/master, origin/HEAD)
Author: Ali Al Idrees <aalidrees@vmware.com>
Date:   Tue Sep 5 17:12:31 2023 +0400

    Update nginx-deployment.yaml

**Comment by pevma** [comment]
Hi , Thank you for trying out SELKS
This info above does not seem to be the latest github master SELKS repo:

```
git clone https://github.com/StamusNetworks/SELKS.git && cd SELKS/docker/ 

Cloning into 'SELKS'...
remote: Enumerating objects: 3381, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 3381 (delta 125), reused 185 (delta 121), pack-reused 3164
Receiving objects: 100% (3381/3381), 10.67 MiB | 6.89 MiB/s, done.
Resolving deltas: 100% (1821/1821), done.

cd SELKS

git log

commit a030b9acbef9e846cfd247fef9c8ac8c1794c6a8 (HEAD -> master, origin/master, origin/HEAD)
Author: Eric Leblond <el@stamus-networks.com>
Date:   Mon Jul 31 19:08:48 2023 +0200

```

**Comment by aidrees** [comment]
Hi, thank you for replying. I have created a branch to  the latest git and use it. I did not do any changes to the docker folder. It is the latest. Any suggestions on how to troubleshoot the issue?

**Comment by pevma** [comment]
Not sure what the local modifications are  which would make it difficult to troubleshoot.

**Comment by aidrees** [comment]
I will redeploy with the master in couple of days and let you know

**Comment by aidrees** [comment]
Problem solved. I had a K3s Cluster installed on same VM. K3s creates a LoadBalancer Service that uses port 443.
it was a port overlap.
