### ISSUE TITLE
✨✨ SELKS iso

### ISSUE THREAD

**Issue by Acenl12** [StamusNetworks/SELKS#455]
### Is there an existing feature request that has already been created?

- [X] I have searched the exiting features requests

### Is your feature request related to a problem? Please describe.

What I noticed is that when everything is installed you go to the main page there is no http to https redirect, so I changed it for myself. Maybe that's also useful for implementing in the ISO. I wanted to do a pull request on the ISO, but i dont see the contents anywhere in your repo. I just added this to the nginx of the server (not in the nginx container)

```
server {
    listen 80 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}
```

### Describe the solution you would like?

.What I noticed is that when everything is installed you go to the main page there is no http to https redirect, so I changed it for myself. Maybe that's also useful for implementing in the ISO. I wanted to do a pull request on the ISO, but i dont see the contents anywhere in your repo. I just added this to the nginx of the server (not in the nginx container)

 ```
 server {
    listen 80 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}
```

Of course remove the listen 80 from the server block that was initial there

**Comment by pevma** [comment]
Thanks @Acenl12 for the report and fix!
One place to include this is maybe in the host prep script - https://github.com/StamusNetworks/SELKS/blob/master/staging/config/hooks/live/chroot-inside-Debian-Live.hook.chroot

**Comment by Acenl12** [comment]
> Thanks @Acenl12 for the report and fix! One place to include this is maybe in the host prep script - https://github.com/StamusNetworks/SELKS/blob/master/staging/config/hooks/live/chroot-inside-Debian-Live.hook.chroot

Are you guys going to change it yourself? Or do you expect a pull request from me?

**Comment by Acenl12** [comment]
Close
