### ISSUE TITLE
🐞🐋 Server 500 Error on System Settings after a clean install

### ISSUE THREAD

**Issue by bleblux** [StamusNetworks/SELKS#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a clean install, default with easy-setup.sh, the setup terminates ok and all the dockers when up. All seems to work perfectly except the Systems->Settings feature, that returns an 500 Sever Error when it is navegated from the Stamus Networks menu.
To comment, at the easy-setup.sh, a different path was specified to store the logs. Is the unique change of a default setup.

### Expected Behavior

This scirius feature doesn't work as expected

### Steps To Reproduce

Entering on de Stamus gui and choosing the 'system settings' option is the way to reproducte the issue.

### Docker version

Docker version 27.1.1, build 6312585

### Docker version

Docker Compose version v2.29.1

### OS Version

Ubuntu 24.04 LTS

### Content of the environnement File

COMPOSE_PROJECT_NAME=selks
INTERFACES= -i br0
RESTART_MODE=on-failure
ELASTIC_DATAPATH=/logs
SCIRIUS_SECRET_KEY=<secret>
PWD=$\{PWD\}

### Version of SELKS

commit 4af455cd15f69f2ba471fa6cd0b96d6aae6e93b9 (HEAD -> master, origin/master, origin/HEAD)
Author: Peter Manev <pmanev@stamus-networks.com>
Date:   Thu Jun 13 13:18:18 2024 +0200

    docker: Add Logstash/Kibana docker versions

**Comment by pevma** [comment]
This should be fixed now.
you can update like so: https://github.com/StamusNetworks/SELKS/wiki/Docker#upgrade-all-containers

**Comment by bleblux** [comment]
It works as expected. Thank you all
