### ISSUE TITLE
Dependency on hostname.

### ISSUE THREAD

**Issue by jasonish** [StamusNetworks/SELKS#48]
First I installed SELKS 3.0rc1 in a VM (bridge networking) using the default hostname and all is fine.

Later I created another SELKS VM, but gave this one the hostname of "SELKS-dev".  In SELKS-dev (desktop installed), I opened Scirius from the desktop icon which takes me to "https://selks/rules/".  This actually took me to my other VM instance with the hostname "SELKS", not the VM I was running.

Navigating to "https://selks-dev/rules/" or "https://localhost/rules" takes me to the correct instance.

**Comment by pevma** [comment]
Fixed by  https://github.com/StamusNetworks/SELKS/pull/49
