### ISSUE TITLE
🐞💿 Threat hunting dashboard empty?

### ISSUE THREAD

**Issue by dsputnikk** [StamusNetworks/SELKS#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello all.

I've successfully installed SELKS and receiving traffic on a GRETAP interface.  I used the ISO and easy-setup.sh . All pods are healthy, tcpdumps looks as expected, all web UIs load, suricata mgmt interface shows traffic and hits, kibana dashboards work as well. Evebox shows alerts.

However the hunting dashboad is completely empty? Am I missing something? 

docker-compose logs are suspiciously empty.

### Expected Behavior

I expect to see data in the included hunting dashboard

### Steps To Reproduce

VSphere 8
32GB of RAM
ES is given 28GBs

**Comment by whale-withme** [comment]
hi, i can not see any data in dashborad too. Could you please tell how you fix it? By the way, I clicked reload button.
