### ISSUE TITLE
Documentation about "curator" is wrong and probably un-tested

### ISSUE THREAD

**Issue by antibarbie** [StamusNetworks/SELKS#51]
Unescaped percent signs are converted into new-lines when used in a cron command line,
so the documentation here is wrong : https://github.com/StamusNetworks/SELKS/wiki/Data-lifecycle

I mean, okay it works from command line, but not from cron.

Maybe an (untested)  fix would be : 
`--timestring '\%Y.\%m.\%d'`

**Comment by pevma** [comment]
Thanks for the good catch! 
It works on the command line but it for cron you need to escape those, yes.

There is new version of curator  (4.0) actually has no backward compatibility with 3.5 so i suggest yous tick with 3.5 until SELKS 3.0 is out.

**Comment by pevma** [comment]
Updated the docs - https://github.com/StamusNetworks/SELKS/wiki/Data-lifecycle
Thanks again for the good eyes!
