### ISSUE TITLE
Firstime setup

### ISSUE THREAD

**Issue by ohharsad** [StamusNetworks/SELKS#56]
Hello, i new in SELKS, iam using SELKS for my final year project.
Refer to the diagram,
i want to setup stamus (6ixthHunter) as inline IPS, i found out that i can't bridge network. 

Webserver network: 10.0.0.0/24
Stamus network: 192.168.0.0/24

any tips regarding this issue or suggest me some setup..
![physical](https://cloud.githubusercontent.com/assets/20744213/20427450/f7a3a632-adbe-11e6-8740-96b2df91d5a1.jpg)

**Comment by pevma** [comment]
How do you mean you can't bridge? Any particular errors?

**Comment by ohharsad** [comment]
i got n error while try this command "ifup br0"

**Comment by pevma** [comment]
Then i think you need to review your bridge set up before moving forward with IPS/SELKS.
