### ISSUE TITLE
Potential issue with Scirius truncating alert information

### ISSUE THREAD

**Issue by mars01** [StamusNetworks/SELKS#60]
Good morning,

I'm seeing a potential issue where Scirius is truncating alert information to 20 items in both the Source and Destination IP addresses. I'm noticing this discrepancy when I change from last hour to last seven days where several different IP addresses will show up. I'm trying to find a way to obtain a complete list for the last seven days.

**Comment by pevma** [comment]
It could be because for the last hour an IP showed up a lot as part of an ssh scan for example -  but then it never appeared in the last 6 days so  it may not make it to the top 20 IPs/alerts for the past 7 days.

**Comment by mars01** [comment]
Ah okay. Thanks Peter.
