### ISSUE TITLE
PF_RING integration on SELKS

### ISSUE THREAD

**Issue by GeoNets** [StamusNetworks/SELKS#61]
Hi,

What's the status of PF_RING integration for SELKS Community Edition? Is it only available on the commercial version?

Thank you,

**Comment by regit** [comment]
There is no use for PF_RING if we omit some corner cases with some specific capture. SELKS and commercial version are using AF_PACKET that scale really well to over 10gbps.

**Comment by GeoNets** [comment]
Ah. Thank you.
