### ISSUE TITLE
Non IP Variables

### ISSUE THREAD

**Issue by SigPloiter** [StamusNetworks/SELKS#62]
am working on a project to setup an IDS for telcom Signalling traffic, and i was wondering if the engine would perfectly detect those packets if i added them in app-layer protocol directive, or is there any tuning i need to do .

The protocols inscop: GTP, Diameter, SS7(MAP,CAMEL)

thanks

**Comment by pevma** [comment]
Currently not the protocols you mention above.
You can however amend the code for those.
Please note it should be in line with GPLv2.
