### ISSUE TITLE
No graphs on new installation

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/SELKS#63]
I installed SELKS 3.0. Suricata works and I can see the list of alerts in web-interface, but I can't see the graphs.
The only graph I see is Logstash event insertion speed, but others absent, I see only No data available.
If I open Kibana I see events, statistics, etc..
So it seems to me that problem is in scirius. 
Suricata, Elasticseach and Logstash logs don't have any criminal and indicators in Scirius are green.

**Comment by pevma** [comment]
Hi,
Is it a case where you don't see any data only in Scirius?
Do you see any data in the dashboards in Kibana and EveBox?

Thank you

**Comment by VN1977** [comment]
> Do you see any data in the dashboards in Kibana and EveBox?
Yes, certainly.  I don't know what EveBox is but I see data in Kibana.
And I see alerts in Scirius.

**Comment by VN1977** [comment]
Maybe it helps.... I partitioned disks manually. Of course it can't be the reason but....  I installed Scirius several times before and every time it was OK. But I partitioned disks automatically so at the moment I suspect that manual partitioning could be somehow connected with this.

**Comment by VN1977** [comment]
>  I installed Scirius several times before
**SELKS** was installed, not Scirius. I made a mistake

**Comment by pevma** [comment]
@VN1977  -  did you by any chance change the host name? see here -  https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---HOSTNAME

**Comment by VN1977** [comment]
Thanks a lot!
Couldn't expect that  it's so easy
