### ISSUE TITLE
Request for MD5 or SHA1 hash with files SELKS sees

### ISSUE THREAD

**Issue by espressobeanies** [StamusNetworks/SELKS#65]
Good morning,

I'm not sure if this would be possible to do with SELKS or if it's a limitation with Suricata, but would it be possible to provide an MD5 or SHA1 hash with the files that SELKS comes across?

Thank you!

**Comment by pevma** [comment]
That is possible yes - you should already have that info in the Suricata eve.json log - `"event_type":"fileinfo"`. Can you confirm?

**Comment by pevma** [comment]
Closing as there is no feedback for  a while.
