### ISSUE TITLE
Role of the Action Tab

### ISSUE THREAD

**Issue by heroflex** [StamusNetworks/SELKS#66]
What do each of the rules do in the action tab? Examples of the rules are: "Disable rule", "Enable rule", "Threshold rule", "Suppress rule", and "Delete generated alerts"

**Comment by stamus** [comment]
> On 14 Apr 2017, at 17:39, heroflex <notifications@github.com> wrote:
> 
> What do each of the rules do in the action tab? Examples of the rules are: "Disable rule", "Enable rule", "Threshold rule", "Suppress rule", and "Delete generated alerts"
> 
Disable - disables a rule 

Enable - enables a disabled rule

Threshold - configures a threshold on the rule for alerting - aka for example alert only every 10th occurrence

Delete generated alerts - deletes all generated by that rule alerts 

Thanks

**Comment by pitoganzado** [comment]
"Disable - disables a rule", correct but after a couple of seconds, they start appearing again... how can i fix that? Regards

**Comment by regit** [comment]
@pitoganzado you need to push ruleset for change to be applied.

**Comment by pitoganzado** [comment]
@regit thanks, need to build and push?

**Comment by regit** [comment]
Yes, these two steps at leastLe 28 juil. 2017 11:47 AM, pitoganzado <notifications@github.com> a écrit :@regit thanks, need to build and push?

**Comment by pevma** [comment]
Closing as it seems resolved.
