### ISSUE TITLE
Use of a file with hash of malicious MD5 files in rules

### ISSUE THREAD

**Issue by esmelnikov** [StamusNetworks/SELKS#68]
Hi! 
Thanks for your work.
I have a file with hashes of malicious MD5 files that is updated from the Malware Patrol source. I added the source to Selks and successfully updated it. How can I use it to detect the download/upload of malicious files? What rule do you need to create, and how to connect the generated source to receive warnings in case of detection of malicious files?
Thanks!

**Comment by pevma** [comment]
How to docs can be found here - 

http://suricata.readthedocs.io/en/latest/rules/file-keywords.html?highlight=filestore
http://suricata.readthedocs.io/en/latest/file-extraction/file-extraction.html?highlight=MD5

**Comment by esmelnikov** [comment]
Hi! 
I created the following rule:

`alert http any any -> any any (msg:"Malicious file - Malware Patrol MD5 Hash"; filemd5:/etc/suricata/rules/mpmd5; classtype:suspicious-filename-detect; sid:2777777; rev:2;)`

Created the source via uploaded  through Scirius interface. Add sourse in Default SELKS ruleset, enable category and Build & Push to suricata. When downloading test file using the https protocol, if our MD5 is the same as the fast.log file, the following entry appears in the directory: /var/log/syricata

`05/12/2017-10:48:16.862485  [**] [1:2777777:2] Malicious file - Malware Patrol MD5 Hash [**] [Classification: A Suspicious Filename was Detected] [Priority: 2] {TCP} 202.8.44.105:80 -> 10.46.104.38:46651`

But in the interface of Scirius these events are not displayed. How can you correct this behavior?

**Comment by pevma** [comment]
Do you have a similar entry in /var/log/suricata/eve.json ?

**Comment by esmelnikov** [comment]
Yes, I can also see these events in EveBox with the "fileinfo" tag with the desired value hash md5

**Comment by pevma** [comment]
Only with "fileinfo" or there are also alerts? You can try to follow the "flow" and see all the logs generated.

**Comment by pevma** [comment]
@esmelnikov - Do you still have the same issue even after upgrading to the latest Scirius 1.2.4 (as part of SELKS 4)?

**Comment by esmelnikov** [comment]
The problem is solved, in SELKS 4 rc1 the rule works and alerts are displayed in the Scirius interface.

**Comment by pevma** [comment]
Thank you for the feedback! Closing.
You might want to upgrade to SELKS 4 -  just released a few hrs ago :)
