### ISSUE TITLE
GeoIP MAP information and MAP is not displayed

### ISSUE THREAD

**Issue by esmelnikov** [StamusNetworks/SELKS#70]
In the dashboard in Kibana, GeoIP MAP information and MAP is not displayed. 

![2017-05-03_081059](https://cloud.githubusercontent.com/assets/26947034/25647175/2e55c4c0-2fd9-11e7-83f1-c4e303cf08a4.png)

The SELKS server is connected to the Internet through a proxy server. On another SELX server with the same version of SELKS, which is connected to the Internet directly, GeoIP Map works without problems. What could be the problem? How can I configure GeoIP MAP?

**Comment by pevma** [comment]
If it the http logs are with only private IP addresses  it would not have GeoIP.  Is that the case?

**Comment by esmelnikov** [comment]
Oh, of course, I'm sorry for my stupid question. After connecting the network SPAN Selks interface after proxy server, everything works fine.

**Comment by pevma** [comment]
ok :) closing then.
