### ISSUE TITLE
sources.list missing main Debian repositories 

### ISSUE THREAD

**Issue by Antonlovesdnb** [StamusNetworks/SELKS#71]
The sources.list file was missing the following: 

deb http://http.debian.net/debian/  jessie main contrib non-free

This was breaking updates.

**Comment by regit** [comment]
Seen on the installed version. Live is ok.

**Comment by pevma** [comment]
I have checked both the sources in SELKS 3 and the one sin the test SELKS 4 upgrades:  

```
root@SELKS:~# cat /etc/apt/sources.list
# 

# deb cdrom:[Debian GNU/Linux 8 _Jessie_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160811-10:54]/ jessie contrib main

deb cdrom:[Debian GNU/Linux 8 _Jessie_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160811-10:54]/ jessie contrib main

deb http://ftp.us.debian.org/debian/ jessie main
deb-src http://ftp.us.debian.org/debian/ jessie main

deb http://security.debian.org/ jessie/updates main contrib
deb-src http://security.debian.org/ jessie/updates main contrib

# jessie-updates, previously known as 'volatile'
deb http://ftp.us.debian.org/debian/ jessie-updates main contrib
deb-src http://ftp.us.debian.org/debian/ jessie-updates main contrib
root@SELKS:~# 
```

It seems the part that is missing is  - "non-free" but that is needed if you have added/installed certain packages that need that. Is that the case?

**Comment by regit** [comment]
Nope, there was no source at all. Could it be a step in the install process that have been skipped like "adding a new source" ?

**Comment by pevma** [comment]
It could be  -  but could not think of it right away... and I couldn't reproduce it so any info would be helpful actually.

**Comment by regit** [comment]
@Antonlovesdnb do you remember if you choose a mirror during the install process ?

**Comment by Antonlovesdnb** [comment]
@regit - Yes I do remember, I specifically said no to choosing a mirror during the installation. This makes sense now. Dumb on my part :)

**Comment by pevma** [comment]
ok - so safe to close in that case :) ? Please feel free to do so.

**Comment by Antonlovesdnb** [comment]
Yes thank you! c
