### ISSUE TITLE
Several NICs and config

### ISSUE THREAD

**Issue by EHRETic** [StamusNetworks/SELKS#72]
Hello there,

Despite my googling, I'm missing a bit of Debian knowledge to be very confortable modifying everything.

I have created a new VM with 2 NICs. I've planned to have the first interface eth0 to be on the "normal" vswitch, having a fixed IP and access the console from there.

The sniffing interface eth1 is on a vswitch on his own (same VLAN) but with promiscuous mode activated.

I've put the following into interfaces file, how can I make sure it is listening properly on the right interface ?

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet static
address 192.168.A.B
netmask 255.255.255.0
gateway 192.168.A.C
dns-nameservers 192.168.A.D 192.168.A.E

# The sniffing network interface
auto eth1
iface eth1 inet manual
pre-up ifconfig $IFACE up
post-down ifconfig $IFACE down
post-up /etc/network/if-up.d/idps-interface-tuneup_stamus
```

Any help on that ? Thanks in advance ;-)

**Comment by pevma** [comment]
Hi,

You need to change/adjust the sniffing interface in the afpacket section of the /etc/suricata/suricata yaml.

**Comment by pevma** [comment]
systemctl restart suricata  - after that :)

**Comment by EHRETic** [comment]
Thanks a lot, I used the EXACT same setup as the youtube video and it worked fine.
