### ISSUE TITLE
Suppressions not active in rulesets

### ISSUE THREAD

**Issue by EHRETic** [StamusNetworks/SELKS#73]
Hello,

Despite creating several "exceptions" (suppression from a specific IP) in my ruleset, it's not taking them into consideration.

I added for several sids a rule to ignore my vulnerability scanner, but it is still coming back.
I've tried to create a new ruleset from scratch but it didn't help.

As an FYI, the ruleset (and the previous default one) are showing some errors :

```
Ruleset has errors

SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv4.frag_too_large"
SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:"SURICATA FRAG IPv4 Packet size too large"; decode-event:ipv4.frag_too_large; sid:2200069; rev:1;)"
SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv6.frag_too_large"
SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:"SURICATA FRAG IPv6 Packet size too large"; decode-event:ipv6.frag_too_large; sid:2200071; rev:1;)"
```

How can I check there are properly created or solve this issue ? 

Thanks in advance :-)

**Comment by pevma** [comment]
Did you restart Suricata?

**Comment by EHRETic** [comment]
Hello,

Unfortunately, neither the server nor the service restart did bring any update.

I have installed the server a couple of days before from scratch (I'm a fresh user from SEKLS). I've tried to update all components like mentioned in youtube video, but maybe something is still buggy and requires an additional update. 

Any idea where I should look for ?

**Comment by pevma** [comment]
Sorry i didn't understand  -  did you restart the Suricata service? (systemctl restart suricata)

**Comment by EHRETic** [comment]
Yes I did and I also tried to restart the full server. None of them helped.

**Comment by pevma** [comment]
I think you should try updating the ruleset - from Scirius tabs - "Suricata", "ruleset actions" then select all and press "Apply".

**Comment by regit** [comment]
@EHRETic how did you set them up ? (via scirius ? file edit ?)

**Comment by EHRETic** [comment]
@pevma I've tried but I get an error :
```

AttributeError at /suricata/update
'NoneType' object has no attribute 'update'
Request Method:	POST
Request URL:	https://scans.ehretic.fr/suricata/update
Django Version:	1.8.14
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'update'
Exception Location:	/opt/selks/scirius/suricata/views.py in update, line 135
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/opt/selks/scirius',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']
Server time:	Mon, 15 May 2017 17:07:21 +0200
```

@regit I did use scirius, I'm not keen to do file manipulation on Linux systems :-)

**Comment by EHRETic** [comment]
@pevma EDIT : in Suricata edit menu, I had no rule set error, the update worked after selecting one. I've launched another vulnerability scan after this update to see if my rules work.

Maybe this lack of selected ruleset was the problem. I'll keep you guys posted. Thanks for now :-)

**Comment by EHRETic** [comment]
Seems to have worked reselecting the rulesset...

Thanks @pevma for giving me the hint ! ;-)
