### ISSUE TITLE
Suricata in red

### ISSUE THREAD

**Issue by jhautefeuille** [StamusNetworks/SELKS#77]
I'm using the last release iso and install it.

Suricata is in red.

> cat /var/log/suricata.suricata.log

```
[1739] 13/7/2017 -- 02:03:52 - (conf-yaml-loader.c:265) <Info> (ConfYamlParse) -- Configuration node 'af-packet' redefined.
[1739] 13/7/2017 -- 02:03:52 - (suricata.c:1109) <Notice> (LogVersion) -- This is Suricata version 4.0.0-dev (rev 5e3d8b1)
[1739] 13/7/2017 -- 02:03:52 - (util-cpu.c:171) <Info> (UtilCpuPrintSummary) -- CPUs/cores online: 4
[1739] 13/7/2017 -- 02:03:52 - (util-spm-hs.c:85) <Error> (HSBuildDatabase) -- [ERRCODE: SC_ERR_FATAL(171)] - Unable to compile '\x47\x45\x54\x20' with Hyperscan, returned -11.
```

**Comment by pevma** [comment]
It seems your CPU doesn't have the flags needed to support Hyperscan.
Can you please share the output of  - `cat /proc/cpuinfo`

**Comment by jhautefeuille** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 1799.999
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm
bugs		:
bogomips	: 3599.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 1799.999
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm
bugs		:
bogomips	: 3599.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 1799.999
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm
bugs		:
bogomips	: 3599.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 1799.999
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm
bugs		:
bogomips	: 3599.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by pevma** [comment]
It seems there is no SSSE3 flag in the CPU that is needed by Hyperscan.

**Comment by jhautefeuille** [comment]
Ok thank you for your reply !

**Comment by jhautefeuille** [comment]
I confirm it was the problem. 

I solve it to enable Sandy bridge processor in proxmox instead of kvm64.

Thank you for your help.

**Comment by Xtopher0s** [comment]
I have the same issue now in PVE-5.2-1. Changing to sandy bridge doesn't work it seems. jhautefeuille, what version of proxmox were you seeing this issue on?

**Comment by jobhh** [comment]
> 
> 
> I have the same issue now in PVE-5.2-1. Changing to sandy bridge doesn't work it seems. jhautefeuille, what version of proxmox were you seeing this issue on? Sorry for commenting on old issue. :(
> 
> My host cpu is AMDFX8350

That's probably because the FX8350 is an AMD Piledriver CPU and not an Intel Sandy Bridge. You could try changing it to "host".

(yes I know this was an old question, but he replied to a 2 year old issue, so I'm relatively early)
