### ISSUE TITLE
SELKS4: no data available in Scirius

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#80]
Hi,

This is a fresh install of SELKS 4.0 RC1
On a VM running on ESXi 6.5
In a network with VLAN tagging (Ubiquity hardware)

I can see traffic in both direction on wireshark on SELKS
When I connect to Scirius I am getting a Yellow flag on elastic search because one shard hasn't been assigned
A red flag on memory, but not anymore info on that.
All tabs on Scirius gives me a "No data available", including memory usage.

I did a service status on logstash, elasticsearch, suricata and they are all running

When I try a Kibana dashboard there are no data either.

I did a selks-upgrade_statmus.sh and rebooted several times

Any ideas how I could fix that?
Thanks.
Bugs.

**Comment by pevma** [comment]
What is the CPU/RAM you have for the machine?
Have you changed the host name by any chance ? ( https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---HOSTNAME )

**Comment by pevma** [comment]
Could be a good feature to consider.  Would you please post it a s a feature request on Scirius github (and close this ticket if ok).

**Comment by pevma** [comment]
Closing here as it is documentation as part of the initial set up procedure.
Please feel free to open a feature request for discussion at the Scirius github repo.
