### ISSUE TITLE
SELKS4: Weird error in Suricata.logs

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#81]
Hi,

This is a fresh install of SELKS 4.0 RC1
On a VM running on ESXi 6.5
In a network with VLAN tagging (Ubiquity hardware)
I can see traffic in both direction on wireshark on SELKS

I have just posted another post because I cannot see any alerts/info in Scirius and Kibana, but as I was troubleshooting the issue I found something odd in suricata.log
It may be related to my problem, but probably not so I am opening a new issue.

I can see the following error in suricata.log
[23023] 28/7/2017 -- 09:31:15 - (source-af-packet.c:1346) <Warning> (AFPTryReopen) -- [ERRCODE: SC_ERR_AFP_CREATE(190)] - Can not open iface 'enp0s3'

What is strange is that I do not have such interface on my box, and I never instructed SELKS to use such interface.
Is that normal?

Thanks,
Bugs.

**Comment by pevma** [comment]
Is the interface `enp0s3` up ?

**Comment by b-u-g-s** [comment]
Nope it doesn't exist, in fact it never existed and at no point did I specify that interface name. Could it be some artefacts left from a default script?

**Comment by pevma** [comment]
in `selks4.yaml` in `/etc/suricata/` it exists as a default (just like `eth0` is often used as default). So you the first thing you would actually need to do is specify IDS interface.

**Comment by b-u-g-s** [comment]
Ah... so this isn't replaced as part of the initial setup/install when it asks which interface should be used for monitoring?

**Comment by pevma** [comment]
No it is - it should be replaced when setting up the interface via the script or the desktop link.
Now it could also be possible that the err msg you see is from before - when it was not set up?

**Comment by pevma** [comment]
Updated the docs  for initial set up steps - https://github.com/StamusNetworks/SELKS/wiki#initial-setup
