### ISSUE TITLE
Monitoring Multiple SPAN ports

### ISSUE THREAD

**Issue by bbrennan04** [StamusNetworks/SELKS#83]
I have Installed SELKS and completed the setup and am able to pull elasticsearch logs on kibana from only one of my two interfaces. I have both enp3s0f0 and enp3s0f1 configured to promiscuous in /etc/network/interfaces. I have also used the reconfigure-listening-interface_stamus.sh script located in /opt/selks/Scripts/Setup to add both of the interfaces but it will only accept one argument. I have looked online for a solution and came across someone with a similar issue who was directed to add the interfaces to the ap-packet area of /etc/suricata/suricata.yaml https://groups.google.com/forum/#!topic/selks/SAMDzQRggbs

After trying this and many other options I am still unable to get BOTH sets of traffic to display on the IDS console. I have confirmed that both promiscuous ports are both SPAN and working properly using a tcpdump and switching between the two as the assigned monitoring port on selks. However, again I am only able to see one of the other. 
Is there something that I am missing here? Anything would help. Thanks

**Comment by pevma** [comment]
Thanks for trying out SELKS!
If you are using SELKS4 RC  - the config file that you should edit is  - `/etc/suricata/selks4-addin.yaml` as this file is added (at the bottom) to `/etc/suricata/suricata.yaml` and overwrites the defaults there. Could you try out and see if that fixes the issue?

**Comment by bbrennan04** [comment]
Awesome that worked perfectly! Thank you so much for the quick response. I do have one side question to help me better understand the file /etc/suricata/selks4-addin.yaml 
I am under the impression that under the af-packet section the commented lines are there for cosmetic and wont make a difference if not included in the interface config. Seeing how I did not include them when adding the new one and everything works I assume this is true. I would just like to be sure that I am not dooming myself further down the road

**Comment by pevma** [comment]
You can skip the comments yes - but be careful not to forget that for example such an option exists :) (that is commented).  
Also be mindful that spaces/tabs and new lines matter in the `yaml` syntax :)
