### ISSUE TITLE
SELKS Scirius CE v1.2.2 stops reporting alerts activity

### ISSUE THREAD

**Issue by drikusb** [StamusNetworks/SELKS#84]
Hi,

I've downloaded SELKS and seems to work great for an hour or so thereafter the alerts activity just stops. I've checked log files for any errors but can't see anything of value that might indicate issues.

I am testing 2 instances on 2 different ESX hosts and both randomly stops.

I initially though the VM doesn't have enough resourced so started off with 2vCPU & 8Gb ram but had the same issue. I increased it to 6vCPU and 16Gb ram but still the same problem.

When i reset all the logs, the graph starts working again as per [https://github.com/StamusNetworks/SELKS/wiki/Reset-stats-and-logs](url) link, but again only for an hour maybe 2. I've had the one VM working all night , but stopped at around 1 hour before this post.

Looking at Elasticsearch, it actively logs data according to the graph, and also the "current" value in "Alert stats for last xh" also increases.

Haven't changed any hostname :)

Any ideas?

**Comment by pevma** [comment]
Hi, 

Thanks fo trying out SELKS.
Some comments inland ne bellow ?

> On 7 Aug 2017, at 18:37, drikusb <notifications@github.com> wrote:
> 
> Hi,
> 
> I've downloaded SELKS and seems to work great for an hour or so thereafter the alerts activity just stops. I've checked log files for any errors but can't see anything of value that might indicate issues.
> 

Which SELKS is that - 4RC1?


> I am testing 2 instances on 2 different ESX hosts and both randomly stops.
> 
> I initially though the VM doesn't have enough resourced so started off with 2vCPU & 8Gb ram but had the same issue. I increased it to 6vCPU and 16Gb ram but still the same problem.
> 
> When i reset all the logs, the graph starts working again as per https://github.com/StamusNetworks/SELKS/wiki/Reset-stats-and-logs link, but again only for an hour maybe 2. I've had the one VM working all night , but stopped at around 1 hour before this post.
> 
What is the size of the traffic  you are monitoring?
Is it possible you run out of disk space?

**Comment by drikusb** [comment]
Heya,

Yeah 4.0RC1. Downloaded and installed with image SELKS-4.0rc1-nodesktop.iso.

HDD size of VM is 256GB, but doesn't get filled up for at least 9 hours. The traffic volume is around 700Mbps

**Comment by drikusb** [comment]
From what i can see, yes. Everything is green, except Elasticsearch which is orange due to a unallocated shard.

**Comment by pevma** [comment]
Ok. We need to somehow find out why it stops logging.  
Besides the web indicators - when it stops can you have  a look on the command line for the service status:  

```
systemctl status suricata elasticsearch kibana logstash
supervisorctl status scirius
```

and then tail the ES and LG logs to see if there is anything interesting:

```
/var/log/logstash/logstash.log
/var/log/elasticsearch/elasticsearch.log
```

Could you please share that info when available?

**Comment by drikusb** [comment]
sure , will do... i'll post this soon.

**Comment by drikusb** [comment]
Hi, 

As requested.

[service status.txt](https://github.com/StamusNetworks/SELKS/files/1209834/service.status.txt)
[elasticsearchlog.txt](https://github.com/StamusNetworks/SELKS/files/1209836/elasticsearchlog.txt)
[logstash-plain-log.txt](https://github.com/StamusNetworks/SELKS/files/1209835/logstash-plain-log.txt)

Thanks,

**Comment by pevma** [comment]
As you mentioned - there is not so much in hte logs that may indicate a lead of the problem you describe.  

Can you try upgrading - ` /opt/selks/Scripts/Setup/selks-upgrade_stamus.sh` and see if that will have any effect for the better?

When you mention initially that alert activity stops - how exactly do you mean? (since you also mention that elasticsearch actively logs the data and it is visible in Kibana?)

**Comment by drikusb** [comment]
so my head of sec decided to stop further troubleshooting on this for a while.

in terms of your question, it seems to have been just the graphing that stopped, and to the managers it raised concerns as to what else may be stopping that doesn't have a visual indicator like the graph does.

thanks for the help.

**Comment by pevma** [comment]
If you help us out understanding the problem exactly we may be able to help you and your management :) 
For example Scirius does not shoe graphs past 7 days. Which graphs stopped showing progress - all, some, which dashboards in Kibana?
