### ISSUE TITLE
threshold option

### ISSUE THREAD

**Issue by bbatmandakh** [StamusNetworks/SELKS#86]
I testing selks4.0 with some threshold rules. I wonder does selks4.0(suricata) support threshold option?
In my test its looks like not working...

example: content:"OPTIONS"; http_method; threshold: type limit, count 30, track by_src, seconds 30;

**Comment by pevma** [comment]
Suricata supports it and you can do that right out of Scirius when you are on the signature details page - you have  a wide range of choices - threshold,suppress,transform,disable etc..

Did you check as first step if the rule loads correctly as expected - you can check if there are any errors with respect to the rule in `/var/log/suricata/suricata.log`

**Comment by bbatmandakh** [comment]
oh looks like threshold option problem...thanks for respond.

Issue closed.
