### ISSUE TITLE
SELKS 4 gives link error

### ISSUE THREAD

**Issue by viris** [StamusNetworks/SELKS#87]
Clean isntall, updated, upgraded and when going to SN ALERTS dashboard, gives this error:

Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"link error","script_stack":["doc['alert.signature_id'].value","     ^---- HERE"],"script":"doc['alert.signature_id'].value","lang":"expression"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"logstash-tls-2017.09.22","node":"xTw0GUQJSG6GhDJg0D8Q0A","reason":{"type":"script_exception","reason":"link error","script_stack":["doc['alert.signature_id'].value","     ^---- HERE"],"script":"doc['alert.signature_id'].value","lang":"expression","caused_by":{"type":"parse_exception","reason":"Field [alert.signature_id] does not exist in mappings"}}}]},"status":500}

Any clue, hint, how to make this go away? I see one shard is also not assingned.

**Comment by pevma** [comment]
Did you follow the upgrade procedure from the Wiki ? ( https://github.com/StamusNetworks/SELKS/wiki/SELKS-upgrades )

Try resetting the dashboards - 
You can do a reload or reset of dashboards from the Scirius graphic interface (https://selks.ip.here) -

Go to System settings (from the Stamus logo drop down menu in the left upper corner) -> Kibana -> choose to reset the dashboards.



Let us know if it helps.


> -- 
> Regards,
> Peter Manev

**Comment by viris** [comment]
It was clean install from latest ISO. After that update and upgrade to latest versions. 
It might have something to do with running apt upgrade in wrong time.

Thanks for hint. It works now! ;)
