### ISSUE TITLE
SELKS upgrade error with desktop-base with quick and dirty fix

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/SELKS#89]
Noticed an error when using the selks-upgrade_stamus.sh on a fresh install.
I could fix the issue up to a point, but there is still an error. Below are the steps I have taken and the error I am getting.

an upgrade using the selks-upgrade_stamus.sh runs fine and does update everything but then produces the following errors:

root@SELKS:/opt/selks/Scripts/Setup# ./selks-upgrade_stamus.sh 

Hit:1 http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease                                                                                                      

Ign:2 http://ftp.uk.debian.org/debian stretch InRelease                                                                                                                       

Hit:3 http://packages.stamus-networks.com/selks4/debian stretch InRelease                                                                                                     

Hit:4 http://ftp.uk.debian.org/debian stretch-updates InRelease                                                                                                               

Hit:6 http://security.debian.org/debian-security stretch/updates InRelease                                           

Hit:7 http://packages.stamus-networks.com/selks4/debian-kernel stretch InRelease               

Hit:8 http://ftp.uk.debian.org/debian stretch Release                                               

Hit:9 http://packages.elastic.co/curator/4/debian stable InRelease                                  

Hit:5 http://evebox.org/files/debian stable InRelease                         

Ign:11 https://artifacts.elastic.co/packages/5.x/apt stable InRelease

Hit:12 https://artifacts.elastic.co/packages/5.x/apt stable Release

Reading package lists... Done

Reading package lists... Done

Building dependency tree       

Reading state information... Done

Calculating upgrade... Done

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

1 not fully installed or removed.

After this operation, 0 B of additional disk space will be used.

Do you want to continue? [Y/n] y

Setting up desktop-base (9.0.2+deb9u1) ...

update-alternatives: error: cannot stat file '/etc/alternatives/desktop-background': Invalid argument

dpkg: error processing package desktop-base (--configure):

 subprocess installed post-installation script returned error exit status 2

Errors were encountered while processing:

 desktop-base

E: Sub-process /usr/bin/dpkg returned an error code (1)

scirius: stopped

scirius: started

Looking into more details I ran a apt-get update to find out if there could be an issue with that part, and yes there is:

root@SELKS:/opt/selks/Scripts/Setup# apt-get update

Get:1 http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease [13.3 kB]                                                                                            

Ign:1 http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease                                                                                                      

Hit:3 http://security.debian.org/debian-security stretch/updates InRelease                                                                                                    

Ign:4 http://ftp.uk.debian.org/debian stretch InRelease                                                                               

Hit:5 http://packages.elastic.co/curator/4/debian stable InRelease                                                                    

Hit:6 http://ftp.uk.debian.org/debian stretch-updates InRelease          

Hit:7 http://packages.stamus-networks.com/selks4/debian stretch InRelease                           

Hit:8 http://ftp.uk.debian.org/debian stretch Release                                                                 

Ign:10 https://artifacts.elastic.co/packages/5.x/apt stable InRelease                          

Hit:11 http://packages.stamus-networks.com/selks4/debian-kernel stretch InRelease

Hit:2 http://evebox.org/files/debian stable InRelease

Hit:12 https://artifacts.elastic.co/packages/5.x/apt stable Release

Fetched 13.3 kB in 2s (6,327 B/s)

Reading package lists... Done

W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886

W: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease' is not signed.

N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

N: See apt-secure(8) manpage for repository creation and user configuration details.

Using the ALTERNATIVE METHOD  instructions from 
https://askubuntu.com/questions/13065/how-do-i-fix-the-gpg-error-no-pubkey

Fixed the GPG error issue by manually adding the missing key.
So I though this would be it!
An apt-get update does not generate any more errors.

However, running the SELKS upgrade script still generates the same error on the desktop-base package.

So here is the quick and dirty fix from Pevma:

mv /etc/alternatives/desktop-background /tmp 

/opt/selks/Scripts/Setup/selks-upgrade_stamus.sh 

mv /tmp/desktop-background /etc/alternatives/ 

Cheers,
B.

**Comment by pevma** [comment]
I have updated the upgrade page with a proper fix [here](https://github.com/StamusNetworks/SELKS/wiki/SELKS-upgrades)

**Comment by b-u-g-s** [comment]
Great, thanks!
