### ISSUE TITLE
Data lifecycle script error

### ISSUE THREAD

**Issue by freeblue** [StamusNetworks/SELKS#93]
Hi, very new to SELKS, just installed it for testing purpose on a test computer that has not enough disk space to handle 14 days retention, i have configured the script /opt/selks/delete-old-logs.sh to prune data older than 4 days.
We are using the latest SELKS iso distribution (which include Scirius CE v1.2.6).

When i execute this script manually (/opt/selks/delete-old-logs.sh), i get the following error : 
2017-11-07 14:04:47,648 ERROR     Singleton action failed due to empty index list

Any idea?

Best regards,

Alex

**Comment by pevma** [comment]
It returns ``empty index list`` since you dont have any indexes older than 4 days :) - so you are good i think.

**Comment by freeblue** [comment]
Thank you very much Pevma for your clear explanations!
That make sense now :)
I have just modified unit_count to an inferior value and it works as expected.

Have a nice day.

Best regards,

Alex
