### ISSUE TITLE
Error (when upgrade) the instalation version

### ISSUE THREAD

**Issue by borbelyau** [StamusNetworks/SELKS#94]
Hi guys... 
I installed today Selks... and update all packages...
when I look the terminal... one message  appears ...

 python3 /usr/share/python/scirius/bin/manage.py migrate accounts --fake 0001_initial
Traceback (most recent call last):
  File "/usr/share/python/scirius/bin/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

I instaled django, python-django... and nothing.... help me guys

**Comment by pevma** [comment]
> On 7 Nov 2017, at 17:10, borbelyau <notifications@github.com> wrote:
> 
> Hi guys...
> I installed today Selks... and update all packages...
> when I look the terminal... one message appears ...
> 
> python3 /usr/share/python/scirius/bin/manage.py migrate accounts --fake 0001_initial
> Traceback (most recent call last):
> File "/usr/share/python/scirius/bin/manage.py", line 8, in 
> from django.core.management import execute_from_command_line
> ImportError: No module named 'django'
> 
> I instaled django, python-django... and nothing.... help me guys
> 

Thanks for trying out SELKS.
How did you upgrade? Did you follow the upgrade procedure explained here - 
https://github.com/StamusNetworks/SELKS/wiki/SELKS-upgrades

Thanks

**Comment by borbelyau** [comment]
@pevma  tks bro... no i upgrade with dist-upgrade...and now crash my graphical interface view...

**Comment by borbelyau** [comment]
the error that I got

Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, django_tables2, revproxy, dbbackup, bootstrap3
  Apply all migrations: sessions, admin, suricata, auth, rules, contenttypes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
/var/lib/scirius
Configurando ffmpeg (7:3.2.8-1~deb9u1) ...
Configurando git (1:2.11.0-3+deb9u2) ...
Configurando apt-transport-https (1.4.8) ...
Configurando curl (7.52.1-5+deb9u2) ...
Configurando git-core (1:2.11.0-3+deb9u2) ...
A processar 'triggers' para libc-bin (2.24-11+deb9u1) ...
Erros foram encontrados durante o processamento de:
 desktop-base
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@x:/home/selks-user# find / -name manage.py
find: ‘/run/user/112/gvfs’: Permissão negada
find: ‘/run/user/1000/gvfs’: Permissão negada
/usr/share/python/scirius/bin/manage.py
/usr/share/python/scirius/lib/python2.7/site-packages/django/conf/project_template/manage.py
root@x:/home/selks-user# python2.7 /usr/share/python/scirius/bin/manage.py migrate --fake accounts 0001_initial
Traceback (most recent call last):
  File "/usr/share/python/scirius/bin/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
root@x:/home/selks-user#

**Comment by borbelyau** [comment]
basic the error is this

root@x:/home/selks-user# python2.7 /usr/share/python/scirius/bin/manage.py migrate --fake accounts 0001_initial
Traceback (most recent call last):
File "/usr/share/python/scirius/bin/manage.py", line 8, in
from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
