### ISSUE TITLE
Errors after the update

### ISSUE THREAD

**Issue by hawatius** [StamusNetworks/SELKS#97]
Hi.
After updating `/opt/selks/Scripts/Setup/selks-upgrade_stamus.sh` suricata stopped working.

suricata.log
```
[20226] 21/12/2017 -- 15:53:26 - (source-pcap-file-directory-helper.c:205) <Error> (PcapDetermineDirectoryOrFile) -- [ERRCODE: SC_ERR_FOPEN(44)] - -: Does not exist, or name is an empty string
[20207] 21/12/2017 -- 15:53:26 - (tm-threads.c:2137) <Error> (TmThreadWaitOnThreadInit) -- [ERRCODE: SC_ERR_THREAD_INIT(49)] - thread "RX#01" failed to initialize: flags 0145
[20207] 21/12/2017 -- 15:53:26 - (suricata.c:2923) <Error> (main) -- [ERRCODE: SC_ERR_INITIALIZATION(45)] - Engine initialization failed, aborting...
```
How can I fix this?
uname -a
`Linux SELKS 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux`
suricata -V
`This is Suricata version 4.1.0-dev (rev 70695201)`

**Comment by pevma** [comment]
> 


> On 21 Dec 2017, at 14:01, hawatius <notifications@github.com> wrote:
> 
> Hi.
> After updating /opt/selks/Scripts/Setup/selks-upgrade_stamus.sh suricata stopped working.
> 
> suricata.log
> 
> [20226] 21/12/2017 -- 15:53:26 - (source-pcap-file-directory-helper.c:205) <Error> (PcapDetermineDirectoryOrFile) -- [ERRCODE: SC_ERR_FOPEN(44)] - -: Does not exist, or name is an empty string
> [20207] 21/12/2017 -- 15:53:26 - (tm-threads.c:2137) <Error> (TmThreadWaitOnThreadInit) -- [ERRCODE: SC_ERR_THREAD_INIT(49)] - thread "RX#01" failed to initialize: flags 0145
> [20207] 21/12/2017 -- 15:53:26 - (suricata.c:2923) <Error> (main) -- [ERRCODE: SC_ERR_INITIALIZATION(45)] - Engine initialization failed, aborting...

I wasn’t able to reproduce this.
Did you do any changes to the Suricata  yaml config ?

Can you please post the full section of the suricata.log when it starts?

Thank you

**Comment by hawatius** [comment]
Thank you very much for your answer!
I understood when there is an error. I run Suricata together with **trafr** to collect traffic (https://wiki.mikrotik.com/wiki/Mikrotik_IPS_IDS)
Before the update, it worked. `./trafr -s | suricata -c /etc/suricata/suricata.yaml --runmode autofp -r -`
Can you help me with this?

**Comment by pevma** [comment]
````
root@SELKS:/opt/work# suricata -c /etc/suricata/suricata.yaml --runmode=autofp -r
suricata: option requires an argument -- 'r'

```

You need to specify an argument with the ``-r`` option with Suricata

**Comment by hawatius** [comment]
argument -r **'-'**
`./trafr -s | suricata -c /etc/suricata/suricata.yaml --runmode autofp -r -`

**Comment by hawatius** [comment]
The problem is solved.
After update suricata ceased to understand correctly "-r -" change to "-r /dev/stdin" solved the problem.
`./trafr -s | suricata -c /etc/suricata/suricata.yaml --runmode autofp -v -r /dev/stdin`
Thank you very much for your help!

**Comment by pevma** [comment]
The problem is that if you issue the command  (Notice ``=`` ) : 
``suricata -c /etc/suricata/suricata.yaml --runmode=autofp -r`` you need to supply a pcap/folder to Suricata (``suricata -h``). But with the command line :  
``./trafr -s | suricata -c /etc/suricata/suricata.yaml --runmode=autofp -r -`` seems it does not find any such. ..

I could not start ``./trafr`` itself either to be honest to reproduce it.
Any extra info there?

**Comment by pevma** [comment]
Yep that will work.
Thank you for posting the solution!

**Comment by hawatius** [comment]
For work ./trafr need a library libc6:i386
```
dpkg --add-architecture i386
apt-get update
apt-get install libc6:i386
```
