### ISSUE TITLE
Dashboards Error

### ISSUE THREAD

**Issue by jfichera66** [StamusNetworks/SELKS#98]
New install of SELKS on new VirtualBox. Ran the update script and it was successful. Everything is working except the dashboards. Getting the same error for all of them. Connection refused. I have tried resetting the SN dashboards with no luck.

![image](https://user-images.githubusercontent.com/12954550/34423890-04cc54f2-ebe5-11e7-824c-9207c89c369b.png)

**Comment by pevma** [comment]
Can you try restarting Scirius and see if any difference  - ``supervisorctl restart scirius`` ?

**Comment by jfichera66** [comment]
Did that. Same issue. Even did a restart of system.

**Comment by pevma** [comment]
I just tried to reproduce that from scratch download and I couldn't.
Can you please run the update script again and see if you dont get the err here (`desktop-base`)? If so the fix is explained and you should rerun the update script once more.

**Comment by jfichera66** [comment]
I am using the SELKS with desktop version. Will run script again and advise.

**Comment by jfichera66** [comment]
Deleted the entire VM and built a new one. Everything appears to be working correctly now.

**Comment by pevma** [comment]
Glad it worked out.
If you ever find the original reason why - please reopen/report a bug issue again.
Thanks for trying out SELKS !
